/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "addrof3.c"
struct qstr {
   unsigned char const   *name ;
   unsigned int len ;
   unsigned int hash ;
};
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  9 "addrof3.c"
struct qstr *foo(struct qstr  const  *p ) 
{ 


  {
//#line  10
  return ((struct qstr *)p);
}
}
//#line  13 "addrof3.c"
int main(void) 
{ 
  struct qstr *x ;
  struct qstr __constr_expr_0 ;
  struct qstr *tmp ;

  {
//#line  15
  __constr_expr_0.name = (unsigned char const   *)"socket:";
//#line  15
  __constr_expr_0.len = 7U;
//#line  15
  __constr_expr_0.hash = 0U;
//#line  15
  tmp = foo((struct qstr  const  *)(& __constr_expr_0));
//#line  15
  x = tmp;
//#line  16
  if ((int const   )*(x->name + 1) != 111) {
//#line  16
    printf("Error %d\n", 1);
//#line  16
    exit(1);
  }
//#line  18
  if (x->len != 7U) {
//#line  18
    printf("Error %d\n", 2);
//#line  18
    exit(2);
  }
//#line  20
  printf("Success\n");
//#line  20
  exit(0);
}
}
