/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "addr-array.c"
int main(void) 
{ 
  int a[10] ;
  int (*pa)[10] ;
  int m[4][7] ;

  {
//#line  13
  if ((int )(& a + 1) != (int )(a + 10)) {
//#line  13
    printf("Error %d\n", 1);
//#line  13
    exit(1);
  }
//#line  15
  pa = & a;
//#line  16
  if ((unsigned long )(& (*(pa + 0))[5]) != (unsigned long )(& a[5])) {
//#line  16
    printf("Error %d\n", 2);
//#line  16
    exit(2);
  }
//#line  18
  if ((unsigned long )((char *)(& m + 1)) != (unsigned long )((char *)(m) + 28UL * sizeof(int ))) {
//#line  18
    printf("Error %d\n", 3);
//#line  18
    exit(3);
  }
//#line  20
  if ((unsigned long )((char *)(& m[2])) != (unsigned long )((char *)(m + 2))) {
//#line  20
    printf("Error %d\n", 4);
//#line  20
    exit(4);
  }
//#line  22
  printf("Success\n");
//#line  22
  exit(0);
}
}
