/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  328 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef int wchar_t;
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  4 "addr-string.c"
int main(void) 
{ 
  char (*p)[4] ;
  wchar_t (*q)[4] ;

  {
//#line  7
  p = (char (*)[4])"bar";
//#line  8
  q = (wchar_t (*)[4])L"foO";
//#line  10
  if ((int )(*p)[1] != 97) {
//#line  10
    printf("Error %d\n", 1);
//#line  10
    exit(1);
  }
//#line  11
  if ((*q)[1] != 111) {
//#line  11
    printf("Error %d\n", 2);
//#line  11
    exit(2);
  }
//#line  13
  printf("Success\n");
//#line  13
  exit(0);
}
}
