/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  17 "align3.c"
struct s1 {
   short a ;
   char b ;
   short c ;
};
//#line  51 "align3.c"
struct s4 {
   short a ;
   char b ;
};
//#line  71 "align3.c"
struct s5 {
   short a ;
   char b ;
} __attribute__((__aligned__)) ;
//#line  23 "align3.c"
struct s1  __attribute__((__aligned__(1))) s1_1  ;
//#line  24 "align3.c"
struct s1 s1_2  ;
//#line  25 "align3.c"
struct s1  __attribute__((__aligned__(4))) s1_4  ;
//#line  27 "align3.c"
struct s1  __attribute__((__aligned__((1) <<  (7) ))) s1_128  ;
//#line  57 "align3.c"
struct s4  __attribute__((__aligned__)) s4_4  ;
//#line  65 "align3.c"
struct s4  __attribute__((__aligned__((sizeof(double )) /  (2) ))) s4_int  ;
//#line  67 "align3.c"
struct s4  __attribute__((__aligned__(__alignof__(int )))) s4_db  ;
//#line  71 "align3.c"
struct s5 foo  ;
//#line  75 "align3.c"
struct s5 s5_4  ;
//#line  80 "align3.c"
int i  ;
//#line  81 "align3.c"
int __attribute__((__aligned__(1)))  i_1  ;
//#line  84
extern int ( /* missing proto */  printf)() ;
//#line  83 "align3.c"
int main(void) 
{ 


  {
//#line  84
  printf("%d, %d\n", sizeof(i), __alignof__(i));
//#line  85
  printf("%d, %d\n", sizeof(i_1), __alignof__(i_1));
//#line  86
  printf("%d, %d\n", sizeof(s4_4), __alignof__(s4_4));
//#line  87
  return (0);
}
}
