/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "align1.c"
struct testalign {
   int f1 ;
} __attribute__((__aligned__(16))) ;
//#line  8 "align1.c"
struct t1 {
   int f0 ;
   struct testalign a ;
};
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  13 "align1.c"
int main(void) 
{ 
  int offset ;

  {
//#line  16
  offset = (int )(& ((struct t1 *)0)->a.f1);
//#line  17
  printf("Offset is: %d\n", offset);
//#line  19
  if ((int )(& ((struct t1 *)0)->a.f1) & 15) {
//#line  20
    printf("Error %d\n", 1);
//#line  20
    exit(1);
  }
//#line  24
  printf("Success\n");
//#line  24
  exit(0);
}
}
