/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "apachefptr.c"
int (*read_buf)(void *arg1 , char *arg2 , int arg3 )  ;
//#line  5 "apachefptr.c"
int file_read(void *gz1 , char *buf , int size ) 
{ 
  int total ;
  int i ;

  {
//#line  6
  total = 0;
//#line  7
  i = 0;
//#line  7
  while (i < size) {
//#line  8
    total += (int )*(buf + i);
//#line  7
    i ++;
  }
//#line  9
  return (total);
}
}
//#line  12 "apachefptr.c"
int main(void) 
{ 
  char mybuffer[5] ;
  char sum ;
  void *foo ;
  int tmp ;

  {
//#line  13
  mybuffer[0] = (char)1;
//#line  13
  mybuffer[1] = (char)2;
//#line  13
  mybuffer[2] = (char)3;
//#line  13
  mybuffer[3] = (char)4;
//#line  13
  mybuffer[4] = (char)5;
//#line  13
  sum = (char)0;
//#line  14
  foo = (void *)0;
//#line  16
  read_buf = & file_read;
//#line  18
  tmp = (*read_buf)(foo, mybuffer, 5);
//#line  18
  sum = (char )tmp;
//#line  20
  if ((int )sum == 15) {
//#line  20
    printf("Success\n");
//#line  20
    exit(0);
  } else {
//#line  21
    printf("Error %d\n", 1);
//#line  21
    exit(1);
  }
}
}
