/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  5 "apachebits.c"
struct uri_components {
   void *hostent ;
   unsigned short port ;
   unsigned int is_initialized : 1 ;
   unsigned int dns_looked_up : 1 ;
   unsigned int dns_resolved : 1 ;
};
//#line  5 "apachebits.c"
typedef struct uri_components uri_components;
//#line  32 "apachebits.c"
struct request_rec {
   uri_components parsed_uri ;
   void *per_dir_config ;
};
//#line  32 "apachebits.c"
typedef struct request_rec request_rec;
//#line  362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  95 "apachebits.c"
int main(void) 
{ 
  request_rec r ;
  void **offset ;
  long diff ;

  {
//#line  100
  offset = & r.per_dir_config;
//#line  102
  diff = (long )offset - (long )(& r);
//#line  104
  printf((char const   */* __restrict  */)"offset is %ld (and should be 8 with gcc version 2.95.3 19991030 (prerelease))\n",
         diff);
//#line  105
  return (0);
}
}
