/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  2 "argcast.c"
static unsigned char buf[16]  ;
//#line  4
int walk(char *a , int l ) ;
//#line  1 "argcast.c"
int main(void) 
{ 
  unsigned char *bp ;

  {
//#line  3
  bp = buf;
//#line  4
  walk(buf, 9);
//#line  5
  return (0);
}
}
//#line  8 "argcast.c"
int walk(char *a , int l ) 
{ 
  int i ;

  {
//#line  11
  i = 0;
//#line  11
  while (i < l) {
//#line  12
    *(a + i) = (char )((int )*(a + i) + 1);
//#line  11
    i ++;
  }
//#line  14
  return (i);
}
}
