/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "array1.c"
struct bitmap {
   unsigned long resident[13] ;
   int words ;
   int allocated_rest ;
   unsigned long *rest ;
};
//#line  3 "array1.c"
typedef struct bitmap BITMAP;
//#line  10 "array1.c"
struct ornode {
   int *or_const ;
   BITMAP any ;
   BITMAP all ;
};
//#line  10 "array1.c"
typedef struct ornode ORNODE;
//#line  18 "array1.c"
union __anonunion_u_909908078 {
   BITMAP nullary ;
   struct ornode args[0] ;
};
//#line  18 "array1.c"
struct andnode {
   int count ;
   int arity ;
   union __anonunion_u_909908078 u ;
};
//#line  18 "array1.c"
typedef struct andnode ANDNODE;
//#line  31 "array1.c"
int main_o(ANDNODE *a ) 
{ 
  ORNODE b ;

  {
//#line  32
  b = a->u.args[1];
//#line  33
  return (0);
}
}
