/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  16 "array2.c"
void radiatepiece(int s , int gral , int c , int (*rtval)[26] ) 
{ 


  {
//#line  18
  s = (*(rtval + 2))[3];
//#line  20
  return;
}
}
