/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  5 "array_formal.c"
int foo(int n , int *ra ) 
{ 


  {
//#line  6
  printf("sizeof(ra) = %d.  sizeof(*ra) = %d\n", sizeof(ra), sizeof(*ra));
//#line  7
  if (sizeof(ra) != sizeof(int *)) {
//#line  7
    printf("Error %d\n", 1);
//#line  7
    exit(1);
  }
//#line  8
  if (sizeof(*ra) != sizeof(int )) {
//#line  8
    printf("Error %d\n", 2);
//#line  8
    exit(2);
  }
//#line  9
  return (n);
}
}
//#line  13 "array_formal.c"
int test(int n , int (*ra)[100] ) 
{ 


  {
//#line  14
  printf("sizeof(ra) = %d.  sizeof(*ra) = %d\n", sizeof(ra), sizeof(*ra));
//#line  15
  if (sizeof(ra) != sizeof(int *)) {
//#line  15
    printf("Error %d\n", 11);
//#line  15
    exit(11);
  }
//#line  16
  if (sizeof(*ra) != 100UL * sizeof(int )) {
//#line  16
    printf("Error %d\n", 12);
//#line  16
    exit(12);
  }
//#line  17
  return (n);
}
}
//#line  21 "array_formal.c"
int test2(int n , int (*ra)[100] ) 
{ 


  {
//#line  22
  printf("sizeof(ra) = %d.  sizeof(*ra) = %d\n", sizeof(ra), sizeof(*ra));
//#line  23
  if (sizeof(ra) != sizeof(int *)) {
//#line  23
    printf("Error %d\n", 21);
//#line  23
    exit(21);
  }
//#line  24
  if (sizeof(*ra) != 100UL * sizeof(int )) {
//#line  24
    printf("Error %d\n", 22);
//#line  24
    exit(22);
  }
//#line  25
  return (n);
}
}
//#line  39 "array_formal.c"
int main(void) 
{ 


  {
//#line  40
  foo(10, (int *)0);
//#line  41
  test(10, (int (*)[100])0);
//#line  42
  test2(10, (int (*)[100])0);
//#line  43
  printf("Success\n");
//#line  43
  exit(0);
}
}
