/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

/* compiler builtin: 
   void *__builtin_alloca(unsigned long  ) ;  */
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  4 "array_varsize.c"
void foo(int n , int *a ) ;
//#line  6 "array_varsize.c"
int main(void) 
{ 
  int a[40] ;

  {
//#line  9
  foo(40, (int *)(a));
//#line  10
  printf("Success\n");
//#line  10
  exit(0);
}
}
//#line  15 "array_varsize.c"
void foo(int n , int *a ) 
{ 
  double *b ;
  unsigned long __lengthofb ;
  void *tmp ;
  int *p ;

  {
//#line  17
  __lengthofb = (unsigned long )n;
//#line  17
  tmp = __builtin_alloca(sizeof(*b) * __lengthofb);
//#line  17
  b = (double *)tmp;
//#line  18
  *(a + (n - 1)) = 0;
//#line  19
  *(b + (n - 1)) = 0.0;
//#line  20
  printf("sizeof(a) = %d, sizeof(b) = %d\n", sizeof(a), sizeof(*b) * __lengthofb);
//#line  23
  p = (int *)a;
//#line  24
  p ++;
//#line  25
  if (sizeof(a) != sizeof(p)) {
//#line  25
    printf("Error %d\n", 2);
//#line  25
    exit(2);
  }
//#line  29
  if (sizeof(*b) * __lengthofb != (unsigned long )n * sizeof(double )) {
//#line  29
    printf("Error %d\n", 3);
//#line  29
    exit(3);
  }
//#line  30
  return;
}
}
