/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  20 "array-size-trick.c"
int array[3]  = {      9,      11,      13};
//#line  33 "array-size-trick.c"
int main(void) 
{ 
  unsigned int i ;

  {
//#line  38
  i = 0U;
//#line  38
  while (i < 3U) {
//#line  40
    printf((char const   */* __restrict  */)"a[%u]: %d\n", i, array[i]);
//#line  38
    i ++;
  }
//#line  43
  return (0);
}
}
