/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  12 "arrayinitsize.c"
struct X {
   int a ;
   int b ;
   int z[] ;
};
//#line  10
extern void abort() ;
//#line  19 "arrayinitsize.c"
struct X x  =    {0, 40, {3, 4}};
//#line  21 "arrayinitsize.c"
int main(void) 
{ 


  {
//#line  23
  if (x.b != 40) {
//#line  24
    abort();
  }
//#line  33
  return (0);
}
}
