/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  9 "arrsize.c"
typedef int g4[(1ULL << (8UL * sizeof(int ) - 2UL)) / (unsigned long long )sizeof(int )];
//#line  10 "arrsize.c"
typedef char g5[(1ULL << (8UL * sizeof(int ) - 2UL)) / (unsigned long long )sizeof(char )];
//#line  11 "arrsize.c"
typedef double g6[(1ULL << (8UL * sizeof(int ) - 2UL)) / (unsigned long long )sizeof(double )];
//#line  13 "arrsize.c"
struct cmsghdr {
   int cmsg_type ;
   unsigned char __cmsg_data[] ;
};
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  5 "arrsize.c"
int g1[(1ULL << (8UL * sizeof(int ) - 2UL)) / (unsigned long long )sizeof(int )]  ;
//#line  6 "arrsize.c"
char g2[(1ULL << (8UL * sizeof(int ) - 2UL)) / (unsigned long long )sizeof(char )]  ;
//#line  7 "arrsize.c"
double g3[(1ULL << (8UL * sizeof(int ) - 2UL)) / (unsigned long long )sizeof(double )]  ;
//#line  20 "arrsize.c"
void os_rcv_fd(void) 
{ 
  char buf[sizeof(struct cmsghdr )] ;

  {
//#line  24
  buf[0] = (char)0;
//#line  25
  return;
}
}
//#line  27 "arrsize.c"
int main(void) 
{ 
  g4 *p1 ;
  g5 *p2 ;
  g6 *p3 ;

  {
//#line  28
  p1 = & g1;
//#line  29
  p2 = & g2;
//#line  30
  p3 = & g3;
//#line  32
  g1[(1ULL << (8UL * sizeof(int ) - 2UL)) / (unsigned long long )sizeof(int ) - 1ULL] = 1;
//#line  33
  g2[(1ULL << (8UL * sizeof(int ) - 2UL)) / (unsigned long long )sizeof(char ) - 1ULL] = (char)2;
//#line  34
  g3[(1ULL << (8UL * sizeof(int ) - 2UL)) / (unsigned long long )sizeof(double ) - 1ULL] = (double )3;
//#line  36
  if ((*(p1 + ((1ULL << (8UL * sizeof(int ) - 2UL)) / (unsigned long long )sizeof(int ) - 1ULL)))[0] != 1) {
//#line  36
    printf("Error %d\n", 1);
//#line  36
    exit(1);
  }
//#line  37
  if ((int )(*(p2 + ((1ULL << (8UL * sizeof(int ) - 2UL)) / (unsigned long long )sizeof(char ) - 1ULL)))[0] != 2) {
//#line  37
    printf("Error %d\n", 2);
//#line  37
    exit(2);
  }
//#line  38
  if ((*(p3 + ((1ULL << (8UL * sizeof(int ) - 2UL)) / (unsigned long long )sizeof(double ) - 1ULL)))[0] != (double )3) {
//#line  38
    printf("Error %d\n", 3);
//#line  38
    exit(3);
  }
//#line  40
  return (0);
}
}
