/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "asm2.c"
__inline extern double atan(double __x ) 
{ 
  register double __result ;

  {
//#line  3
  __asm__  volatile   ("fld1; fpatan": "=t" (__result): "0" (__x): "st(1)");
//#line  7
  return (__result);
}
}
