/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "asm3.c"
__inline extern double floor(double __x ) 
{ 
  register long double __value ;
  unsigned short volatile   __cw ;
  unsigned short volatile   __cwtmp ;

  {
//#line  1
  __asm__  volatile   ("fnstcw %0": "=m" (__cw));
//#line  1
  __cwtmp = (unsigned short volatile   )(((int volatile   )__cw & (int volatile   )62463) | (int volatile   )1024);
//#line  1
  __asm__  volatile   ("fldcw %0": : "m" (__cwtmp));
//#line  1
  __asm__  volatile   ("frndint": "=t" (__value): "0" (__x));
//#line  1
  __asm__  volatile   ("fldcw %0": : "m" (__cw));
//#line  1
  return ((double )__value);
}
}
//#line  3 "asm3.c"
__inline extern float floorf(float __x ) 
{ 
  register long double __value ;
  unsigned short volatile   __cw ;
  unsigned short volatile   __cwtmp ;

  {
//#line  3
  __asm__  volatile   ("fnstcw %0": "=m" (__cw));
//#line  3
  __cwtmp = (unsigned short volatile   )(((int volatile   )__cw & (int volatile   )62463) | (int volatile   )1024);
//#line  3
  __asm__  volatile   ("fldcw %0": : "m" (__cwtmp));
//#line  3
  __asm__  volatile   ("frndint": "=t" (__value): "0" (__x));
//#line  3
  __asm__  volatile   ("fldcw %0": : "m" (__cw));
//#line  3
  return ((float )__value);
}
}
//#line  3 "asm3.c"
__inline extern long double floorl(long double __x ) 
{ 
  register long double __value ;
  unsigned short volatile   __cw ;
  unsigned short volatile   __cwtmp ;

  {
//#line  3
  __asm__  volatile   ("fnstcw %0": "=m" (__cw));
//#line  3
  __cwtmp = (unsigned short volatile   )(((int volatile   )__cw & (int volatile   )62463) | (int volatile   )1024);
//#line  3
  __asm__  volatile   ("fldcw %0": : "m" (__cwtmp));
//#line  3
  __asm__  volatile   ("frndint": "=t" (__value): "0" (__x));
//#line  3
  __asm__  volatile   ("fldcw %0": : "m" (__cw));
//#line  3
  return (__value);
}
}
