/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  5 "asm4.c"
typedef signed char gint8;
//#line  7 "asm4.c"
typedef short gint16;
//#line  8 "asm4.c"
typedef unsigned short guint16;
//#line  9 "asm4.c"
typedef int gint32;
//#line  10 "asm4.c"
typedef unsigned int guint32;
//#line  12 "asm4.c"
typedef long long gint64;
//#line  13 "asm4.c"
typedef unsigned long long guint64;
//#line  48 "asm4.c"
union __anonunion___r_425203202 {
   guint64 __ll ;
   guint32 __l[2] ;
};
//#line  48 "asm4.c"
union __anonunion___w_425203203 {
   guint64 __ll ;
   guint32 __l[2] ;
};
//#line  38
extern int ( /* missing proto */  printf)() ;
//#line  26 "asm4.c"
int main(int argc , char **argv ) 
{ 
  guint16 gu16t1 ;
  guint16 gu16t2 ;
  guint32 gu32t1 ;
  guint32 gu32t2 ;
  guint64 gu64t1 ;
  guint64 gu64t2 ;
  register guint16 __v ;
  register guint32 __v___0 ;
  union __anonunion___r_425203202 __r ;
  union __anonunion___w_425203203 __w ;
  register guint32 __v___1 ;
  register guint32 __v___2 ;

  {
//#line  30
  gu16t1 = (guint16 )17583U;
//#line  30
  gu16t2 = (guint16 )44868U;
//#line  31
  gu32t1 = 44560649U;
//#line  31
  gu32t2 = 166831874U;
//#line  33
  gu64t1 = 2117653906934364839ULL;
//#line  33
  gu64t2 = 0xa77a0a30026b631dULL;
//#line  38
  if (! (sizeof(gint8 ) == 1UL)) {
//#line  38
    printf("file %s: line %d (%s): assertion failed: (%s)", "type-test.c", 47, "main",
           "sizeof (gint8) == 1");
  }
//#line  39
  if (! (sizeof(gint16 ) == 2UL)) {
//#line  39
    printf("file %s: line %d (%s): assertion failed: (%s)", "type-test.c", 48, "main",
           "sizeof (gint16) == 2");
  }
//#line  40
  if (! (sizeof(gint32 ) == 4UL)) {
//#line  40
    printf("file %s: line %d (%s): assertion failed: (%s)", "type-test.c", 49, "main",
           "sizeof (gint32) == 4");
  }
//#line  42
  if (! (sizeof(gint64 ) == 8UL)) {
//#line  42
    printf("file %s: line %d (%s): assertion failed: (%s)", "type-test.c", 51, "main",
           "sizeof (gint64) == 8");
  }
//#line  45
  __asm__  const   ("rorw $8, %w0": "=r" (__v): "0" (gu16t1));
//#line  45
  if (! ((int )__v == (int )gu16t2)) {
//#line  45
    printf("file %s: line %d (%s): assertion failed: (%s)", "type-test.c", 54, "main",
           "GUINT16_SWAP_LE_BE (gu16t1) == gu16t2");
  }
//#line  46
  __asm__  const   ("rorw $8, %w0\n\t"
                    "rorl $16, %0\n\t"
                    "rorw $8, %w0": "=r" (__v___0): "0" (gu32t1));
//#line  46
  if (! (__v___0 == gu32t2)) {
//#line  46
    printf("file %s: line %d (%s): assertion failed: (%s)", "type-test.c", 55, "main",
           "GUINT32_SWAP_LE_BE (gu32t1) == gu32t2");
  }
//#line  48
  __w.__ll = gu64t1;
//#line  48
  __asm__  const   ("rorw $8, %w0\n\t"
                    "rorl $16, %0\n\t"
                    "rorw $8, %w0": "=r" (__v___1): "0" (__w.__l[1]));
//#line  48
  __r.__l[0] = __v___1;
//#line  48
  __asm__  const   ("rorw $8, %w0\n\t"
                    "rorl $16, %0\n\t"
                    "rorw $8, %w0": "=r" (__v___2): "0" (__w.__l[0]));
//#line  48
  __r.__l[1] = __v___2;
//#line  48
  if (! (__r.__ll == gu64t2)) {
//#line  48
    printf("file %s: line %d (%s): assertion failed: (%s)", "type-test.c", 57, "main",
           "GUINT64_SWAP_LE_BE (gu64t1) == gu64t2");
  }
//#line  51
  return (0);
}
}
