/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  2 "asm_emptyclobberallowed.c"
int main(void) 
{ 


  {
//#line  3
  __asm__  ("xor %%eax, %%eax":);
//#line  7
  return (0);
}
}
