/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "assign.c"
int x  ;
//#line  8 "assign.c"
int main(void) 
{ 
  char p[3] ;
  char tmp ;
  char tmp___0 ;
  char tmp___1 ;

  {
//#line  13
  p[0] = (char)0;
//#line  14
  p[1] = (char)2;
//#line  15
  p[2] = (char)0;
//#line  16
  tmp = p[1];
//#line  16
  *(p + (int )p[0]) = tmp;
//#line  16
  if (tmp) {
//#line  17
    x = 1;
  } else {
//#line  19
    printf("Error %d\n", 1);
//#line  19
    exit(1);
  }
//#line  22
  p[0] = (char)0;
//#line  23
  p[1] = (char)2;
//#line  24
  p[2] = (char)5;
//#line  25
  tmp___0 = p[1];
//#line  25
  *(p + (int )p[0]) = tmp___0;
//#line  25
  if ((int )tmp___0 != 2) {
//#line  25
    printf("Error %d\n", 2);
//#line  25
    exit(2);
  }
//#line  27
  p[0] = (char)0;
//#line  28
  p[1] = (char)2;
//#line  29
  p[2] = (char)5;
//#line  30
  tmp___1 = p[1];
//#line  30
  p[p[0]] = tmp___1;
//#line  30
  if ((int )tmp___1 != 2) {
//#line  30
    printf("Error %d\n", 5);
//#line  30
    exit(5);
  }
//#line  32
  p[0] = (char)1;
//#line  33
  p[1] = (char)2;
//#line  34
  p[2] = (char)5;
//#line  35
  p[0] = p[p[0]];
//#line  35
  if ((int )p[0] != 2) {
//#line  35
    printf("Error %d\n", 8);
//#line  35
    exit(8);
  }
//#line  37
  printf("Success\n");
//#line  37
  exit(0);
//#line  38
  return (0);
}
}
