/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "attr11.c"
struct swsusp_info {
   unsigned int version_code ;
   unsigned long num_physpages ;
   int cpus ;
   unsigned long image_pages ;
   unsigned long pages ;
   unsigned long size ;
} __attribute__((__aligned__((1) <<  (12) ))) ;
//#line  13 "attr11.c"
struct swsusp_info global  ;
