/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "attr.c"
struct tm {
   int x ;
};
//#line  6
extern char *( __attribute__((__cdecl__)) asctime1)(struct tm  const  * ) ;
//#line  7
extern char *( __attribute__((__stdcall__)) asctime2)(struct tm  const  * ) ;
//#line  10
extern  __attribute__((__dllimport__)) unsigned long ( __attribute__((__stdcall__)) Int64ShllMod32)(void ( __attribute__((__stdcall__)) (*))() ) ;
//#line  25 "attr.c"
int *( __attribute__((__stdcall__)) (*x1[8]))(void)  ;
//#line  27 "attr.c"
void ( __attribute__((__stdcall__)) foo)(int x ) 
{ 


  {
//#line  28
  return;
}
}
//#line  31 "attr.c"
void main(void) 
{ 
  struct tm thetime ;
  char *t1 ;
  char *tmp ;
  char *t2 ;
  char *tmp___0 ;
  unsigned long l ;
  unsigned long tmp___1 ;

  {
//#line  34
  tmp = asctime1((struct tm  const  *)(& thetime));
//#line  34
  t1 = tmp;
//#line  35
  tmp___0 = asctime2((struct tm  const  *)(& thetime));
//#line  35
  t2 = tmp___0;
//#line  36
  tmp___1 = Int64ShllMod32((void ( __attribute__((__stdcall__)) (*))())(& foo));
//#line  36
  l = tmp___1;
//#line  37
  return;
}
}
