/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  20 "attr3.c"
int __attribute__((__a__(6)))  * __attribute__((__a__(5))) ( __attribute__((__a__(3))) (* __attribute__((__a__(2))) ( __attribute__((__a__(1))) x1)[5]))(int __attribute__((__a__(4)))   )  __attribute__((__name__))  ;
//#line  25
extern int __attribute__((__a__(7)))  * __attribute__((__a__(6))) ( __attribute__((__a__(4))) x2)(float __attribute__((__a__(5)))  x )  __attribute__((__name__)) ;
//#line  30 "attr3.c"
int __attribute__((__a__(7)))  * __attribute__((__a__(6))) ( __attribute__((__a__(4))) (* __attribute__((__a__(3))) ( __attribute__((__a__(1))) x3)(int __attribute__((__a__(2)))  x )))(float __attribute__((__a__(5)))   ) 
{ 


  {
//#line  31
  return ((int __attribute__((__a__(7)))  * __attribute__((__a__(6))) ( __attribute__((__a__(4))) (*/* __attribute__((__a__(3))) */))(float __attribute__((__a__(5)))   ))(& x2));
}
}
