/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "attr9.c"
enum state {
    Start = 0,
    Collect = 1,
    GotHeader = 2,
    SkipIt = 3,
    GotName = 4,
    CopyFile = 5,
    GotSymlink = 6,
    Reset = 7
} ;
//#line  35 "attr9.c"
struct foo {
   int field ;
};
//#line  39 "attr9.c"
union __anonunion_myunion_109580352 {
   int field ;
};
//#line  4 "attr9.c"
static enum state state  __attribute__((__section__(".init.data")))  ;
//#line  19 "attr9.c"
int ( __attribute__((__noinline__)) inflate_fixed)(void) 
{ 


  {
//#line  20
  return (0);
}
}
//#line  24 "attr9.c"
int main(void) 
{ 


  {
//#line  25
  state = (enum state )7;
//#line  26
  return (0);
}
}
//#line  32 "attr9.c"
enum state state2  __attribute__((__section__(".init.data")))  ;
//#line  33 "attr9.c"
enum state state3  __attribute__((__section__(".init.data")))  ;
//#line  35 "attr9.c"
struct foo mystruct  __attribute__((__section__(".init.data")))  ;
//#line  39 "attr9.c"
static union __anonunion_myunion_109580352 myunion  __attribute__((__section__(".init.data")))  ;
//#line  44 "attr9.c"
int test(void) 
{ 


  {
//#line  45
  state3 = (enum state )7;
//#line  45
  state2 = state3;
//#line  46
  myunion.field = 15;
//#line  47
  return (0);
}
}
