/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "attr8.c"
 __attribute__((__noreturn__)) void foo(char *x ) ;
//#line  2
 __attribute__((__noreturn__)) void foo(char *x ) ;
//#line  2 "attr8.c"
void foo(char *x ) 
{ 


  {
//#line  3
  while (1) {

  }
}
}
//#line  6 "attr8.c"
int main(int argc , char **argv ) 
{ 


  {
//#line  7
  foo((char *)0);
//#line  8
  return (0);
}
}
