/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "attr12.c"
extern int strnvis(char * , char const   * , unsigned int  , int  ) ;
//#line  5 "attr12.c"
int main(void) 
{ 


  {
//#line  6
  strnvis((char *)0, (char const   *)0, 0U, 0);
//#line  7
  return (0);
}
}
