/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  2 "attr10.c"
#pragma warning(foo:2)
//#line  5 "attr10.c"
int array[32]  ;
//#line  7 "attr10.c"
int foo  ;
//#line  7 "attr10.c"
int bar  ;
//#line  7 "attr10.c"
int c  ;
//#line  9 "attr10.c"
int * __attribute__((__array__)) p1  ;
//#line  11 "attr10.c"
int * __attribute__((__test__(foo ? bar : c))) p4  ;
//#line  15 "attr10.c"
int * __attribute__((__test__(foo ? 0 : 1))) p5  ;
//#line  17 "attr10.c"
int * __attribute__((__test__(foo ? bar : 1))) p6  ;
//#line  20 "attr10.c"
int * __attribute__((__test__(& array))) p2  ;
//#line  21 "attr10.c"
int * __attribute__((__test__(& array[0]))) p3  ;
//#line  24 "attr10.c"
int main(void) 
{ 


  {
//#line  25
  return (0);
}
}
