/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  13 "bitfield3.c"
struct only_bitfields {
   int bf1 : 1 ;
   int bf2 : 4 ;
};
//#line  18 "bitfield3.c"
struct nested1 {
   int i1 ;
   int *p1 ;
   struct only_bitfields b1 ;
   int *p2 ;
};
//#line  38 "bitfield3.c"
struct start_bitfields {
   int bf2 : 4 ;
   int bf3 : 5 ;
   int *ptr2 ;
};
//#line  44 "bitfield3.c"
struct nested2 {
   int *ptr1 ;
   struct start_bitfields b2 ;
};
//#line  62 "bitfield3.c"
struct end_bitfields {
   int *ptr1 ;
   int bf2 : 4 ;
   int bf3 : 5 ;
};
//#line  67 "bitfield3.c"
struct nested3 {
   struct end_bitfields b3 ;
   int *ptr2 ;
};
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  8 "bitfield3.c"
int anint1  =    123;
//#line  8 "bitfield3.c"
int anint2  =    456;
//#line  10 "bitfield3.c"
int main(void) 
{ 
  struct nested1 x1 ;
  struct nested2 x2 ;
  struct nested3 x3 ;

  {
//#line  25
  x1.p1 = & anint1;
//#line  25
  x1.p2 = & anint2;
//#line  26
  x1.i1 = 5;
//#line  26
  if (x1.i1 != 5) {
//#line  26
    printf("Error %d\n", 1);
//#line  26
    exit(1);
  }
//#line  28
  x1.b1.bf2 = 4;
//#line  28
  if (x1.b1.bf2 != 4) {
//#line  28
    printf("Error %d\n", 2);
//#line  28
    exit(2);
  }
//#line  31
  if (*(x1.p1) != anint1) {
//#line  31
    printf("Error %d\n", 3);
//#line  31
    exit(3);
  }
//#line  33
  if (*(x1.p2) != anint2) {
//#line  33
    printf("Error %d\n", 4);
//#line  33
    exit(4);
  }
//#line  49
  x2.ptr1 = & anint1;
//#line  49
  x2.b2.ptr2 = & anint2;
//#line  50
  x2.b2.bf3 = 5;
//#line  50
  if (x2.b2.bf3 != 5) {
//#line  50
    printf("Error %d\n", 11);
//#line  50
    exit(11);
  }
//#line  52
  x2.b2.bf2 = 4;
//#line  52
  if (x2.b2.bf2 != 4) {
//#line  52
    printf("Error %d\n", 12);
//#line  52
    exit(12);
  }
//#line  55
  if (*(x2.ptr1) != anint1) {
//#line  55
    printf("Error %d\n", 13);
//#line  55
    exit(13);
  }
//#line  57
  if (*(x2.b2.ptr2) != anint2) {
//#line  57
    printf("Error %d\n", 14);
//#line  57
    exit(14);
  }
//#line  72
  x3.b3.ptr1 = & anint1;
//#line  72
  x3.ptr2 = & anint2;
//#line  73
  x3.b3.bf3 = 5;
//#line  73
  if (x3.b3.bf3 != 5) {
//#line  73
    printf("Error %d\n", 21);
//#line  73
    exit(21);
  }
//#line  75
  x3.b3.bf2 = 4;
//#line  75
  if (x3.b3.bf2 != 4) {
//#line  75
    printf("Error %d\n", 22);
//#line  75
    exit(22);
  }
//#line  78
  if (*(x3.b3.ptr1) != anint1) {
//#line  78
    printf("Error %d\n", 23);
//#line  78
    exit(23);
  }
//#line  80
  if (*(x3.ptr2) != anint2) {
//#line  80
    printf("Error %d\n", 24);
//#line  80
    exit(24);
  }
//#line  86
  printf("Success\n");
//#line  86
  exit(0);
}
}
