/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "bitfield2.c"
struct __anonstruct_uri_components_914949163 {
   char x ;
   unsigned int dns_resolved : 1 ;
};
//#line  3 "bitfield2.c"
typedef struct __anonstruct_uri_components_914949163 uri_components;
//#line  9 "bitfield2.c"
struct __anonstruct_test_352126815 {
   char x ;
};
//#line  9 "bitfield2.c"
typedef struct __anonstruct_test_352126815 test;
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  12 "bitfield2.c"
int main(void) 
{ 


  {
//#line  13
  if (sizeof(uri_components ) == sizeof(test )) {
//#line  14
    printf("Error %d\n", 1);
//#line  14
    exit(1);
  }
//#line  16
  printf("Success\n");
//#line  16
  exit(0);
}
}
