/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  4 "blockattr2.c"
int f(int x ) 
{ 


  {
  {
//#line  10
  if (x == 1) {
//#line  10
    goto case_1;
  }
//#line  6
  goto switch_break;
  {  /* __blockattribute__(__x__)*/ 
  case_1: /* CIL Label */ 
//#line  11
  return (2);
  }
  switch_break: /* CIL Label */ ;
  }
//#line  13
  return (0);
}
}
//#line  16 "blockattr2.c"
int main(void) 
{ 
  int tmp ;

  {
  {
//#line  18
  tmp = f(1);
  }
//#line  18
  if (tmp != 2) {
    {
//#line  18
    printf("Error %d\n", 1);
//#line  18
    exit(1);
    }
  }
  {
//#line  19
  printf("Success\n");
//#line  19
  exit(0);
  }
}
}
