/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "bool.c"
int main(void) 
{ 
  _Bool x ;
  int z ;
  double zz ;

  {
//#line  5
  x = (_Bool)1;
//#line  6
  z = 2;
//#line  7
  zz = 0.0;
//#line  9
  if (! x) {
//#line  9
    printf("Error %d\n", 1);
//#line  9
    exit(1);
  }
//#line  11
  x = (_Bool )z;
//#line  12
  if (! x) {
//#line  12
    printf("Error %d\n", 2);
//#line  12
    exit(2);
  }
//#line  13
  if ((int )x != 1) {
//#line  13
    printf("Error %d\n", 3);
//#line  13
    exit(3);
  }
//#line  15
  x = (_Bool )zz;
//#line  16
  if (x) {
//#line  16
    printf("Error %d\n", 4);
//#line  16
    exit(4);
  }
//#line  19
  if ((int )((_Bool )(1.0 + (double )2)) != 1) {
//#line  19
    printf("Error %d\n", 6);
//#line  19
    exit(6);
  }
//#line  21
  printf("Success\n");
//#line  21
  exit(0);
}
}
