/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  5 "builtin3.c"
int main(void) 
{ 
  int x ;
  int b ;

  {
//#line  7
  x = 0;
//#line  8
  b = 0;
//#line  14
  b = 0;
//#line  19
  x ++;
//#line  21
  switch (8) {
  case 8: 
//#line  23
  break;
  default: 
//#line  25
  printf("Error %d\n", 2);
//#line  25
  exit(2);
  }
//#line  28
  if (x != 1) {
//#line  28
    printf("Error %d\n", 1);
//#line  28
    exit(1);
  }
//#line  37
  printf("Success\n");
//#line  37
  exit(0);
}
}
