/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

/* compiler builtin: 
   double __builtin_fabs(double  ) ;  */
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "builtin.c"
int main(void) 
{ 
  double d ;
  double tmp ;

  {
//#line  4
  tmp = __builtin_fabs(- 2.0);
//#line  4
  d = tmp;
//#line  5
  printf("Result is %lf\n", d);
//#line  6
  printf("Success\n");
//#line  6
  exit(0);
}
}
