/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  5 "builtin5.c"
struct __anonstruct_zz_109580352 {
   int z ;
};
//#line  2 "builtin5.c"
int a  ;
//#line  2 "builtin5.c"
int b  ;
//#line  2 "builtin5.c"
int c  ;
//#line  3 "builtin5.c"
int *chrdevs[3]  = {      & a,      & b,      & c};
//#line  5 "builtin5.c"
struct __anonstruct_zz_109580352 zz  ;
//#line  7 "builtin5.c"
void f(void) 
{ 
  int i ;

  {
//#line  11
  i = (int )((sizeof(chrdevs) / sizeof(chrdevs[0]) + (sizeof(char [1]) - 1UL)) - 1UL);
//#line  11
  while (i > 0) {
//#line  14
    if ((unsigned long )chrdevs[i] == (unsigned long )((void *)0)) {
//#line  15
      break;
    }
//#line  11
    i --;
  }
//#line  17
  return;
}
}
