/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  5 "builtin_choose_expr.c"
int main(void) 
{ 
  char c ;
  int i ;
  int *p ;
  double d ;
  int tmp___0 ;

  {
//#line  6
  c = (char)0;
//#line  7
  i = 1;
//#line  8
  if (sizeof(c) != sizeof(char )) {
//#line  8
    printf("Error %d\n", 1);
//#line  8
    exit(1);
  }
//#line  9
  if (sizeof(i) != sizeof(int )) {
//#line  9
    printf("Error %d\n", 2);
//#line  9
    exit(2);
  }
//#line  11
  p = & i;
//#line  12
  d = 2.0;
//#line  15
  c = c;
//#line  16
  if (i != 1) {
//#line  16
    printf("Error %d\n", 3);
//#line  16
    exit(3);
  }
//#line  19
  tmp___0 = i;
//#line  19
  i ++;
//#line  19
  c = (char )tmp___0;
//#line  20
  if (i != 2) {
//#line  20
    printf("Error %d\n", 4);
//#line  20
    exit(4);
  }
//#line  22
  return (0);
}
}
