/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "builtin2.c"
int f(__builtin_va_list vl ) ;
//#line  2 "builtin2.c"
int f(__builtin_va_list vl ) 
{ 


  {
//#line  3
  return (0);
}
}
//#line  6 "builtin2.c"
int main(void) 
{ 
  __builtin_va_list vl ;
  int tmp ;

  {
//#line  8
  tmp = f(vl);
//#line  8
  return (tmp);
}
}
