/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  4 "call2.c"
int any_int(void) 
{ 


  {
//#line  5
  return (3);
}
}
//#line  8 "call2.c"
void main(void) 
{ 
  int tmp ;
  unsigned int G ;

  {
//#line  9
  tmp = -1;
//#line  13
  tmp = any_int();
//#line  14
  G = (unsigned int )tmp;
//#line  15
  tmp -= 3;
//#line  16
  if (tmp != 0) {
//#line  16
    printf("Error %d\n", 1);
//#line  16
    exit(1);
  }
//#line  17
  printf("Success\n");
//#line  17
  exit(0);
}
}
