/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "caserange.c"
int foo(int x ) 
{ 
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
//#line  5
  switch (x) {
  case 6: 
//#line  6
  x ++;
  case 7: 
  case 8: 
  case 9: 
  case 10: 
//#line  7
  tmp = foo(x + 2);
//#line  7
  return (tmp);
  case 65: 
  case 66: 
  case 67: 
  case 68: 
  case 69: 
//#line  8
  tmp___0 = foo(x + 8);
//#line  8
  return (tmp___0);
  case 70: 
  case 71: 
  case 72: 
  case 73: 
  case 74: 
  case 75: 
  case 76: 
  case 77: 
  case 78: 
  case 79: 
  case 80: 
  case 81: 
  case 82: 
  case 83: 
  case 84: 
  case 85: 
  case 86: 
  case 87: 
  case 88: 
  case 89: 
  case 90: 
//#line  9
  return (x);
  default: 
//#line  11
  tmp___1 = foo(x + 5);
//#line  11
  return (tmp___1);
  }
}
}
//#line  15 "caserange.c"
int main(void) 
{ 
  int tmp ;

  {
//#line  17
  tmp = foo(6);
//#line  17
  return (tmp - 74);
}
}
