/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  4 "case_then_default_in_switch.c"
int main(void) 
{ 


  {
  {
//#line  9
  if (1 == 1) {
//#line  9
    goto case_1;
  }
//#line  7
  goto switch_default;
  switch_default: /* CIL Label */ 
//#line  8
  goto switch_break;
  case_1: /* CIL Label */ 
  {
//#line  10
  printf("Success\n");
//#line  10
  exit(0);
  }
  switch_break: /* CIL Label */ ;
  }
  {
//#line  12
  printf("Error %d\n", 0);
//#line  12
  exit(0);
  }
}
}
