/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
//#line  362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  466 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
//#line  4 "castincr.c"
int main(void) 
{ 
  char *p ;
  int i ;
  void *tmp ;
  int *tmp___0 ;
  int *tmp___1 ;

  {
//#line  8
  tmp = malloc(2UL * sizeof(int ));
//#line  8
  p = (char *)tmp;
//#line  9
  *((int *)p) = 1;
//#line  10
  *((int *)p + 1) = 2;
//#line  12
  tmp___0 = (int *)p;
//#line  12
  p = (char *)((int *)p + 1);
//#line  12
  i = *tmp___0;
//#line  13
  printf((char const   */* __restrict  */)"%d\n", i);
//#line  14
  tmp___1 = (int *)p;
//#line  14
  p = (char *)((int *)p + 1);
//#line  14
  i = *tmp___1;
//#line  15
  printf((char const   */* __restrict  */)"%d\n", i);
//#line  17
  return (0);
}
}
