/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "cast2.c"
extern void free(void * ) ;
//#line  3 "cast2.c"
void foo(void) 
{ 


  {
//#line  5
  free((void *)0);
//#line  6
  return;
}
}
