/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "castcall.c"
short S  ;
//#line  3 "castcall.c"
int f(int x , int y ) 
{ 


  {
//#line  5
  return (x + y);
}
}
//#line  8 "castcall.c"
int main(void) 
{ 
  short tmp ;
  int tmp___0 ;

  {
//#line  9
  tmp = S;
//#line  9
  S = (short )((int )S + 1);
//#line  9
  tmp___0 = f(1, (int )tmp);
//#line  9
  return (tmp___0);
}
}
