/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  5 "cast8.c"
int main(void) 
{ 
  int base ;
  unsigned long max_over_base ;
  unsigned long correct ;

  {
//#line  6
  base = 5;
//#line  7
  max_over_base = 0xffffffffffffffffUL / (unsigned long )base;
//#line  10
  correct = 0xffffffffffffffffUL / (unsigned long )base;
//#line  13
  printf("Result is %ld. Correct=%ld\n", max_over_base, correct);
//#line  14
  if (max_over_base != correct) {
//#line  14
    printf("Error %d\n", 1);
//#line  14
    exit(1);
  }
//#line  16
  printf("Success\n");
//#line  16
  exit(0);
}
}
