/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "castunion.c"
union X {
   int a ;
   short b ;
};
//#line  6 "castunion.c"
int main(void) 
{ 
  union X u ;
  union X v ;
  union X __constr_expr_0 ;

  {
//#line  9
  __constr_expr_0 = u;
//#line  9
  v = __constr_expr_0;
//#line  10
  return (0);
}
}
