/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "cast4.c"
struct str {
   int i1 ;
   int i2 ;
};
//#line  3 "cast4.c"
union un {
   int i ;
   long long l ;
   struct str s ;
};
//#line  3 "cast4.c"
typedef union un un;
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  11 "cast4.c"
int f(union un x ) 
{ 


  {
//#line  12
  return (x.s.i1);
}
}
//#line  15 "cast4.c"
un glob  =    {6};
//#line  17 "cast4.c"
int main(void) 
{ 
  un x ;
  struct str s ;
  un y ;
  un __constr_expr_0 ;
  int tmp ;

  {
//#line  18
  x.l = 5LL;
//#line  19
  if (x.l != 5LL) {
//#line  19
    printf("Error %d\n", 1);
//#line  19
    exit(1);
  }
//#line  20
  if (x.i != 5) {
//#line  20
    printf("Error %d\n", 2);
//#line  20
    exit(2);
  }
//#line  23
  s.i1 = 1;
//#line  23
  s.i2 = 2;
//#line  24
  y.s = s;
//#line  25
  if (y.s.i1 != 1) {
//#line  25
    printf("Error %d\n", 3);
//#line  25
    exit(3);
  } else
//#line  25
  if (y.s.i2 != 2) {
//#line  25
    printf("Error %d\n", 3);
//#line  25
    exit(3);
  }
//#line  27
  __constr_expr_0.s = s;
//#line  27
  tmp = f(__constr_expr_0);
//#line  27
  if (tmp != 1) {
//#line  27
    printf("Error %d\n", 4);
//#line  27
    exit(4);
  }
//#line  30
  if (glob.i != 6) {
//#line  30
    printf("Error %d\n", 5);
//#line  30
    exit(5);
  }
//#line  32
  printf("Success\n");
//#line  32
  exit(0);
}
}
