/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 9 "combine_sbumpB_3.c"
typedef int int_type;
#line 10 "combine_sbumpB_3.c"
typedef int_type int_type1;
#line 11 "combine_sbumpB_3.c"
struct str1 {
   int *_M_get ;
};
#line 33 "combine_sbumpB_3.c"
__inline static int_type1 sbump___0(struct str1 *this ) 
{ 
  int tmp___3 ;
  char const   *tmp___4 ;
  int tmp___5 ;

  {
#line 39
  tmp___5 = 5;
#line 40
  if (tmp___5 > 0) {
#line 42
    tmp___4 = (char const   *)0;
  }
#line 44
  return (tmp___3);
}
}
#line 48 "combine_sbumpB_3.c"
int main(int argc , char *argv ) 
{ 


  {
#line 50
  if (argc > 100) {
#line 51
    sbump___0((struct str1 *)0);
  }
#line 53
  return (0);
}
}
