/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 11 "combine_allocate_2.c"
__inline static void *allocate___0(unsigned int __11367_34___n ) ;
#line 14 "combine_allocate_2.c"
__inline static void *allocate___0(unsigned int __11367_34___n ) 
{ 


  {
#line 16
  return ((void *)0);
}
}
#line 21 "combine_allocate_2.c"
int main(void) 
{ 


  {
#line 22
  allocate___0(0U);
#line 23
  return (0);
}
}
