/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 1 "combine10_2.c"
struct foo ;
#line 1 "combine10_2.c"
typedef struct foo PSFOO;
#line 2 "combine10_2.c"
struct foo {
   struct foo *left ;
   PSFOO *right ;
   int x ;
};
#line 2 "combine10_2.c"
struct foo g2  ;
