/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 2 "combineenum3_1.c"
enum e1 {
    FIRST = 0,
    SECOND = 1
} ;
#line 2 "combineenum3_1.c"
enum e1 x1  ;
#line 7 "combineenum3_1.c"
int main(void) 
{ 


  {
#line 8
  return ((int )x1);
}
}
