/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 6 "combine_init_1.c"
struct logger {
   char *s ;
   int i ;
};
#line 11 "combine_init_1.c"
static struct logger __constr_expr_0  =    {(char *)"redSecondaryCPMStatusChange", 2013};
#line 11 "combine_init_1.c"
static struct logger __constr_expr_1  =    {(char *)"redRestoreSuccess", 2014};
#line 11 "combine_init_1.c"
static struct logger __constr_expr_2  =    {(char *)"redRestoreFail", 2015};
#line 11 "combine_init_1.c"
struct logger *event_list_CHASSIS[4]  = {      & __constr_expr_0,      & __constr_expr_1,      & __constr_expr_2,      (struct logger *)0};
#line 19 "combine_init_1.c"
int main(void) 
{ 


  {
#line 20
  return (0);
}
}
