/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 1 "combineinline2_2.c"
static int g  ;
#line 2 "combineinline2_2.c"
__inline int foo(int x ) 
{ 


  {
#line 2
  return (g);
}
}
#line 5 "combineinline2_2.c"
int getfoo2(void) 
{ 


  {
#line 5
  return ((int )(& foo));
}
}
