/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 13 "combinelibrik_2.c"
extern int chunk1(char * ) ;
#line 15 "combinelibrik_2.c"
static char fake[1]  ;
#line 16 "combinelibrik_2.c"
static char *chunk  =    fake;
#line 18 "combinelibrik_2.c"
int main(void) 
{ 
  int tmp ;

  {
#line 20
  tmp = chunk1(chunk);
#line 20
  return (tmp - (int )fake[0]);
}
}
