/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 1 "combine15_2.c"
struct s2 {
   int x ;
};
#line 5 "combine15_2.c"
struct d2 {
   double x ;
};
#line 1 "combine15_2.c"
struct s2 x1  ;
#line 1 "combine15_2.c"
struct s2 x2  ;
#line 5 "combine15_2.c"
struct d2 y2  ;
#line 5 "combine15_2.c"
struct d2 y1  ;
