/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 1 "combineenum2_2.c"
enum __anonenum_x2_658273763 {
    SECOND = 0,
    FIRST = 1
} ;
#line 1 "combineenum2_2.c"
enum __anonenum_x2_658273763 x2  ;
#line 6 "combineenum2_2.c"
int foo(void) 
{ 


  {
#line 7
  return ((int )x2);
}
}
