/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 6 "combine21_2.c"
extern void testit(int flag ) ;
#line 8 "combine21_2.c"
void otest(int flag ) 
{ 


  {
#line 10
  testit(flag);
#line 11
  return;
}
}
