/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 4 "combinealias_2.c"
extern int ( /* missing proto */  foo)() ;
#line 3 "combinealias_2.c"
int main(void) 
{ 


  {
#line 4
  foo(42);
#line 5
  return (0);
}
}
