/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 2 "combineinline4_2.c"
__inline int bar(int x ) ;
#line 5 "combineinline4_2.c"
int getfoo2(void) 
{ 


  {
#line 6
  return ((int )(& bar));
}
}
#line 10 "combineinline4_2.c"
__inline int bar(int x ) 
{ 


  {
#line 10
  return (x);
}
}
