/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 1 "combine3_1.c"
struct foo ;
#line 1 "combine3_1.c"
typedef struct foo *PFOO;
#line 3 "combine3_1.c"
struct foo {
   int x ;
   PFOO y ;
};
#line 3 "combine3_1.c"
typedef struct foo *PTR;
#line 8 "combine3_1.c"
PTR g1  ;
