/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 7 "combine_samefn_1.c"
/* #pragma ccuredpoly("some_poly_fn") */
#line 10 "combine_samefn_1.c"
int foo(int xxx ) 
{ 
  int yyy ;
  int z ;

  {
#line 12
  yyy = xxx + 3;
#line 13
  z = yyy + xxx;
#line 14
  return (z + xxx);
}
}
#line 18 "combine_samefn_1.c"
int myglobal     =    3;
#line 22 "combine_samefn_1.c"
__inline static int func(void) 
{ 


  {
#line 24
  return (3);
}
}
#line 27
__inline static int func___0(void) ;
#line 28 "combine_samefn_1.c"
__inline static int func___0(void) 
{ 


  {
#line 30
  return (3);
}
}
#line 35
extern int otherFunc() ;
#line 38 "combine_samefn_1.c"
int main(void) 
{ 
  int ret ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;

  {
#line 40
  tmp = func();
#line 40
  tmp___0 = func___0();
#line 40
  ret = (tmp + tmp___0) - 6;
#line 41
  tmp___1 = foo(5);
#line 41
  ret += ((tmp___1 - 18) + myglobal) - 3;
#line 42
  tmp___2 = otherFunc();
#line 42
  ret += tmp___2 - 3;
#line 43
  return (ret);
}
}
