/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 3 "testharness.h"
extern int printf(char const   *format  , ...) ;
#line 12
extern void exit(int  ) ;
#line 3 "combine2_3.c"
int bar  ;
#line 6
extern int ( /* missing proto */  f1)() ;
#line 7
extern int ( /* missing proto */  f2)() ;
#line 5 "combine2_3.c"
int main(void) 
{ 


  {
#line 6
  f1();
#line 7
  f2();
#line 9
  printf("Success\n");
#line 9
  exit(0);
}
}
