/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 1 "combine_theFunc_3.c"
typedef int ptrdiff_t;
#line 2 "combine_theFunc_3.c"
typedef int FILE;
#line 8
__inline static ptrdiff_t theFunc___0(FILE const   *__20468_44___f ) ;
#line 25 "combine_theFunc_3.c"
__inline static ptrdiff_t theFunc___0(FILE const   *__20468_44___f ) 
{ 


  {
#line 27
  return (0);
}
}
#line 30 "combine_theFunc_3.c"
int main(void) 
{ 


  {
#line 32
  theFunc___0((FILE const   *)0);
#line 33
  return (0);
}
}
