/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 1 "combine18_2.c"
enum e2 {
    ITEM1 = 5,
    ITEM2 = 6
} ;
#line 1 "combine18_2.c"
enum e2 x2  ;
#line 6 "combine18_2.c"
int getitem5(void) 
{ 


  {
#line 7
  return (5);
}
}
