/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 1 "combine13_2.c"
struct foo ;
#line 1 "combine13_2.c"
typedef struct foo PSFOO;
#line 2 "combine13_2.c"
struct foo {
   struct foo *left ;
   PSFOO *right ;
   int x ;
};
#line 2
extern struct foo g ;
#line 3 "testharness.h"
extern int printf(char const   *format  , ...) ;
#line 12
extern void exit(int  ) ;
#line 10 "combine13_2.c"
int main(void) 
{ 


  {
#line 11
  printf("Address is %x\n", & g);
#line 12
  printf("Success\n");
#line 12
  exit(0);
}
}
