/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 4 "combine22_2.c"
typedef int MYINT;
#line 6 "combine22_2.c"
struct empty {
   MYINT i ;
};
#line 6 "combine22_2.c"
struct empty glob  ;
#line 10 "combine22_2.c"
struct empty *ptr_empty  ;
#line 12 "combine22_2.c"
int main(void) 
{ 


  {
#line 13
  return (glob.i);
}
}
