/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 9 "combine_syserr_2.c"
int __T_9xSysError ;
#line 11 "combine_syserr_2.c"
int *glob  =    & __T_9xSysError;
#line 13 "combine_syserr_2.c"
int __T_9xSysError  =    0;
#line 25 "combine_syserr_2.c"
int main(void) 
{ 


  {
#line 27
  return (0);
}
}
