/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 4 "combine_samefn_2.c"
int foo(int x ) 
{ 
  int y ;
  int z ;

  {
#line 6
  y = x + 3;
#line 7
  z = y + x;
#line 8
  return (z + x);
}
}
#line 13 "combine_samefn_2.c"
int myglobal  =    3;
#line 17
__inline static int func(void) ;
#line 19 "combine_samefn_2.c"
__inline static int func(void) 
{ 


  {
#line 21
  return (3);
}
}
#line 24 "combine_samefn_2.c"
int otherFunc(void) 
{ 
  int tmp ;

  {
#line 26
  tmp = func();
#line 26
  return (tmp);
}
}
