/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 4 "combine_node_alloc_2.c"
struct node {
   struct node *link ;
};
#line 7 "combine_node_alloc_2.c"
struct node *list[1]  = {      (struct node *)0};
#line 11 "combine_node_alloc_2.c"
int main(void) 
{ 


  {
#line 13
  return ((int )list[0]);
}
}
