/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 2 "combineenum1_1.c"
enum __anonenum_x1_134510117 {
    INT = 0,
    FLOAT = 1
} ;
#line 2 "combineenum1_1.c"
enum __anonenum_x1_134510117 x1  ;
#line 8 "combineenum1_1.c"
void foo(void) 
{ 


  {
#line 9
  x1 = (enum __anonenum_x1_134510117 )1;
#line 10
  return;
}
}
