/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 4 "combine22_1.c"
struct empty ;
#line 4 "combine22_1.c"
struct empty *ptr_empty  ;
#line 6 "combine22_1.c"
int other(void) 
{ 


  {
#line 7
  return ((int )sizeof(struct empty ));
}
}
