/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 1 "combine9_2.c"
typedef short INT;
#line 3 "combine9_2.c"
struct __anonstruct_g_15862768 {
   INT i ;
   int x ;
};
#line 3 "combine9_2.c"
struct __anonstruct_g_15862768 g  ;
