/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 3 "testharness.h"
extern int printf(char const   *format  , ...) ;
#line 12
extern void exit(int  ) ;
#line 4 "combineinline2_1.c"
static int g  ;
#line 5 "combineinline2_1.c"
__inline static int foo(int x ) 
{ 


  {
#line 5
  return (g);
}
}
#line 7
extern int getfoo2() ;
#line 10 "combineinline2_1.c"
int main(void) 
{ 
  int tmp ;

  {
#line 11
  tmp = getfoo2();
#line 11
  if (tmp == (int )(& foo)) {
#line 11
    printf("Error %d\n", 1);
#line 11
    exit(1);
  }
#line 12
  printf("Success\n");
#line 12
  exit(0);
}
}
