/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 1 "combine_copyptrs_2.c"
struct true_type {

};
#line 20
__inline static char *copyptrs(char *__5338_43___first , char *__5338_63___last ,
                               char *__5338_83___result , struct true_type  const  *_6 ) ;
#line 43 "combine_copyptrs_2.c"
__inline static char *copyptrs(char *__5338_43___first , char *__5338_63___last ,
                               char *__5338_83___result , struct true_type  const  *_6 ) 
{ 


  {
#line 47
  return ((char *)0);
}
}
#line 81 "combine_copyptrs_2.c"
int main(void) 
{ 


  {
#line 83
  copyptrs((char *)0, (char *)0, (char *)0, (struct true_type  const  *)0);
#line 84
  return (0);
}
}
