/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 1 "combine11_2.c"
struct foo ;
#line 1
struct bar ;
#line 1 "combine11_2.c"
struct list {
   struct list *next ;
   struct foo *f ;
   struct bar *b ;
};
#line 7
enum __anonenum_e_653952911 {
    A = 0,
    B = 1,
    C = 2
} ;
#line 7 "combine11_2.c"
struct bar {
   enum __anonenum_e_653952911 e ;
};
#line 1
extern struct list g ;
#line 11 "combine11_2.c"
void *f2(void) 
{ 


  {
#line 12
  return ((void *)(& (g.b)->e));
}
}
#line 17
extern int ( /* missing proto */  f1)() ;
#line 16 "combine11_2.c"
int main(void) 
{ 
  void *v1 ;
  int tmp ;
  void *v2 ;
  void *tmp___0 ;

  {
#line 17
  tmp = f1();
#line 17
  v1 = (void *)tmp;
#line 18
  tmp___0 = f2();
#line 18
  v2 = tmp___0;
#line 19
  return (0);
}
}
