/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 3 "combine12_1.c"
struct foo ;
#line 3 "combine12_1.c"
struct bar {
   int x ;
   struct foo *next ;
};
#line 8 "combine12_1.c"
struct foo {
   struct bar b ;
};
#line 8 "combine12_1.c"
struct foo g  ;
#line 12 "combine12_1.c"
int main(void) 
{ 


  {
#line 13
  return (0);
}
}
