/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 3 "combine8_1.c"
struct googoo ;
#line 3 "combine8_1.c"
struct foo {
   int x ;
   struct googoo *next ;
};
#line 9 "combine8_1.c"
struct googoo {
   double d ;
};
#line 3 "testharness.h"
extern int printf(char const   *format  , ...) ;
#line 12
extern void exit(int  ) ;
#line 3 "combine8_1.c"
struct foo *g1  ;
#line 14 "combine8_1.c"
int main(void) 
{ 


  {
#line 15
  printf("Success\n");
#line 15
  exit(0);
}
}
