/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 1 "combine17_2.c"
struct __anonstruct_x_109580352 {
   int f ;
};
#line 1 "combine17_2.c"
struct __anonstruct_x_109580352 x  ;
#line 3 "testharness.h"
extern int printf(char const   *format  , ...) ;
#line 12
extern void exit(int  ) ;
#line 7 "combine17_2.c"
extern int ( /* missing proto */  read)() ;
#line 5 "combine17_2.c"
int main(void) 
{ 
  int tmp ;

  {
#line 6
  x.f = 5;
#line 7
  tmp = read();
#line 7
  if (tmp != 5) {
#line 7
    printf("Error %d\n", 1);
#line 7
    exit(1);
  }
#line 9
  printf("Success\n");
#line 9
  exit(0);
}
}
