/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 4 "combine10_1.c"
struct foo {
   struct foo *left ;
   struct foo *right ;
   int x ;
};
#line 4 "combine10_1.c"
struct foo g1  ;
