/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 2 "combine11_1.c"
struct foo ;
#line 2
struct bar ;
#line 2 "combine11_1.c"
struct list {
   struct list *next ;
   struct foo *f ;
   struct bar *b ;
};
#line 8 "combine11_1.c"
struct foo {
   double d ;
};
#line 2 "combine11_1.c"
struct list g  ;
#line 13 "combine11_1.c"
void *f1(void) 
{ 


  {
#line 14
  return ((void *)(& (g.f)->d));
}
}
