/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 2 "combine20_2.c"
struct stralloc {
   char *s ;
   unsigned int len ;
   unsigned int a ;
};
#line 8 "combine20_2.c"
static struct stralloc tmp  ;
#line 11 "combine20_2.c"
int main(void) 
{ 
  int tmp___0 ;
  char *path ;

  {
#line 12
  tmp___0 = 5;
#line 14
  path = tmp.s;
#line 15
  return (0);
}
}
