/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 1 "combine14_2.c"
extern int protoname1 ;
#line 3 "combine14_2.c"
int protoname2  =    5;
#line 5
extern void bar(int protoname2 ) ;
#line 7 "combine14_2.c"
void foo(int myname ) 
{ 


  {
#line 8
  protoname1 = myname;
#line 10
  bar(0);
#line 11
  return;
}
}
