/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 2 "combineinline3_2.c"
__inline int bar(int x ) ;
#line 4 "combineinline3_2.c"
__inline int bar(int x ) 
{ 


  {
#line 4
  return (x);
}
}
#line 7 "combineinline3_2.c"
int getfoo2(void) 
{ 


  {
#line 8
  return ((int )(& bar));
}
}
