/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 5 "combine15_1.c"
struct s1 {
   int x ;
};
#line 8 "combine15_1.c"
struct d1 {
   double x ;
};
#line 13 "combine15_1.c"
struct use {
   struct s1 f1 ;
   struct d1 f2 ;
};
#line 18 "combine15_1.c"
struct s11 {
   int x ;
};
#line 21 "combine15_1.c"
struct d11 {
   double x ;
};
#line 26 "combine15_1.c"
struct use2 {
   struct s11 f2 ;
   struct d11 f3 ;
};
#line 5
extern struct s1 x1 ;
#line 8
extern struct d1 y1 ;
#line 13 "combine15_1.c"
struct use ext1  ;
#line 18
extern struct s11 x2 ;
#line 21
extern struct d11 y2 ;
#line 26 "combine15_1.c"
struct use2 ext2  ;
#line 3 "testharness.h"
extern int printf(char const   *format  , ...) ;
#line 33 "combine15_1.c"
int main(void) 
{ 


  {
#line 34
  printf("Address of x1=%x and x2=%x\n", & x1, & x2);
#line 36
  printf("Address of y1=%x and y2=%x\n", & y1, & y2);
#line 38
  return (0);
}
}
