/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 1 "combineinline1_2.c"
__inline int foo(int x ) 
{ 


  {
#line 2
  return (x);
}
}
#line 6 "combineinline1_2.c"
int getfoo2(void) 
{ 


  {
#line 7
  return ((int )(& foo));
}
}
