/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 1 "combine12_2.c"
struct foo ;
#line 1 "combine12_2.c"
struct __anonstruct_c_360559640 {
   int x ;
   struct foo *next ;
};
#line 1 "combine12_2.c"
struct bar {
   struct __anonstruct_c_360559640 c ;
};
#line 8 "combine12_2.c"
struct __anonstruct_b_528287478 {
   int x ;
   struct bar *next ;
};
#line 8 "combine12_2.c"
struct baz {
   struct __anonstruct_b_528287478 b ;
};
#line 8 "combine12_2.c"
struct baz g  ;
