/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 4 "combine17_1.c"
struct __anonstruct_x_109580352 {
   int f ;
};
#line 4
extern struct __anonstruct_x_109580352  const  x ;
#line 7 "combine17_1.c"
int read(void) 
{ 


  {
#line 8
  return ((int )x.f);
}
}
