/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 1 "combine_sbump_2.c"
struct someStruct ;
#line 9
__inline static int sbump___0(struct someStruct *this ) ;
#line 10 "combine_sbump_2.c"
__inline static int sbump___0(struct someStruct *this ) 
{ 


  {
#line 12
  return (3);
}
}
#line 15 "combine_sbump_2.c"
int foo(void) 
{ 


  {
#line 17
  sbump___0((struct someStruct *)0);
#line 18
  return (0);
}
}
#line 20 "combine_sbump_2.c"
int main(void) 
{ 


  {
#line 22
  foo();
#line 23
  return (0);
}
}
