/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 3 "combinealias_1.c"
void __foo(int x ) 
{ 


  {
#line 4
  printf((char const   */* __restrict  */)"Hello, world!  %d\n", x);
#line 5
  return;
}
}
#line 7 "combinealias_1.c"
void foo(int x ) 
{ 


  {
#line 7
  __foo(x);
#line 7
  return;
}
}
