/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 2 "combine1_2.c"
struct str1 {
   int random ;
};
#line 6 "combine1_2.c"
static int array[10]  ;
#line 8 "combine1_2.c"
int c2(void) 
{ 


  {
#line 9
  return ((int )(sizeof(array) + sizeof(struct str1 )));
}
}
