/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 4 "combineinline6_1.c"
__inline static int foo2(int x ) ;
#line 7 "combineinline6_1.c"
int main(void) 
{ 
  void *p ;
  int tmp ;

  {
#line 8
  p = (void *)(& foo2);
#line 9
  tmp = foo2(5);
#line 9
  return (tmp);
}
}
#line 18 "combineinline6_1.c"
__inline static int foo2(int x ) 
{ 


  {
#line 19
  return (x - 5);
}
}
