/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 1 "combineenum1_2.c"
enum __anonenum_x1_134510117 {
    INT = 0,
    FLOAT = 3
} ;
#line 1
extern enum __anonenum_x1_134510117 x1 ;
#line 3 "testharness.h"
extern int printf(char const   *format  , ...) ;
#line 12
extern void exit(int  ) ;
#line 9 "combineenum1_2.c"
extern int ( /* missing proto */  foo)() ;
#line 8 "combineenum1_2.c"
int main(void) 
{ 


  {
#line 9
  foo();
#line 10
  if ((unsigned int )x1 != 1U) {
#line 10
    printf("Error %d\n", 1);
#line 10
    exit(1);
  }
#line 12
  printf("Success\n");
#line 12
  exit(0);
}
}
