/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 1 "combine8_2.c"
struct bar ;
#line 1 "combine8_2.c"
struct __anonstruct_STR_528287478 {
   int x ;
   struct bar *next ;
};
#line 1 "combine8_2.c"
typedef struct __anonstruct_STR_528287478 STR;
#line 8 "combine8_2.c"
struct bar {
   double d ;
};
#line 6 "combine8_2.c"
STR *g1  ;
