/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 5 "combine9_1.c"
typedef int INT;
#line 7 "combine9_1.c"
struct __anonstruct_g_15862768 {
   INT i ;
   int x ;
};
#line 3 "testharness.h"
extern int printf(char const   *format  , ...) ;
#line 12
extern void exit(int  ) ;
#line 7 "combine9_1.c"
struct __anonstruct_g_15862768 g  ;
#line 13 "combine9_1.c"
int main(void) 
{ 


  {
#line 14
  printf("Error %d\n", 1);
#line 14
  exit(1);
}
}
