/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 3 "combine_init_2.c"
struct logger {
   char *s ;
   int i ;
};
#line 8 "combine_init_2.c"
static struct logger __constr_expr_0  =    {(char *)"redRestoreSuccess", 2014};
#line 8 "combine_init_2.c"
static struct logger __constr_expr_1  =    {(char *)"redRestoreFail", 2015};
#line 8 "combine_init_2.c"
struct logger *event_list_CHASSIS_2[3]  = {      & __constr_expr_0,      & __constr_expr_1,      (struct logger *)0};
