/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 1 "combine1_3.c"
typedef int INT;
#line 3 "combine1_3.c"
struct str1 {
   INT x1 ;
   int x2 ;
};
#line 3 "combine1_3.c"
struct str1 array2  ;
#line 8 "combine1_3.c"
int c3(void) 
{ 
  int var ;

  {
#line 11
  var = 9;
#line 12
  return ((int )sizeof(array2));
}
}
