/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 2 "combine2_1.c"
char *foo[2] ;
#line 5 "combine2_1.c"
char *foo[2]  = {      (char *)"first string",      (char *)"second string"};
#line 7
extern int bar ;
#line 9 "combine2_1.c"
int f1(void) 
{ 


  {
#line 10
  return (bar);
}
}
