/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 3 "combine10_3.c"
struct foo {
   struct foo *left ;
   struct foo *right ;
   int x ;
};
#line 3 "testharness.h"
extern int printf(char const   *format  , ...) ;
#line 12
extern void exit(int  ) ;
#line 3 "combine10_3.c"
extern struct foo g1 ;
#line 3
extern struct foo g2 ;
#line 9 "combine10_3.c"
int main(void) 
{ 


  {
#line 10
  g1 = g2;
#line 11
  printf("Success\n");
#line 11
  exit(0);
}
}
