/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 3 "testharness.h"
extern int printf(char const   *format  , ...) ;
#line 12
extern void exit(int  ) ;
#line 5 "combineinline4_1.c"
__inline int foo(int x ) ;
#line 7 "combineinline4_1.c"
__inline int foo(int x ) 
{ 


  {
#line 7
  return (x);
}
}
#line 9
extern int getfoo2() ;
#line 11 "combineinline4_1.c"
int main(void) 
{ 
  int tmp ;

  {
#line 12
  tmp = getfoo2();
#line 12
  if (tmp != (int )(& foo)) {
#line 13
    printf("Merging of inlines did not work\n");
#line 14
    printf("Error %d\n", 1);
#line 14
    exit(1);
  }
#line 17
  printf("Success\n");
#line 17
  exit(0);
}
}
