/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 1 "combine1_1.c"
typedef int INT;
#line 3 "combine1_1.c"
struct str1 {
   INT x1 ;
   int x2 ;
};
#line 3 "combine1_1.c"
struct str1 array  ;
#line 8 "combine1_1.c"
int var  =    7;
#line 10
extern void printf(char *  , ...) ;
#line 13
extern int c2(void) ;
#line 13
extern int c3(void) ;
#line 14 "combine1_1.c"
int main(void) 
{ 
  int c1res ;
  int c2res ;
  int tmp ;
  int c3res ;
  int tmp___0 ;

  {
#line 15
  c1res = (int )sizeof(array);
#line 16
  tmp = c2();
#line 16
  c2res = tmp;
#line 17
  tmp___0 = c3();
#line 17
  c3res = tmp___0;
#line 19
  if (c1res != c3res) {
#line 19
    printf((char *)"Error %d\n", 1);
#line 19
    return (1);
  }
#line 21
  if ((unsigned long )c2res != sizeof(int [10]) + sizeof(int )) {
#line 21
    printf((char *)"Error %d\n", 2);
#line 21
    return (2);
  }
#line 23
  if (var != 7) {
#line 23
    printf((char *)"Error %d\n", 3);
#line 23
    return (3);
  }
#line 25
  printf((char *)"Success\n");
#line 26
  return (0);
}
}
