/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 1 "combine21_1.c"
static int gflag  ;
#line 3 "combine21_1.c"
__inline void testit(int flag ) 
{ 


  {
#line 5
  gflag = flag;
#line 6
  return;
}
}
#line 8
extern void otest(int flag ) ;
#line 10 "combine21_1.c"
int main(int argc , char **argv ) 
{ 


  {
#line 13
  testit(0);
#line 14
  otest(2);
#line 15
  testit(1);
#line 16
  return (0);
}
}
