/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 24 "combinelibrik_1.c"
struct chunk_struct {
   char c_tab[20] ;
   struct chunk_struct *c_prev ;
};
#line 29 "combinelibrik_1.c"
typedef struct chunk_struct chunk;
#line 125 "/usr/include/string.h"
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1,2), __leaf__)) strcpy)(char * __restrict  __dest ,
                                                                                                 char const   * __restrict  __src ) ;
#line 32 "combinelibrik_1.c"
int chunk1(char *s ) 
{ 
  chunk c ;

  {
#line 36
  strcpy((char */* __restrict  */)s, (char const   */* __restrict  */)(c.c_tab));
#line 38
  return ((int )c.c_tab[0]);
}
}
