/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  4 "comma1.c"
int to_hex(int x ) 
{ 


  {
//#line  4
  return (x);
}
}
//#line  6 "comma1.c"
int main(void) 
{ 
  int tmp ;

  {
//#line  8
  tmp = to_hex(6);
//#line  8
  if (6 != tmp) {
//#line  8
    printf("Error %d\n", 1);
//#line  8
    exit(1);
  }
//#line  10
  printf("Success\n");
//#line  10
  exit(0);
}
}
