/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  197 "/usr/include/x86_64-linux-gnu/sys/types.h"
typedef long int64_t;
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  10 "comparisons.c"
int main(void) 
{ 
  int64_t a64 ;
  int64_t b64 ;
  float f ;
  double d ;
  int *p ;
  int64_t bignum ;

  {
//#line  15
  p = (int *)0;
//#line  17
  bignum = (int64_t )1;
//#line  18
  bignum <<= 40;
//#line  21
  a64 = (int64_t )42;
//#line  22
  b64 = a64 + bignum;
//#line  25
  if (a64 == b64) {
//#line  26
    printf("Error %d\n", 1);
//#line  26
    exit(1);
  }
//#line  28
  if (a64 >= b64) {
//#line  29
    printf("Error %d\n", 2);
//#line  29
    exit(2);
  }
//#line  31
  if ((a64 | bignum) == a64) {
//#line  32
    printf("Error %d\n", 3);
//#line  32
    exit(3);
  }
//#line  34
  if (! bignum) {
//#line  35
    printf("Error %d\n", 5);
//#line  35
    exit(5);
  }
//#line  38
  f = 0.125f;
//#line  39
  if (! f) {
//#line  40
    printf("Error %d\n", 10);
//#line  40
    exit(10);
  }
//#line  41
  if (f >= 0.25f) {
//#line  42
    printf("Error %d\n", 11);
//#line  42
    exit(11);
  }
//#line  44
  d = 0.125;
//#line  45
  if (d < (double )f) {
//#line  46
    printf("Error %d\n", 12);
//#line  46
    exit(12);
  } else
//#line  45
  if (d > (double )f) {
//#line  46
    printf("Error %d\n", 12);
//#line  46
    exit(12);
  }
//#line  49
  printf("Success\n");
//#line  49
  exit(0);
}
}
