/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "compound1.c"
int main(void) 
{ 
  unsigned long a ;
  unsigned long *p ;

  {
//#line  6
  p = (unsigned long *)(& p);
//#line  7
  (*p) ++;
//#line  7
  a = *p;
//#line  8
  if (a - 1UL != (unsigned long )(& p)) {
//#line  9
    printf("Error %d\n", 1);
//#line  9
    exit(1);
  }
//#line  10
  printf("Success\n");
//#line  10
  exit(0);
}
}
