/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "compound2.c"
struct l {
   struct l **next ;
};
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "compound2.c"
int main(void) 
{ 
  struct l s[4] ;
  struct l *a ;
  struct l *p[4] ;
  struct l *old ;
  struct l *tmp ;

  {
//#line  10
  p[0] = s;
//#line  11
  (p[0])->next = & p[0];
//#line  12
  old = *((p[0])->next);
//#line  13
  tmp = *((p[0])->next) + 1;
//#line  13
  *((p[0])->next) = tmp;
//#line  13
  a = tmp;
//#line  14
  if ((unsigned long )(old + 1) != (unsigned long )a) {
//#line  15
    printf("Error %d\n", 1);
//#line  15
    exit(1);
  }
//#line  16
  printf("Success\n");
//#line  16
  exit(0);
}
}
