/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "cond1.c"
int foo(void) 
{ 


  {
//#line  4
  return (5);
}
}
//#line  7 "cond1.c"
int main(void) 
{ 
  int x1 ;
  int tmp ;
  int x2 ;
  int tmp___0 ;
  int x3 ;
  int x4 ;
  int tmp___1 ;

  {
//#line  9
  goto L1;
//#line  9
  if (0) {
    L1: 
//#line  9
    tmp = 1;
  } else {
//#line  9
    tmp = 0;
  }
//#line  9
  x1 = tmp;
//#line  11
  printf("x1 = %d\n", x1);
//#line  13
  if (x1 != 1) {
//#line  13
    printf("Error %d\n", 1);
//#line  13
    exit(1);
  }
//#line  16
  if (0) {
//#line  16
    tmp___0 = 1;
  } else {
//#line  16
    tmp___0 = 0;
  }
//#line  16
  x2 = tmp___0;
//#line  17
  if (x2 != 0) {
//#line  17
    printf("Error %d\n", 2);
//#line  17
    exit(2);
  }
//#line  21
  x3 = 1;
//#line  22
  printf("x3 = %d\n", x3);
//#line  23
  if (x3 != 1) {
//#line  23
    printf("Error %d\n", 3);
//#line  23
    exit(3);
  }
//#line  27
  tmp___1 = foo();
//#line  27
  x4 = tmp___1 != 0;
//#line  28
  printf("x4 = %d\n", x4);
//#line  29
  if (x4 != 1) {
//#line  29
    printf("Error %d\n", 4);
//#line  29
    exit(4);
  }
//#line  32
  printf("Success\n");
//#line  32
  exit(0);
}
}
