/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "cond2.c"
int calls_to_foo  =    0;
//#line  4 "cond2.c"
int foo(void) 
{ 


  {
//#line  5
  calls_to_foo ++;
//#line  6
  return (calls_to_foo);
}
}
//#line  16
int main(void) ;
//#line  16 "cond2.c"
static int x  =    (int )((int (*)(void))1);
//#line  15 "cond2.c"
int main(void) 
{ 
  int *x2 ;
  int (*tmp)(void) ;
  int x3 ;
  int tmp___1 ;

  {
//#line  18
  if (x != 1) {
//#line  18
    printf("Error %d\n", 1);
//#line  18
    exit(1);
  }
//#line  21
  tmp = & main;
//#line  21
  if (! tmp) {
//#line  21
    tmp = (int (*)(void))0;
  }
//#line  21
  x2 = (int *)tmp;
//#line  22
  if ((unsigned long )x2 != (unsigned long )(& main)) {
//#line  22
    printf("Error %d\n", 2);
//#line  22
    exit(2);
  }
//#line  26
  tmp___1 = foo();
//#line  26
  if (! tmp___1) {
//#line  26
    tmp___1 = 0;
  }
//#line  26
  x3 = tmp___1;
//#line  27
  if (x3 != 1) {
//#line  27
    printf("Error %d\n", 3);
//#line  27
    exit(3);
  } else
//#line  27
  if (calls_to_foo != 1) {
//#line  27
    printf("Error %d\n", 3);
//#line  27
    exit(3);
  }
//#line  29
  printf("Success\n");
//#line  29
  exit(0);
}
}
