/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "const2.c"
int main(void) 
{ 
  unsigned int x ;

  {
//#line  4
  x = 4294967295U;
//#line  6
  if ((x >= 0U) == 0) {
//#line  6
    printf("Error %d\n", 1);
//#line  6
    exit(1);
  }
//#line  11
  printf("Success\n");
//#line  11
  exit(0);
//#line  13
  return (0);
}
}
