/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  5 "const-array-init.c"
struct bar {
   int f2 ;
   int a[8] ;
};
//#line  5 "const-array-init.c"
struct foo {
   int f1 ;
   struct bar b ;
};
//#line  543 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
//#line  13 "const-array-init.c"
int main(void) 
{ 
  int values[1] ;
  struct foo f ;
  unsigned int tmp ;
  int x ;

  {
//#line  15
  values[0] = 0;
//#line  16
  f.f1 = 1;
//#line  16
  f.b.f2 = 2;
//#line  16
  f.b.a[0] = 3;
//#line  16
  f.b.a[1] = 4;
//#line  16
  f.b.a[2] = 5;
//#line  16
  f.b.a[3] = 6;
//#line  16
  tmp = 4U;
//#line  16
  while (! (tmp >= 8U)) {
//#line  16
    f.b.a[tmp] = 0;
//#line  16
    tmp ++;
  }
//#line  18
  x = values[0];
//#line  19
  exit(((x + f.f1) + f.b.f2) - f.b.a[0]);
}
}
