/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "const3.c"
int main(void) 
{ 
  long long x ;

  {
//#line  4
  x = 8LL;
//#line  6
  if (x != 8LL) {
//#line  6
    printf("Error %d\n", 1);
//#line  6
    exit(1);
  }
//#line  8
  printf("Success\n");
//#line  8
  exit(0);
}
}
