/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  7 "const6.c"
int tst[1]  ;
//#line  12
extern int ( /* missing proto */  abort)() ;
//#line  14
extern int ( /* missing proto */  exit)() ;
//#line  10 "const6.c"
int main(void) 
{ 


  {
//#line  11
  if (sizeof(tst) != 4UL) {
//#line  12
    abort();
  }
//#line  14
  exit(0);
}
}
