/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  2 "const10.c"
int mine[1]  = {      1};
//#line  5 "const10.c"
int main(void) 
{ 


  {
//#line  6
  return (mine[0] - 1);
}
}
