/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "const-struct-init.c"
struct inner {
   int field ;
};
//#line  6 "const-struct-init.c"
struct outer {
   struct inner inner ;
};
//#line  11 "const-struct-init.c"
int main(void) 
{ 
  struct outer outer ;

  {
//#line  13
  outer.inner.field = 0;
//#line  14
  return (outer.inner.field);
}
}
