/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "const16.c"
struct F {
   int x ;
   int y ;
};
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  5 "const16.c"
int main(void) 
{ 
  int timeout ;
  int x ;
  struct F i ;
  int tmp ;

  {
//#line  7
  timeout = 0;
//#line  8
  x = 0;
//#line  9
  while (1) {
//#line  11
    tmp = x;
//#line  11
    x ++;
//#line  11
    i.x = tmp;
//#line  11
    i.y = 0;
//#line  12
    if (i.x > 0) {
//#line  13
      break;
    }
//#line  14
    timeout ++;
//#line  14
    if (timeout > 5) {
//#line  15
      goto die;
    }
  }
//#line  17
  return (0);
  die: 
//#line  19
  printf("Error %d\n", 1);
//#line  19
  exit(1);
}
}
