/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "const8.c"
int main(void) 
{ 
  unsigned int base ;
  unsigned long max ;
  unsigned long max1 ;

  {
//#line  4
  base = 5U;
//#line  5
  max = 0xffffffffffffffffUL / (unsigned long )base;
//#line  7
  max1 = 0xffffffffffffffffUL;
//#line  8
  printf("max = %ld, max1 = %ld\n", max, max1 / (unsigned long )base);
//#line  10
  if (max != max1 / (unsigned long )base) {
//#line  10
    printf("Error %d\n", 1);
//#line  10
    exit(1);
  }
//#line  12
  printf("Success\n");
//#line  12
  exit(0);
}
}
