/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "const15.c"
unsigned long x  =    0xfffffffffffffffeUL;
//#line  5 "const15.c"
int main(void) 
{ 


  {
//#line  8
  if (sizeof(unsigned long ) == 8UL) {
//#line  8
    if (x == 4294967294UL) {
//#line  10
      printf("Error %d\n", 1);
//#line  10
      exit(1);
    }
  }
//#line  12
  printf("Success\n");
//#line  12
  exit(0);
//#line  13
  return (0);
}
}
