/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "constfold.c"
int global  ;
//#line  5 "constfold.c"
void init(void) 
{ 


  {
//#line  7
  global = 1;
//#line  8
  return;
}
}
//#line  11 "constfold.c"
int main(void) 
{ 


  {
  {
//#line  13
  global = 0;
//#line  14
  init();
  }
  {
  {
  {
//#line  19
  printf("Error %d\n", 1);
//#line  19
  exit(1);
  }
  }
  }
//#line  21
  return (0);
}
}
