/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  5 "const13.c"
struct __anonstruct_t2_352126815 {
   char p[5] ;
};
//#line  5 "const13.c"
typedef struct __anonstruct_t2_352126815 t2;
//#line  10
extern void consttst1(char const   *p ) ;
//#line  12 "const13.c"
void consttst2(t2 const   *p2 ) 
{ 
  char *tmp ;

  {
//#line  14
  if (p2->p[0]) {
//#line  14
    tmp = p2->p;
  } else {
//#line  14
    tmp = (char */* const  */)((void *)0);
  }
//#line  14
  consttst1((char const   *)tmp);
//#line  15
  return;
}
}
