/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  9 "const11.c"
int main(void) 
{ 
  int x ;
  int aa ;
  int bb ;
  int cc ;
  int a ;
  char b ;
  int c ;
  unsigned long long d ;
  unsigned long long e ;
  int f ;
  int g ;

  {
//#line  10
  x = 257;
//#line  13
  a = 1 << 9;
//#line  14
  b = (char )(1 << 9);
//#line  15
  c = 1 << 1;
//#line  16
  d = (unsigned long long )(1 << 33);
//#line  17
  e = 1ULL << 33;
//#line  18
  f = 1 << 64;
//#line  19
  g = 1 << -1;
//#line  22
  printf("a=%d, b=%d, c=%d, d=%d:%u, e=%d:%u, f=%d, g=%d\n", a, (int )b, c, (int )(d >> 32),
         (unsigned int )d, (int )(e >> 32), (unsigned int )e, f, g);
//#line  28
  aa = (int )(8589934592ULL >> 33);
//#line  29
  bb = (int )(8589934592ULL >> 65);
//#line  30
  cc = 3 >> -1;
//#line  33
  printf("aa=%d, bb=%d, cc=%d\n", aa, bb, cc);
//#line  36
  if (a != 512) {
//#line  36
    printf("Error %d\n", 2);
//#line  36
    exit(2);
  }
//#line  37
  if ((int )b != 0) {
//#line  37
    printf("Error %d\n", 3);
//#line  37
    exit(3);
  }
//#line  38
  if (c != 2) {
//#line  38
    printf("Error %d\n", 4);
//#line  38
    exit(4);
  }
//#line  39
  if (d != 0ULL) {
//#line  39
    printf("Error %d\n", 5);
//#line  39
    exit(5);
  }
//#line  40
  if (e != 8589934592ULL) {
//#line  40
    printf("Error %d\n", 6);
//#line  40
    exit(6);
  }
//#line  41
  if (f != 0) {
//#line  41
    printf("Error %d\n", 7);
//#line  41
    exit(7);
  }
//#line  42
  if (g != 0) {
//#line  42
    printf("Error %d\n", 8);
//#line  42
    exit(8);
  }
//#line  44
  if (aa != 1) {
//#line  44
    printf("Error %d\n", 9);
//#line  44
    exit(9);
  }
//#line  45
  if (bb != 0) {
//#line  45
    printf("Error %d\n", 10);
//#line  45
    exit(10);
  }
//#line  46
  if (cc != 6) {
//#line  46
    printf("Error %d\n", 11);
//#line  46
    exit(11);
  }
//#line  48
  printf("Success\n");
//#line  48
  exit(0);
}
}
