/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "const4.c"
struct reiserfs_de_head {
   int x ;
   int y ;
};
/* compiler builtin: 
   void *__builtin_alloca(unsigned long  ) ;  */
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  7 "const4.c"
int somefunction(void) 
{ 


  {
//#line  8
  return (8);
}
}
//#line  11
extern int ( /* missing proto */  strlen)() ;
//#line  10 "const4.c"
int main(void) 
{ 
  int tmp ;
  int tmp___0 ;
  char *empty_dir ;
  unsigned long __lengthofempty_dir ;
  void *tmp___1 ;
  int tmp___2 ;
  char *another ;
  unsigned long __lengthofanother ;
  void *tmp___3 ;

  {
//#line  11
  tmp = strlen(".");
//#line  11
  tmp___0 = strlen("..");
//#line  11
  __lengthofempty_dir = (unsigned long )(((unsigned long long )(sizeof(struct reiserfs_de_head ) * 2UL) + (unsigned long long )((((long long )tmp + 8LL) - 1LL) & -8LL)) + (unsigned long long )((((long long )tmp___0 + 8LL) - 1LL) & -8LL));
//#line  11
  tmp___1 = __builtin_alloca(sizeof(*empty_dir) * __lengthofempty_dir);
//#line  11
  empty_dir = (char *)tmp___1;
//#line  16
  tmp___2 = somefunction();
//#line  16
  __lengthofanother = (unsigned long )tmp___2;
//#line  16
  tmp___3 = __builtin_alloca(sizeof(*another) * __lengthofanother);
//#line  16
  another = (char *)tmp___3;
//#line  18
  printf("Sizeof empty_dir=%d\n", (int )(sizeof(*empty_dir) * __lengthofempty_dir));
//#line  19
  if (sizeof(*empty_dir) * __lengthofempty_dir != 32UL) {
//#line  19
    printf("Error %d\n", 1);
//#line  19
    exit(1);
  }
//#line  21
  printf("Sizeof another=%d\n", (int )(sizeof(*another) * __lengthofanother));
//#line  22
  if (sizeof(*another) * __lengthofanother != 8UL) {
//#line  22
    printf("Error %d\n", 2);
//#line  22
    exit(2);
  }
//#line  25
  printf("Success\n");
//#line  25
  exit(0);
}
}
