/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
/* compiler builtin: 
   void *__builtin_alloca(unsigned long  ) ;  */
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  394 "/usr/include/string.h"
extern  __attribute__((__nothrow__)) size_t ( __attribute__((__nonnull__(1), __leaf__)) strlen)(char const   *__s )  __attribute__((__pure__)) ;
//#line  4 "const5.c"
int main(void) 
{ 
  int slen ;
  size_t tmp ;
  char *silly ;
  unsigned long __lengthofsilly ;
  void *tmp___0 ;

  {
//#line  6
  tmp = strlen(".nfs");
//#line  6
  slen = (int )(tmp + 5UL);
//#line  7
  __lengthofsilly = (unsigned long )(slen + 1);
//#line  7
  tmp___0 = __builtin_alloca(sizeof(*silly) * __lengthofsilly);
//#line  7
  silly = (char *)tmp___0;
//#line  9
  slen += 20;
//#line  11
  if (sizeof(*silly) * __lengthofsilly != 10UL) {
//#line  11
    printf("Error %d\n", 1);
//#line  11
    exit(1);
  }
//#line  13
  printf("Success\n");
//#line  13
  exit(0);
}
}
