/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "const1.c"
unsigned long long x1  =    0xff00000000000000ULL;
//#line  5 "const1.c"
int main(void) 
{ 


  {
//#line  8
  if (2147483647 >> 31 != 0) {
//#line  8
    printf("Error %d\n", 1);
//#line  8
    exit(1);
  }
//#line  10
  if ((-0x7FFFFFFF-1) >> 31 != -1) {
//#line  10
    printf("Error %d\n", 2);
//#line  10
    exit(2);
  }
//#line  13
  if (2147483648L >> 31 != 1L) {
//#line  13
    printf("Error %d\n", 3);
//#line  13
    exit(3);
  }
//#line  16
  if (2147483648U >> 31 != 1U) {
//#line  16
    printf("Error %d\n", 4);
//#line  16
    exit(4);
  }
//#line  19
  if (x1 >> 56 != 255ULL) {
//#line  19
    printf("Error %d\n", 5);
//#line  19
    exit(5);
  }
//#line  22
  if (0xff00000000000000ULL >> 56 != 255ULL) {
//#line  22
    printf("Error %d\n", 6);
//#line  22
    exit(6);
  }
//#line  25
  printf("Success\n");
//#line  25
  exit(0);
}
}
