/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "constprop.c"
int foo(int x ) 
{ 
  int y ;
  unsigned long tmp ;

  {
//#line  4
  if ((((1UL << 12) / 384UL) * 64UL) * 8UL > 1048576UL) {
//#line  4
    tmp = 1048576UL;
  } else {
//#line  4
    tmp = (((1UL << 12) / 384UL) * 64UL) * 8UL;
  }
//#line  4
  y = (int )(tmp / (8UL * sizeof(unsigned long )));
//#line  8
  if ((unsigned long )(5 << 2)) {
//#line  9
    x ++;
  } else {
//#line  11
    x --;
  }
//#line  13
  return (0);
}
}
