/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  2 "cpp-3.c"
extern int strlen(char const   * ) ;
//#line  6 "cpp-3.c"
char *str  =    (char *)"( { [ %   \033 \033 \a \b \f \n \r \t \v ? \\ \' ";
//#line  8 "cpp-3.c"
int main(void) 
{ 
  int tmp ;

  {
//#line  9
  tmp = strlen((char const   *)str);
//#line  9
  if (tmp != 34) {
//#line  9
    printf("Error %d\n", 1);
//#line  9
    exit(1);
  }
//#line  10
  return (0);
}
}
