/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  6 "decl_mix_stmt.c"
int main(void) 
{ 
  int x ;
  int y ;

  {
//#line  9
  x = 3;
//#line  12
  y = 6;
//#line  14
  return ((x + y) - 9);
}
}
