/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "decl1.c"
struct timeval {
   int tv_sec ;
   int tv_usec ;
};
//#line  6 "decl1.c"
struct timeval  volatile  xtime  __attribute__((__aligned__(16)))  ;
//#line  11
extern void printf(char *  , ...) ;
//#line  15 "decl1.c"
int main(void) 
{ 


  {
//#line  16
  if ((int )(& xtime) & 1) {
//#line  16
    printf((char *)"Error %d\n", 1);
//#line  16
    return (1);
  }
//#line  18
  printf((char *)"Success\n");
//#line  19
  return (0);
}
}
