/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "decl2.c"
int f(unsigned char x ) ;
//#line  4
int s(short x ) ;
//#line  5
int d(float x ) ;
//#line  7 "decl2.c"
int main(void) 
{ 
  int x1 ;
  int tmp ;
  int x2 ;
  int tmp___0 ;
  int x3 ;
  int tmp___1 ;
  int x4 ;
  int tmp___2 ;

  {
//#line  10
  tmp = f(5);
//#line  10
  x1 = tmp;
//#line  11
  if (x1 != 5) {
//#line  11
    printf("Error %d\n", 1);
//#line  11
    exit(1);
  }
//#line  15
  tmp___0 = f(256);
//#line  15
  x2 = tmp___0;
//#line  16
  if (x2 != 0) {
//#line  16
    printf("Error %d\n", 2);
//#line  16
    exit(2);
  }
//#line  20
  tmp___1 = s(65537);
//#line  20
  x3 = tmp___1;
//#line  21
  if (x3 != 1) {
//#line  21
    printf("Error %d\n", 3);
//#line  21
    exit(3);
  }
//#line  25
  tmp___2 = d((double )1);
//#line  25
  x4 = tmp___2;
//#line  26
  if (x4 != 1) {
//#line  26
    printf("Error %d\n", 4);
//#line  26
    exit(4);
  }
//#line  29
  printf("Success\n");
//#line  29
  exit(0);
}
}
//#line  34 "decl2.c"
int f(unsigned char x ) 
{ 


  {
//#line  37
  return ((int )x);
}
}
//#line  40 "decl2.c"
int s(short x ) 
{ 


  {
//#line  43
  return ((int )x);
}
}
//#line  46 "decl2.c"
int d(float x ) 
{ 


  {
//#line  49
  return ((int )x);
}
}
