/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "duplicate.c"
typedef int agp_setup___0;
//#line  4 "duplicate.c"
static int test___0  ;
//#line  13 "duplicate.c"
int foo(int jiffies ) 
{ 


  {
//#line  14
  return (test___0 + jiffies);
}
}
//#line  18 "duplicate.c"
float test  ;
//#line  20 "duplicate.c"
float bar(void) 
{ 
  agp_setup___0 x ;

  {
//#line  21
  x = 5;
//#line  22
  return ((float )x);
}
}
//#line  25
extern float jiffies ;
//#line  27 "duplicate.c"
int agp_setup(void) 
{ 


  {
//#line  28
  return ((int )((float )5 + jiffies));
}
}
