/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  7 "enum3j.c"
int main(void) 
{ 
  int ok ;
  int tmp ;
  int tmp___0 ;

  {
//#line  9
  ok = 1;
//#line  11
  if (ok) {
//#line  11
    tmp = 1;
  } else {
//#line  11
    tmp = 0;
  }
//#line  11
  ok = tmp;
//#line  13
  if (ok) {
//#line  13
    tmp___0 = 0;
  } else {
//#line  13
    tmp___0 = 2;
  }
//#line  13
  return (tmp___0);
}
}
