/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  5 "enum3l.c"
int main(void) 
{ 
  int ok ;
  int tmp ;
  int tmp___0 ;

  {
//#line  7
  ok = 1;
//#line  10
  if (ok) {
//#line  10
    tmp = 1;
  } else {
//#line  10
    tmp = 0;
  }
//#line  10
  ok = tmp;
//#line  12
  if (ok) {
//#line  12
    tmp___0 = 0;
  } else {
//#line  12
    tmp___0 = 2;
  }
//#line  12
  return (tmp___0);
}
}
