/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  6 "enum2.c"
enum foo ;
//#line  6 "enum2.c"
typedef enum foo E;
//#line  7
enum foo {
    e0 = 0,
    e1 = 2
} ;
//#line  10
enum bar {
    b0 = 2
} ;
//#line  12 "enum2.c"
struct __anonstruct_s_104652499 {
   E eval ;
   enum bar b ;
};
//#line  1
extern void exit(int  ) ;
//#line  2
extern void abort(void) ;
//#line  12 "enum2.c"
struct __anonstruct_s_104652499 s  ;
//#line  17 "enum2.c"
void p(void) 
{ 


  {
//#line  18
  abort();
//#line  19
  return;
}
}
//#line  21 "enum2.c"
void f(void) 
{ 


  {
//#line  22
  switch ((unsigned int )s.eval) {
  case 4U: 
  case 0U: 
//#line  25
  p();
  }
//#line  27
  return;
}
}
//#line  29 "enum2.c"
int main(void) 
{ 


  {
//#line  30
  s.eval = (E )2;
//#line  31
  f();
//#line  32
  exit(0);
}
}
