/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  4 "escapes.c"
char escapes[145]  = 
//#line  4 "escapes.c"
  {      (char )'\000',      (char )'\001',      (char )'\002',      (char )'\003', 
        (char )'\004',      (char )'\005',      (char )'\006',      (char )'\a', 
        (char )'\b',      (char )'\t',      (char )'\n',      (char )'\v', 
        (char )'\f',      (char )'\r',      (char )'\016',      (char )'\017', 
        (char )'\020',      (char )'\021',      (char )'\022',      (char )'\023', 
        (char )'\024',      (char )'\025',      (char )'\026',      (char )'\027', 
        (char )'\030',      (char )'\031',      (char )'\032',      (char )'\033', 
        (char )'\034',      (char )'\035',      (char )'\036',      (char )'\037', 
        (char )' ',      (char )'!',      (char )'\"',      (char )'#', 
        (char )'$',      (char )'%',      (char )'&',      (char )'\'', 
        (char )'(',      (char )')',      (char )'*',      (char )'+', 
        (char )',',      (char )'-',      (char )'.',      (char )'/', 
        (char )'0',      (char )'1',      (char )'2',      (char )'3', 
        (char )'4',      (char )'5',      (char )'6',      (char )'7', 
        (char )'8',      (char )'9',      (char )':',      (char )';', 
        (char )'<',      (char )'=',      (char )'>',      (char )'?', 
        (char )'@',      (char )'A',      (char )'B',      (char )'C', 
        (char )'D',      (char )'E',      (char )'F',      (char )'G', 
        (char )'H',      (char )'I',      (char )'J',      (char )'K', 
        (char )'L',      (char )'M',      (char )'N',      (char )'O', 
        (char )'P',      (char )'Q',      (char )'R',      (char )'S', 
        (char )'T',      (char )'U',      (char )'V',      (char )'W', 
        (char )'X',      (char )'Y',      (char )'Z',      (char )'[', 
        (char )'\\',      (char )']',      (char )'^',      (char )'_', 
        (char )'`',      (char )'a',      (char )'b',      (char )'c', 
        (char )'d',      (char )'e',      (char )'f',      (char )'g', 
        (char )'h',      (char )'i',      (char )'j',      (char )'k', 
        (char )'l',      (char )'m',      (char )'n',      (char )'o', 
        (char )'p',      (char )'q',      (char )'r',      (char )'s', 
        (char )'t',      (char )'u',      (char )'v',      (char )'w', 
        (char )'x',      (char )'y',      (char )'z',      (char )'{', 
        (char )'|',      (char )'}',      (char )'~',      (char )'\177', 
        (char )'\200',      (char )'\201',      (char )'\202',      (char )'\203', 
        (char )'\204',      (char )'\205',      (char )'\206',      (char )'\207', 
        (char )'\210',      (char )'\211',      (char )'\212',      (char )'\213', 
        (char )'\214',      (char )'\215',      (char )'\216',      (char )'\217', 
        (char )'\000'};
//#line  26 "escapes.c"
int main(void) 
{ 
  unsigned char i ;

  {
//#line  28
  i = (unsigned char)0;
//#line  28
  while ((int )i < 144) {
//#line  29
    if ((int )((unsigned char )escapes[i]) != (int )i) {
//#line  30
      printf("escapes[%d] = 0x%x\n", (int )i, (int )escapes[i]);
//#line  31
      printf("Error %d\n", (int )i);
//#line  31
      exit((int )i);
    }
//#line  28
    i = (unsigned char )((int )i + 1);
  }
//#line  35
  printf("Success\n");
//#line  35
  exit(0);
}
}
