/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "extinline2.c"
__inline int f(void) ;
//#line  5 "extinline2.c"
int g(void) 
{ 
  int tmp ;

  {
//#line  7
  tmp = f();
//#line  7
  return (tmp);
}
}
//#line  10 "extinline2.c"
__inline int f(void) 
{ 


  {
//#line  10
  return (2);
}
}
//#line  12 "extinline2.c"
int h(void) 
{ 
  int tmp ;

  {
//#line  14
  tmp = f();
//#line  14
  return (tmp);
}
}
//#line  18 "extinline2.c"
int main(void) 
{ 
  int tmp ;
  int tmp___0 ;

  {
//#line  20
  tmp = g();
//#line  20
  if (tmp != 2) {
//#line  20
    printf("Error %d\n", 1);
//#line  20
    exit(1);
  }
//#line  21
  tmp___0 = h();
//#line  21
  if (tmp___0 != 2) {
//#line  21
    printf("Error %d\n", 1);
//#line  21
    exit(1);
  }
//#line  22
  printf("Success\n");
//#line  22
  exit(0);
}
}
