/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "extinline3.c"
__inline extern int f(void) 
{ 


  {
//#line  1
  return (1);
}
}
//#line  3 "extinline3.c"
int g(void) 
{ 
  int tmp ;

  {
//#line  5
  tmp = f();
//#line  5
  return (tmp);
}
}
