/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "flexible-array-member.c"
struct s {
   unsigned long x ;
   int y ;
   char t[] ;
};
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  10 "flexible-array-member.c"
int main(void) ;
//#line  10 "flexible-array-member.c"
static struct s b  =    {sizeof(b), 2, {(char)1, (char)2, (char)3}};
//#line  18
int main(void) ;
//#line  18 "flexible-array-member.c"
static struct s c  =    {sizeof(b), 2, {(char)1, (char)2, (char)3, (char)4, (char)5}};
//#line  4 "flexible-array-member.c"
int main(void) 
{ 
  struct s a ;

  {
//#line  5
  a.x = sizeof(a);
//#line  5
  a.y = 2;
//#line  26
  if (a.x != sizeof(struct s )) {
//#line  26
    printf("Error %d\n", 1);
//#line  26
    exit(1);
  }
//#line  27
  if ((int )b.t[2] != 3) {
//#line  27
    printf("Error %d\n", 2);
//#line  27
    exit(2);
  }
//#line  28
  if ((int )c.t[4] != 5) {
//#line  28
    printf("Error %d\n", 2);
//#line  28
    exit(2);
  }
//#line  30
  printf("Success\n");
//#line  30
  exit(0);
}
}
