/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "float.c"
int main(void) 
{ 
  double f1 ;
  double f2 ;

  {
//#line  5
  f1 = 5.e-1;
//#line  6
  f2 = 5.00000e-1;
//#line  8
  if (f1 != f2) {
//#line  9
    printf("Error %d\n", 1);
//#line  9
    exit(1);
  }
//#line  11
  printf("Success\n");
//#line  11
  exit(0);
}
}
