/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
//#line  362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  42 "/usr/include/string.h"
extern  __attribute__((__nothrow__)) void *( __attribute__((__nonnull__(1,2), __leaf__)) memcpy)(void * __restrict  __dest ,
                                                                                                 void const   * __restrict  __src ,
                                                                                                 size_t __n ) ;
//#line  3 "float2.c"
int main(void) 
{ 
  double a[2][2] ;
  double __constr_expr_0[2][2] ;

  {
//#line  5
  __constr_expr_0[0][0] = 1.0;
//#line  5
  __constr_expr_0[0][1] = 2.0;
//#line  5
  __constr_expr_0[1][0] = 3.0;
//#line  5
  __constr_expr_0[1][1] = 4.0;
//#line  5
  memcpy((void */* __restrict  */)(a), (void const   */* __restrict  */)(__constr_expr_0),
         sizeof(a));
//#line  6
  printf((char const   */* __restrict  */)"%f %f %f %f\n", a[0][0], a[0][1], a[1][0],
         a[1][1]);
//#line  7
  return (0);
}
}
