/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "for1.c"
int main(void) 
{ 
  int z ;
  int i ;
  int j ;

  {
//#line  5
  i = 0;
//#line  5
  j = 5;
//#line  5
  while (1) {
//#line  5
    if (i <= 3) {
//#line  5
      if (! (j >= 3)) {
//#line  5
        break;
      }
    } else {
//#line  5
      break;
    }
//#line  6
    i += j - 3;
//#line  5
    i ++;
//#line  5
    j --;
//#line  5
    z = i;
  }
//#line  8
  if (z != 5) {
//#line  8
    printf("Error %d\n", 1);
//#line  8
    exit(1);
  }
//#line  10
  printf("Success\n");
//#line  10
  exit(0);
}
}
