/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "func.c"
typedef int (*intfun)(int  );
//#line  1 "func.c"
int (*pfun1)(int (*)(int  ) , int  )  ;
//#line  2 "func.c"
int (*pfun2)(int (*)(int  ) , int  )  ;
//#line  5 "func.c"
intfun arrfun[5]  ;
//#line  7 "func.c"
int testf(int k ) 
{ 


  {
//#line  8
  return (k);
}
}
//#line  11 "func.c"
int foo(int (*bar)(int  ) , int n ) 
{ 


  {
//#line  13
  pfun1 = & foo;
//#line  14
  pfun1 = & foo;
//#line  15
  pfun1 = pfun2;
//#line  17
  pfun1 = (int (*)(int (*)(int  ) , int  ))arrfun[4];
//#line  19
  (*pfun2)(& testf, 5);
//#line  21
  return (1);
}
}
