/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "func4.c"
struct __anonstruct_FOO_109580352 {
   int (*f)(int  ) ;
};
//#line  1 "func4.c"
typedef struct __anonstruct_FOO_109580352 FOO;
//#line  5 "func4.c"
int highorder(int (*a)(int  ) , int arg ) 
{ 
  int tmp ;

  {
//#line  6
  tmp = (*a)(arg);
//#line  6
  return (tmp);
}
}
//#line  9 "func4.c"
int incr(int x ) 
{ 


  {
//#line  10
  return (x + 1);
}
}
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  14 "func4.c"
int main(void) 
{ 
  int tmp ;
  FOO x ;
  int tmp___0 ;

  {
//#line  15
  tmp = highorder(& incr, 5);
//#line  15
  if (tmp != 6) {
//#line  15
    printf("Error %d\n", 1);
//#line  15
    exit(1);
  }
//#line  18
  x.f = & incr;
//#line  19
  tmp___0 = (*(x.f))(6);
//#line  19
  if (tmp___0 != 7) {
//#line  19
    printf("Error %d\n", 2);
//#line  19
    exit(2);
  }
//#line  22
  printf("Success\n");
//#line  22
  exit(0);
}
}
