/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "func3.c"
int foo(int *x , int z , int *y ) 
{ 


  {
//#line  5
  return ((*x + z) + *y);
}
}
//#line  8 "func3.c"
int main(void) 
{ 
  int x ;
  int y ;
  int z ;
  int (*f)() ;
  int tmp ;
  int tmp___0 ;

  {
//#line  9
  x = 5;
//#line  9
  y = 7;
//#line  9
  z = 13;
//#line  11
  f = (int (*)())(& foo);
//#line  13
  tmp = (*f)(& x, & z, & y);
//#line  13
  x = (tmp - 12) - (int )(& z);
//#line  15
  tmp___0 = foo(& x, z, & y);
//#line  15
  return ((x + tmp___0) - 20);
}
}
