/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "func2.c"
extern void exit(int  ) ;
//#line  9 "func2.c"
int fun1(int i1 , int *p2 , int *p3 , int i4 ) 
{ 


  {
//#line  10
  return (((i1 + *p2) + *p3) + i4);
}
}
//#line  14 "func2.c"
int (*g)()  =    (int (*)())(& fun1);
//#line  17 "func2.c"
int main(void) 
{ 
  int loc1 ;
  int loc2 ;
  int loc3 ;
  int tmp ;
  int tmp___0 ;

  {
//#line  18
  loc1 = 7;
//#line  18
  loc2 = 9;
//#line  18
  loc3 = 11;
//#line  21
  tmp = (*g)(5, & loc1, & loc2, 13);
//#line  21
  if (tmp != 34) {
//#line  22
    exit(1);
  }
//#line  25
  tmp___0 = fun1(1, & loc1, & loc3, 7);
//#line  25
  if (tmp___0 != 26) {
//#line  26
    exit(2);
  }
//#line  29
  exit(0);
}
}
