/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "funptr1.c"
typedef int ide_dmaproc_t(int  , int * );
//#line  11 "funptr1.c"
struct foo {
   ide_dmaproc_t *dmaproc ;
};
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  7 "funptr1.c"
int test(int x , int *y ) 
{ 


  {
//#line  8
  return (x + *y);
}
}
//#line  11 "funptr1.c"
struct foo x  =    {& test};
//#line  17 "funptr1.c"
int main(void) 
{ 
  int y ;
  int tmp ;

  {
//#line  18
  y = 7;
//#line  20
  tmp = (*(x.dmaproc))(5, & y);
//#line  20
  if (tmp != 12) {
//#line  20
    printf("Error %d\n", 1);
//#line  20
    exit(1);
  }
//#line  22
  printf("Success\n");
//#line  22
  exit(0);
}
}
