/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  2 "globals.c"
static int *glob2 ;
//#line  4 "globals.c"
int *glob1  =    (int *)(& glob2);
//#line  6 "globals.c"
static int *glob2  =    (int *)(& glob1);
//#line  8 "globals.c"
int arr2[10]  ;
