/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  2 "globals2.c"
int base_files[sizeof(lang_dir_names) / sizeof(lang_dir_names[0]) - 1UL] ;
//#line  3 "globals2.c"
char const   * const  lang_dir_names[2]  = {      (char const   */* const  */)"c",      (char const   */* const  */)((void *)0)};
//#line  6 "globals2.c"
int base_files[sizeof(lang_dir_names) / sizeof(lang_dir_names[0]) - 1UL]  = {      (int )sizeof(lang_dir_names[1])};
