/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "init15.c"
struct __anonstruct_brlock_read_lock_t_109580352 {
   int x ;
   int y ;
};
//#line  3 "init15.c"
typedef struct __anonstruct_brlock_read_lock_t_109580352 brlock_read_lock_t;
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  9 "init15.c"
brlock_read_lock_t __brlock_array[4][4]  = { {        {5, 6}, 
            {5, 6}, 
            {5, 6}, 
            {5, 6}}, 
   {        {5, 6}, 
            {5, 6}, 
            {5, 6}, 
            {5, 6}}, 
   {        {5, 6}, 
            {5, 6}, 
            {5, 6}, 
            {5, 6}}, 
   {        {5, 6}, 
            {5, 6}, 
            {5, 6}, 
            {5, 6}}};
//#line  12 "init15.c"
int main(void) 
{ 
  int i ;
  int j ;

  {
//#line  14
  i = 0;
//#line  14
  while (i < 4) {
//#line  15
    j = 0;
//#line  15
    while (j < 4) {
//#line  16
      if (__brlock_array[i][j].x != 5) {
//#line  18
        printf("At index [%d][%d] I found { %d, %d }\n", i, j, __brlock_array[i][j].x,
               __brlock_array[i][j].y);
//#line  20
        exit(1);
      } else
//#line  16
      if (__brlock_array[i][j].y != 6) {
//#line  18
        printf("At index [%d][%d] I found { %d, %d }\n", i, j, __brlock_array[i][j].x,
               __brlock_array[i][j].y);
//#line  20
        exit(1);
      }
//#line  15
      j ++;
    }
//#line  14
    i ++;
  }
//#line  24
  return (0);
}
}
