/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  9 "init22.c"
struct bar {
   int x ;
};
//#line  12 "init22.c"
struct foo {
   struct bar b ;
   int y ;
};
//#line  17
extern int rand(void) ;
//#line  19 "init22.c"
int main(void) 
{ 
  int t ;
  int tmp ;
  struct foo f ;
  int tmp___0 ;

  {
//#line  20
  tmp = rand();
//#line  20
  t = tmp;
//#line  21
  if (t) {
//#line  21
    tmp___0 = 2;
  } else {
//#line  21
    tmp___0 = 3;
  }
//#line  21
  f.b.x = tmp___0;
//#line  21
  f.y = 42;
//#line  27
  return (0);
}
}
