/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "init8.c"
struct pci_device_info {
   unsigned short device ;
   unsigned short seen ;
   char const   *name ;
};
//#line  7 "init8.c"
struct pci_device_info __devices_0000[]  __attribute__((__section__(".data.init")))  = { };
