/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "init18.c"
struct foo {
   int a ;
   int b ;
};
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  8 "init18.c"
static struct foo foos[5]  = {      {1, 0}, 
        {0, 0}, 
        {3, 4}, 
        {0, 0}, 
        {0, 0}};
//#line  16 "init18.c"
int main(void) 
{ 


  {
//#line  17
  printf("sizeof foos = %d.\n", sizeof(foos));
//#line  19
  if (sizeof(foos) != 5UL * sizeof(struct foo )) {
//#line  19
    printf("Error %d\n", 1);
//#line  19
    exit(1);
  }
//#line  20
  if (foos[2].b != 4) {
//#line  20
    printf("Error %d\n", 2);
//#line  20
    exit(2);
  }
//#line  21
  if (foos[4].b != 0) {
//#line  21
    printf("Error %d\n", 3);
//#line  21
    exit(3);
  }
//#line  23
  return (0);
}
}
