/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "init12.c"
struct empty {

};
//#line  5 "init12.c"
struct something {
   int spacer ;
   struct empty foo ;
   int bar ;
};
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  11 "init12.c"
struct something X  =    {0, {}, 1};
//#line  17 "init12.c"
int main(void) 
{ 


  {
//#line  18
  if (X.bar != 1) {
//#line  18
    printf("Error %d\n", 1);
//#line  18
    exit(1);
  }
//#line  19
  if (X.spacer != 0) {
//#line  19
    printf("Error %d\n", 2);
//#line  19
    exit(2);
  }
//#line  21
  printf("Success\n");
//#line  21
  exit(0);
}
}
