/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  5 "init20.c"
struct __anonstruct_str2_109580352 {
   int b ;
};
//#line  5 "init20.c"
typedef struct __anonstruct_str2_109580352 str2;
//#line  9 "init20.c"
struct __anonstruct_str4_773697287 {
   int c ;
   int d ;
};
//#line  9 "init20.c"
typedef struct __anonstruct_str4_773697287 str4;
//#line  14 "init20.c"
union u {
   str2 m1 ;
   str4 m2 ;
};
//#line  14 "init20.c"
struct __anonstruct_str3_967505542 {
   int a ;
   union u u ;
};
//#line  14 "init20.c"
typedef struct __anonstruct_str3_967505542 str3;
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  24 "init20.c"
int ( __attribute__((__noinline__)) scrambleTheStack)(int x ) 
{ 
  char junk[256] ;
  int i ;
  int tmp ;

  {
//#line  27
  i = 0;
//#line  28
  while (i < 256) {
//#line  28
    tmp = i;
//#line  28
    i ++;
//#line  28
    junk[tmp] = (char)-86;
  }
//#line  29
  return ((int )junk[x]);
}
}
//#line  36 "init20.c"
void ( __attribute__((__noinline__)) test)(void) 
{ 
  str3 z ;

  {
//#line  38
  z.a = 0;
//#line  38
  z.u.m2.c = 0;
//#line  38
  z.u.m2.d = 0;
//#line  39
  printf("z.u.m2.d = 0x%x\n", z.u.m2.d);
//#line  40
  if (z.u.m2.d != 0) {
//#line  40
    printf("Error %d\n", 2);
//#line  40
    exit(2);
  }
//#line  41
  return;
}
}
//#line  44 "init20.c"
int main(void) 
{ 


  {
//#line  46
  scrambleTheStack(200);
//#line  47
  test();
//#line  48
  return (0);
}
}
