/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "init9.c"
static unsigned char a[61440 >> 12]  = 
//#line  3 "init9.c"
  {      (unsigned char)0,      (unsigned char)5,      (unsigned char)3,      (unsigned char)0, 
        (unsigned char)2,      (unsigned char)0,      (unsigned char)4,      (unsigned char)0, 
        (unsigned char)1,      (unsigned char)0,      (unsigned char)7,      (unsigned char)0, 
        (unsigned char)6};
//#line  14 "init9.c"
int main(void) 
{ 


  {
//#line  15
  if ((int )a[8] != 1) {
//#line  15
    printf("Error %d\n", 1);
//#line  15
    exit(1);
  }
//#line  16
  if ((int )a[4] != 2) {
//#line  16
    printf("Error %d\n", 2);
//#line  16
    exit(2);
  }
//#line  17
  if ((int )a[2] != 3) {
//#line  17
    printf("Error %d\n", 3);
//#line  17
    exit(3);
  }
//#line  18
  if ((int )a[6] != 4) {
//#line  18
    printf("Error %d\n", 4);
//#line  18
    exit(4);
  }
//#line  19
  if ((int )a[1] != 5) {
//#line  19
    printf("Error %d\n", 5);
//#line  19
    exit(5);
  }
//#line  20
  if ((int )a[12] != 6) {
//#line  20
    printf("Error %d\n", 6);
//#line  20
    exit(6);
  }
//#line  21
  if ((int )a[10] != 7) {
//#line  21
    printf("Error %d\n", 7);
//#line  21
    exit(7);
  }
//#line  23
  if ((int )a[3] != 0) {
//#line  23
    printf("Error %d\n", 8);
//#line  23
    exit(8);
  }
//#line  24
  if ((int )a[0] != 0) {
//#line  24
    printf("Error %d\n", 9);
//#line  24
    exit(9);
  }
//#line  25
  if ((int )a[5] != 0) {
//#line  25
    printf("Error %d\n", 10);
//#line  25
    exit(10);
  }
//#line  26
  if ((int )a[7] != 0) {
//#line  26
    printf("Error %d\n", 11);
//#line  26
    exit(11);
  }
//#line  27
  if ((int )a[9] != 0) {
//#line  27
    printf("Error %d\n", 12);
//#line  27
    exit(12);
  }
//#line  28
  if ((int )a[11] != 0) {
//#line  28
    printf("Error %d\n", 13);
//#line  28
    exit(13);
  }
//#line  29
  if ((int )a[13] != 0) {
//#line  29
    printf("Error %d\n", 14);
//#line  29
    exit(14);
  }
//#line  30
  if ((int )a[14] != 0) {
//#line  30
    printf("Error %d\n", 15);
//#line  30
    exit(15);
  }
//#line  31
  if ((int )a[15] != 0) {
//#line  31
    printf("Error %d\n", 16);
//#line  31
    exit(16);
  }
//#line  33
  printf("Success\n");
//#line  33
  exit(0);
}
}
