/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  6 "init10.c"
struct foo {
   int other ;
   int tint ;
};
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  6 "init10.c"
struct foo x  =    {0, 5};
//#line  12 "init10.c"
int main(void) 
{ 


  {
//#line  13
  if (x.tint != 5) {
//#line  13
    printf("Error %d\n", 1);
//#line  13
    exit(1);
  }
//#line  14
  if (x.other != 0) {
//#line  14
    printf("Error %d\n", 2);
//#line  14
    exit(2);
  }
//#line  16
  printf("Success\n");
//#line  16
  exit(0);
}
}
