/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  5 "init16.c"
int x  =    1;
//#line  7 "init16.c"
int array[8]  ;
//#line  9 "init16.c"
int main(void) 
{ 


  {
//#line  10
  return (x - 1);
}
}
