/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "init1.c"
struct __anonstruct_s1_773697287 {
   int *f1 ;
   int *f2 ;
};
//#line  3 "init1.c"
struct __anonstruct_s2_109580352 {
   int *f3 ;
};
//#line  3 "init1.c"
struct __anonstruct_memory_377622428 {
   struct __anonstruct_s1_773697287 s1 ;
   struct __anonstruct_s2_109580352 s2 ;
};
//#line  1
extern void exit(int  ) ;
//#line  3 "init1.c"
struct __anonstruct_memory_377622428 memory[10]  = {      {{(int *)1, (int *)0}, {(int *)0}}};
//#line  13 "init1.c"
int main(void) 
{ 


  {
//#line  14
  if ((unsigned long )memory[0].s1.f1 != (unsigned long )((int *)1)) {
//#line  15
    exit(1);
  }
//#line  16
  exit(0);
}
}
