/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "init2.c"
extern void printf(char *  , ...) ;
//#line  5 "init2.c"
int tickadj1  =    5;
//#line  6 "init2.c"
int tickadj2  =    1;
//#line  8 "init2.c"
int main(void) 
{ 


  {
//#line  9
  if (tickadj1 != 5) {
//#line  9
    printf((char *)"Error %d\n", 1);
//#line  9
    return (1);
  }
//#line  10
  if (tickadj2 != 1) {
//#line  10
    printf((char *)"Error %d\n", 2);
//#line  10
    return (2);
  }
//#line  12
  return (0);
}
}
