/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "init21.c"
struct snd_usb_audio_quirk ;
//#line  4 "init21.c"
typedef struct snd_usb_audio_quirk snd_usb_audio_quirk_t;
//#line  5
struct snd_usb_midi_endpoint_info ;
//#line  5 "init21.c"
typedef struct snd_usb_midi_endpoint_info snd_usb_midi_endpoint_info_t;
//#line  80 "init21.c"
struct snd_usb_audio_quirk {
   char const   *vendor_name ;
   char const   *product_name ;
   short ifnum ;
   short type ;
   void const   *data ;
};
//#line  88 "init21.c"
struct snd_usb_midi_endpoint_info {
   char out_ep ;
   char out_interval ;
   char in_ep ;
   char in_interval ;
   short out_cables ;
   short in_cables ;
};
//#line  99 "init21.c"
struct usb_device_id {
   short match_flags ;
   short idVendor ;
   short idProduct ;
   short bcdDevice_lo ;
   short bcdDevice_hi ;
   char bDeviceClass ;
   char bDeviceSubClass ;
   char bDeviceProtocol ;
   char bInterfaceClass ;
   char bInterfaceSubClass ;
   char bInterfaceProtocol ;
   unsigned long driver_info ;
};
//#line  123 "init21.c"
struct audioformat {
   int format ;
   unsigned int channels ;
   unsigned int fmt_type ;
   unsigned int frame_size ;
   int iface ;
   unsigned char altsetting ;
   unsigned char altset_idx ;
   unsigned char attributes ;
   unsigned char endpoint ;
   unsigned char ep_attr ;
   unsigned int maxpacksize ;
   unsigned int rates ;
   unsigned int rate_min ;
   unsigned int rate_max ;
   unsigned int nr_rates ;
   unsigned int *rate_table ;
};
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  143 "init21.c"
static struct snd_usb_audio_quirk  const  __constr_expr_0  =    {"Yamaha", "UX256", (short)-1, (short)1, (void const   *)0};
//#line  143 "init21.c"
static struct audioformat  const  __constr_expr_3  = 
//#line  143
     {2, 4U, 0U, 0U, 0, (unsigned char)1, (unsigned char)1, (unsigned char)0, (unsigned char)1,
    (unsigned char)9, 0U, (unsigned int )(1 << 30), 44100U, 44100U, 0U, (unsigned int *)0};
//#line  143 "init21.c"
static struct audioformat  const  __constr_expr_4  = 
//#line  143
     {2, 2U, 0U, 0U, 1, (unsigned char)1, (unsigned char)1, (unsigned char)128, (unsigned char)129,
    (unsigned char)5, 0U, (unsigned int )(1 << 30), 44100U, 44100U, 0U, (unsigned int *)0};
//#line  143 "init21.c"
static struct snd_usb_midi_endpoint_info  const  __constr_expr_5  =    {(char)0, (char)0, (char)0, (char)0, (short)7, (short)7};
//#line  143 "init21.c"
static snd_usb_audio_quirk_t const   __constr_expr_2[4]  = {      {(char const   *)0, (char const   *)0, (short)0, (short)11, (void const   *)(& __constr_expr_3)}, 
        {(char const   *)0,
      (char const   *)0, (short)1, (short)11, (void const   *)(& __constr_expr_4)}, 
        {(char const   *)0,
      (char const   *)0, (short)2, (short)3, (void const   *)(& __constr_expr_5)}, 
        {(char const   *)0,
      (char const   *)0, (short)-1, (short)0, (void const   *)0}};
//#line  143 "init21.c"
static struct snd_usb_audio_quirk  const  __constr_expr_1  =    {"Roland", "UA-100", (short)-1, (short)1, (void const   *)(__constr_expr_2)};
//#line  143 "init21.c"
static struct usb_device_id usb_audio_ids[3]  = {      {(short)3, (short)1177, (short)4096, (short)0, (short)0, (char)0, (char)0, (char)0,
      (char)0, (char)0, (char)0, (unsigned long )(& __constr_expr_0)}, 
        {(short)3, (short)1410, (short)0, (short)0, (short)0, (char)0, (char)0, (char)0,
      (char)0, (char)0, (char)0, (unsigned long )(& __constr_expr_1)}, 
        {(short)0, (short)0, (short)0, (short)0, (short)0, (char)0, (char)0, (char)0,
      (char)0, (char)0, (char)0, 0UL}};
//#line  217 "init21.c"
int main(void) 
{ 
  snd_usb_audio_quirk_t *driver_info ;

  {
//#line  220
  driver_info = (snd_usb_audio_quirk_t *)usb_audio_ids[1].driver_info;
//#line  222
  if ((int )((snd_usb_midi_endpoint_info_t *)((snd_usb_audio_quirk_t *)driver_info->data + 2)->data)->out_cables != 7) {
//#line  222
    printf("Error %d\n", 3);
//#line  222
    exit(3);
  }
//#line  223
  if ((int )((snd_usb_audio_quirk_t *)driver_info->data + 3)->ifnum != -1) {
//#line  224
    printf("Error %d\n", 4);
//#line  224
    exit(4);
  }
//#line  226
  printf("Success\n");
//#line  226
  exit(0);
}
}
