/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "init19.c"
struct __anonstruct_addr6_788510206 {
   double d ;
   int x ;
};
//#line  1 "init19.c"
union __anonunion_u_300869476 {
   int addr ;
   struct __anonstruct_addr6_788510206 addr6 ;
};
//#line  1 "init19.c"
struct tTimNetAddr {
   int isIPv4 ;
   union __anonunion_u_300869476 u ;
};
//#line  1 "init19.c"
typedef struct tTimNetAddr tTimNetAddr;
//#line  10 "init19.c"
tTimNetAddr isisPolChangePrefixV6  =    {0, {.addr6 = {0.0, 5}}};
//#line  18 "init19.c"
int main(void) 
{ 


  {
//#line  19
  return (isisPolChangePrefixV6.u.addr6.x != 5);
}
}
