/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  2 "init3.c"
struct hw_interrupt_type {
   char const   *typename ;
   void (*startup)(unsigned int irq ) ;
   void (*shutdown)(unsigned int irq ) ;
   void (*handle)(unsigned int irq ) ;
   void (*enable)(unsigned int irq ) ;
   void (*disable)(unsigned int irq ) ;
};
//#line  13 "init3.c"
struct irqaction {
   void (*handler)(int  , void * ) ;
   unsigned long flags ;
   unsigned long mask ;
   char const   *name ;
   void *dev_id ;
   struct irqaction *next ;
};
//#line  22 "init3.c"
struct __anonstruct_irq_desc_t_198717013 {
   unsigned int status ;
   struct hw_interrupt_type *handler ;
   struct irqaction *action ;
   unsigned int depth ;
};
//#line  22 "init3.c"
typedef struct __anonstruct_irq_desc_t_198717013 irq_desc_t;
//#line  11 "init3.c"
struct hw_interrupt_type no_irq_type  ;
//#line  30 "init3.c"
irq_desc_t irq_desc[224]  = 
//#line  30
  {      {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}, 
        {0U, & no_irq_type, (struct irqaction *)0, 0U}};
//#line  32
extern void printf(char *  , ...) ;
//#line  35 "init3.c"
int main(void) 
{ 


  {
//#line  37
  if (sizeof(irq_desc) / sizeof(irq_desc[0]) != 224UL) {
//#line  37
    printf((char *)"Error %d\n", 1);
//#line  37
    return (1);
  }
//#line  39
  if ((unsigned long )irq_desc[0].handler != (unsigned long )(& no_irq_type)) {
//#line  39
    printf((char *)"Error %d\n", 2);
//#line  39
    return (2);
  }
//#line  41
  if ((unsigned long )irq_desc[112].handler != (unsigned long )(& no_irq_type)) {
//#line  41
    printf((char *)"Error %d\n", 2);
//#line  41
    return (2);
  }
//#line  43
  if ((unsigned long )irq_desc[223].handler != (unsigned long )(& no_irq_type)) {
//#line  43
    printf((char *)"Error %d\n", 2);
//#line  43
    return (2);
  }
//#line  45
  printf((char *)"Success\n");
//#line  46
  return (0);
}
}
