/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "init13.c"
struct __anonstruct_T1_476363767 {
   char *key ;
   char *value ;
};
//#line  4 "init13.c"
typedef struct __anonstruct_T1_476363767 T1;
//#line  10 "init13.c"
struct __anonstruct_T3_938603720 {
   long type ;
   char *value ;
};
//#line  10 "init13.c"
typedef struct __anonstruct_T3_938603720 T3;
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  16 "init13.c"
static T3 __constr_expr_0  =    {1L, (char *)1};
//#line  16 "init13.c"
T1 a[1]  = {      {(char *)"", (char *)(& __constr_expr_0)}};
//#line  25 "init13.c"
int main(void) 
{ 
  T3 *t3 ;

  {
//#line  28
  if (sizeof(a) != sizeof(T1 )) {
//#line  28
    printf("Error %d\n", 1);
//#line  28
    exit(1);
  }
//#line  30
  if (*(a[0].key + 0)) {
//#line  30
    printf("Error %d\n", 2);
//#line  30
    exit(2);
  }
//#line  32
  t3 = (T3 *)a[0].value;
//#line  33
  if (t3->type != 1L) {
//#line  33
    printf("Error %d\n", 3);
//#line  33
    exit(3);
  }
//#line  34
  if ((unsigned long )t3->value != 1UL) {
//#line  34
    printf("Error %d\n", 4);
//#line  34
    exit(4);
  }
//#line  37
  printf("Success\n");
//#line  37
  exit(0);
}
}
