/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  2 "init5.c"
struct __anonstruct_spinlock_t_109580352 {
   int gcc_is_buggy ;
};
//#line  2 "init5.c"
typedef struct __anonstruct_spinlock_t_109580352 spinlock_t;
//#line  6 "init5.c"
struct list_head {
   struct list_head *next ;
   struct list_head *prev ;
};
//#line  10 "init5.c"
struct __wait_queue_head {
   spinlock_t lock ;
   struct list_head task_list ;
};
//#line  14 "init5.c"
typedef struct __wait_queue_head wait_queue_head_t;
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  17 "init5.c"
static wait_queue_head_t reiserfs_commit_thread_done  =    {{0}, {& reiserfs_commit_thread_done.task_list, & reiserfs_commit_thread_done.task_list}};
//#line  24 "init5.c"
int main(void) 
{ 


  {
//#line  25
  if ((unsigned long )reiserfs_commit_thread_done.task_list.next != (unsigned long )(& reiserfs_commit_thread_done.task_list)) {
//#line  26
    printf("Error %d\n", 1);
//#line  26
    exit(1);
  }
//#line  28
  if ((unsigned long )reiserfs_commit_thread_done.task_list.prev != (unsigned long )(& reiserfs_commit_thread_done.task_list)) {
//#line  29
    printf("Error %d\n", 2);
//#line  29
    exit(2);
  }
//#line  31
  printf("Success\n");
//#line  31
  exit(0);
}
}
