/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  6 "init14.c"
int main(void) 
{ 
  int __constr_expr_0[4] ;
  int __constr_expr_1[4] ;

  {
//#line  7
  __constr_expr_0[0] = 1;
//#line  7
  __constr_expr_0[1] = 2;
//#line  7
  __constr_expr_0[2] = 3;
//#line  7
  __constr_expr_0[3] = 4;
//#line  7
  if (__constr_expr_0[1] != 2) {
//#line  7
    printf("Error %d\n", 1);
//#line  7
    exit(1);
  }
//#line  9
  __constr_expr_1[0] = 1;
//#line  9
  __constr_expr_1[1] = 2;
//#line  9
  __constr_expr_1[2] = 3;
//#line  9
  __constr_expr_1[3] = 4;
//#line  9
  __constr_expr_1[1] = 15;
//#line  11
  printf("Success\n");
//#line  11
  exit(0);
}
}
