/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "init6.c"
struct S {
   int x ;
};
//#line  3 "init6.c"
struct A {
   struct S s ;
   int a[4] ;
   int  : 8 ;
   int *p ;
};
//#line  12 "init6.c"
struct B {
   struct A a1 ;
   struct A a2 ;
   struct A a3 ;
   struct A a4 ;
   struct A a5 ;
};
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  10 "init6.c"
struct S s  =    {8};
//#line  20 "init6.c"
struct A a  =    {{1}, {2, 3, 4, 5}, (int *)6};
//#line  23 "init6.c"
int main(void) 
{ 
  struct B b ;
  unsigned int tmp ;
  struct B b1 ;
  struct B b2 ;

  {
//#line  24
  b.a1.s.x = 0;
//#line  24
  b.a1.a[0] = 0;
//#line  24
  b.a1.a[1] = 0;
//#line  24
  b.a1.a[2] = 0;
//#line  24
  b.a1.a[3] = 0;
//#line  24
  b.a1.p = (int *)0;
//#line  24
  b.a2.s.x = 5;
//#line  24
  b.a2.a[0] = 0;
//#line  24
  b.a2.a[1] = 0;
//#line  24
  b.a2.a[2] = 0;
//#line  24
  b.a2.a[3] = 0;
//#line  24
  b.a2.p = (int *)0;
//#line  24
  b.a3.s = s;
//#line  24
  b.a3.a[0] = 0;
//#line  24
  b.a3.a[1] = 0;
//#line  24
  b.a3.a[2] = 0;
//#line  24
  b.a3.a[3] = 0;
//#line  24
  b.a3.p = (int *)0;
//#line  24
  b.a4.s.x = 6;
//#line  24
  b.a4.a[0] = 0;
//#line  24
  tmp = 1U;
//#line  24
  while (! (tmp >= 4U)) {
//#line  24
    b.a4.a[tmp] = 0;
//#line  24
    tmp ++;
  }
//#line  24
  b.a4.p = (int *)0;
//#line  24
  b.a5 = a;
//#line  30
  if (s.x != 8) {
//#line  30
    printf("Error %d\n", 2);
//#line  30
    exit(2);
  }
//#line  32
  if (a.s.x != 1) {
//#line  32
    printf("Error %d\n", 3);
//#line  32
    exit(3);
  } else
//#line  32
  if (a.a[1] != 3) {
//#line  32
    printf("Error %d\n", 3);
//#line  32
    exit(3);
  } else
//#line  32
  if ((unsigned long )a.p != 6UL) {
//#line  32
    printf("Error %d\n", 3);
//#line  32
    exit(3);
  }
//#line  34
  if (b.a2.s.x != 5) {
//#line  34
    printf("Error %d\n", 1);
//#line  34
    exit(1);
  }
//#line  36
  if (b.a2.a[2] != 0) {
//#line  36
    printf("Error %d\n", 4);
//#line  36
    exit(4);
  }
//#line  38
  if (b.a3.s.x != s.x) {
//#line  38
    printf("Error %d\n", 5);
//#line  38
    exit(5);
  }
//#line  40
  if (b.a4.s.x != 6) {
//#line  40
    printf("Error %d\n", 6);
//#line  40
    exit(6);
  }
//#line  42
  if (b.a5.a[2] != a.a[2]) {
//#line  42
    printf("Error %d\n", 7);
//#line  42
    exit(7);
  }
//#line  45
  b1.a1 = b.a4;
//#line  45
  b1.a2 = a;
//#line  45
  b1.a3.s.x = 0;
//#line  45
  b1.a3.a[0] = 0;
//#line  45
  b1.a3.a[1] = 0;
//#line  45
  b1.a3.a[2] = 0;
//#line  45
  b1.a3.a[3] = 0;
//#line  45
  b1.a3.p = (int *)0;
//#line  45
  b1.a4.s.x = 0;
//#line  45
  b1.a4.a[0] = 0;
//#line  45
  b1.a4.a[1] = 0;
//#line  45
  b1.a4.a[2] = 0;
//#line  45
  b1.a4.a[3] = 0;
//#line  45
  b1.a4.p = (int *)0;
//#line  45
  b1.a5.s.x = 0;
//#line  45
  b1.a5.a[0] = 0;
//#line  45
  b1.a5.a[1] = 0;
//#line  45
  b1.a5.a[2] = 0;
//#line  45
  b1.a5.a[3] = 0;
//#line  45
  b1.a5.p = (int *)0;
//#line  48
  if (b1.a2.a[2] != a.a[2]) {
//#line  48
    printf("Error %d\n", 11);
//#line  48
    exit(11);
  }
//#line  50
  if (b1.a1.s.x != b.a4.s.x) {
//#line  50
    printf("Error %d\n", 12);
//#line  50
    exit(12);
  }
//#line  55
  b2.a1.s.x = 15;
//#line  55
  b2.a1.a[0] = 16;
//#line  55
  b2.a1.a[1] = 17;
//#line  55
  b2.a1.a[2] = 18;
//#line  55
  b2.a1.a[3] = 19;
//#line  55
  b2.a1.p = (int *)20;
//#line  55
  b2.a2.s.x = 21;
//#line  55
  b2.a2.a[0] = 22;
//#line  55
  b2.a2.a[1] = 23;
//#line  55
  b2.a2.a[2] = 7;
//#line  55
  b2.a2.a[3] = 8;
//#line  55
  b2.a2.p = (int *)9;
//#line  55
  b2.a3.s.x = 10;
//#line  55
  b2.a3.a[0] = 11;
//#line  55
  b2.a3.a[1] = 12;
//#line  55
  b2.a3.a[2] = 13;
//#line  55
  b2.a3.a[3] = 14;
//#line  55
  b2.a3.p = (int *)8;
//#line  55
  b2.a4.s.x = 0;
//#line  55
  b2.a4.a[0] = 0;
//#line  55
  b2.a4.a[1] = 0;
//#line  55
  b2.a4.a[2] = 0;
//#line  55
  b2.a4.a[3] = 0;
//#line  55
  b2.a4.p = (int *)0;
//#line  55
  b2.a5.s.x = 0;
//#line  55
  b2.a5.a[0] = 0;
//#line  55
  b2.a5.a[1] = 0;
//#line  55
  b2.a5.a[2] = 0;
//#line  55
  b2.a5.a[3] = 0;
//#line  55
  b2.a5.p = (int *)0;
//#line  62
  if (b2.a2.a[0] != 22) {
//#line  62
    printf("Error %d\n", 20);
//#line  62
    exit(20);
  }
//#line  63
  if (b2.a2.a[1] != 23) {
//#line  63
    printf("Error %d\n", 21);
//#line  63
    exit(21);
  }
//#line  64
  if (b2.a2.a[2] != 7) {
//#line  64
    printf("Error %d\n", 22);
//#line  64
    exit(22);
  }
//#line  65
  if (b2.a3.s.x != 10) {
//#line  65
    printf("Error %d\n", 23);
//#line  65
    exit(23);
  }
//#line  66
  if (b2.a3.a[0] != 11) {
//#line  66
    printf("Error %d\n", 24);
//#line  66
    exit(24);
  }
//#line  67
  if (b2.a3.a[1] != 12) {
//#line  67
    printf("Error %d\n", 25);
//#line  67
    exit(25);
  }
//#line  68
  if (b2.a3.a[2] != 13) {
//#line  68
    printf("Error %d\n", 26);
//#line  68
    exit(26);
  }
//#line  69
  if (b2.a3.a[3] != 14) {
//#line  69
    printf("Error %d\n", 27);
//#line  69
    exit(27);
  }
//#line  70
  if ((unsigned long )b2.a3.p != 8UL) {
//#line  70
    printf("Error %d\n", 28);
//#line  70
    exit(28);
  }
//#line  72
  if (b2.a1.s.x != 15) {
//#line  72
    printf("Error %d\n", 29);
//#line  72
    exit(29);
  }
//#line  74
  if (b2.a1.a[0] != 16) {
//#line  74
    printf("Error %d\n", 30);
//#line  74
    exit(30);
  }
//#line  75
  if (b2.a1.a[1] != 17) {
//#line  75
    printf("Error %d\n", 31);
//#line  75
    exit(31);
  }
//#line  76
  if (b2.a1.a[2] != 18) {
//#line  76
    printf("Error %d\n", 32);
//#line  76
    exit(32);
  }
//#line  77
  if (b2.a1.a[3] != 19) {
//#line  77
    printf("Error %d\n", 33);
//#line  77
    exit(33);
  }
//#line  79
  if ((unsigned long )b2.a1.p != 20UL) {
//#line  79
    printf("Error %d\n", 34);
//#line  79
    exit(34);
  }
//#line  81
  if (b2.a2.s.x != 21) {
//#line  81
    printf("Error %d\n", 35);
//#line  81
    exit(35);
  }
//#line  84
  printf("Success\n");
//#line  84
  exit(0);
}
}
