/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "inline3.c"
struct __anonstruct_link_1046794635 {
   char _unused[16] ;
   int _dxd[4] ;
   char _inline[128] ;
   char _inline_ea[128] ;
};
//#line  4 "inline3.c"
struct __anonstruct_link_1046794635 link  ;
