/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  31 "/usr/include/x86_64-linux-gnu/bits/setjmp.h"
typedef long __jmp_buf[8];
//#line  27 "/usr/include/x86_64-linux-gnu/bits/sigset.h"
struct __anonstruct___sigset_t_973126068 {
   unsigned long __val[1024UL / (8UL * sizeof(unsigned long ))] ;
};
//#line  27 "/usr/include/x86_64-linux-gnu/bits/sigset.h"
typedef struct __anonstruct___sigset_t_973126068 __sigset_t;
//#line  34 "/usr/include/setjmp.h"
struct __jmp_buf_tag {
   __jmp_buf __jmpbuf ;
   int __mask_was_saved ;
   __sigset_t __saved_mask ;
};
//#line  48 "/usr/include/setjmp.h"
typedef struct __jmp_buf_tag jmp_buf[1];
//#line  63
extern  __attribute__((__nothrow__)) int _setjmp(struct __jmp_buf_tag *__env ) ;
//#line  74
extern  __attribute__((__nothrow__, __noreturn__)) void longjmp(struct __jmp_buf_tag *__env ,
                                                                int __val ) ;
//#line  362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  13 "jmp_buf.c"
jmp_buf env  ;
//#line  22 "jmp_buf.c"
int main(void) 
{ 
  int status ;

  {
//#line  26
  status = _setjmp((struct __jmp_buf_tag *)(& env));
//#line  26
  if (status) {
//#line  27
    printf((char const   */* __restrict  */)"Returned from longjmp, status = %d\n",
           status);
//#line  28
    if (status != 55) {
//#line  29
      printf((char const   */* __restrict  */)"Wrong status value!\n");
//#line  29
      return (1);
    }
  } else {
//#line  32
    printf((char const   */* __restrict  */)"Saved state via setjmp, status = 0.\n");
  }
//#line  34
  if (status == 0) {
//#line  35
    printf((char const   */* __restrict  */)"Long-Jumping with status argument 55.\n");
//#line  36
    longjmp((struct __jmp_buf_tag *)(& env), 55);
  }
//#line  38
  printf((char const   */* __restrict  */)"success\n");
//#line  39
  return (0);
}
}
