/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  12 "testharness.h"
extern void exit(int  ) ;
//#line  2 "label4b.c"
extern void abort(void) ;
//#line  5 "label4b.c"
int expect_do1  =    1;
//#line  5 "label4b.c"
int expect_do2  =    2;
//#line  10
static int doit(int x ) ;
//#line  10 "label4b.c"
static int jtab_init  =    0;
//#line  11 "label4b.c"
static void *jtab[2]  ;
//#line  7 "label4b.c"
static int doit(int x ) 
{ 


  {
//#line  13
  if (! jtab_init) {
//#line  14
    jtab[0] = && lbl1___0;
//#line  15
    jtab[1] = && lbl2___0;
//#line  16
    jtab_init = 1;
  }
//#line  18
  goto *(jtab[x]);
  lbl1___0: 
//#line  20
  return (1);
  lbl2___0: 
//#line  22
  return (2);
}
}
//#line  25 "label4b.c"
static void do1(void) 
{ 
  int tmp ;

  {
//#line  26
  tmp = doit(0);
//#line  26
  if (tmp != expect_do1) {
//#line  27
    abort();
  }
//#line  28
  return;
}
}
//#line  30 "label4b.c"
static void do2(void) 
{ 
  int tmp ;

  {
//#line  31
  tmp = doit(1);
//#line  31
  if (tmp != expect_do2) {
//#line  32
    abort();
  }
//#line  33
  return;
}
}
//#line  35 "label4b.c"
int main(void) 
{ 


  {
//#line  37
  do1();
//#line  38
  do2();
//#line  40
  exit(0);
}
}
