/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "label9.c"
int main(void) 
{ 


  {
  {
//#line  2
  while (1) {
    while_continue: /* CIL Label */ ;

//#line  4
    goto while_0_break;
  }
  while_break: /* CIL Label */ ;
  }
  while_0_break: ;
//#line  3
  return (0);
}
}
