/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "label8.c"
int main(void) 
{ 


  {
//#line  2
  goto __Cont;
//#line  3
  while (1) {
//#line  3
    goto __Cont___0;
    __Cont___0: /* CIL Label */ ;
  }
  __Cont: 
//#line  5
  return (0);
}
}
