/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "label7.c"
int main(void) 
{ 
  int x ;

  {
//#line  4
  if (x) {
//#line  4
    goto _L___0;
  } else {
//#line  4
    x ++;
//#line  4
    if (x) {
      _L___0: /* CIL Label */ 
//#line  4
      x ++;
//#line  4
      x ++;
//#line  4
      x ++;
//#line  4
      x ++;
//#line  4
      x ++;
//#line  4
      x ++;
    }
  }
//#line  5
  return (0);
}
}
