/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "label3b.c"
int main(void) 
{ 
  static void *array[3]  = {&& L1, && L2, && L3};
  int acc ;

  {
//#line  6
  acc = 0;
  L1: 
//#line  8
  acc ++;
//#line  8
  goto *(array[1]);
  L2: 
//#line  9
  acc += 2;
//#line  9
  goto *(array[2]);
  L3: 
//#line  10
  acc += 3;
//#line  12
  return (acc - 6);
}
}
