/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  21 "label1.c"
int thearray[10]  = 
//#line  21 "label1.c"
  {      1,      3,      5,      7, 
        9,      11,      13,      15, 
        17,      21};
//#line  23 "label1.c"
int main(void) 
{ 
  int res ;
  int _SEARCH_target ;
  int *_SEARCH_array ;
  int i ;
  int value ;
  int max ;
  int _SEARCH_target___0 ;
  int *_SEARCH_array___0 ;
  int i___0 ;
  int value___0 ;
  int max___0 ;

  {
//#line  27
  _SEARCH_target = 7;
//#line  27
  _SEARCH_array = thearray;
//#line  27
  max = (int )(sizeof(thearray) / sizeof(thearray[0]));
  retry___0: 
//#line  27
  i = 0;
//#line  27
  while (i < max) {
//#line  27
    if (*(_SEARCH_array + i) == _SEARCH_target) {
//#line  27
      value = i;
//#line  27
      goto found___0;
    }
//#line  27
    i ++;
  }
//#line  27
  goto found___1;
  found___1: 
//#line  27
  _SEARCH_target += 5;
//#line  27
  goto retry___0;
  found___0: 
//#line  27
  _SEARCH_target___0 = 8;
//#line  27
  _SEARCH_array___0 = thearray;
//#line  27
  max___0 = (int )(sizeof(thearray) / sizeof(thearray[0]));
  retry___1: 
//#line  27
  i___0 = 0;
//#line  27
  while (i___0 < max___0) {
//#line  27
    if (*(_SEARCH_array___0 + i___0) == _SEARCH_target___0) {
//#line  27
      value___0 = i___0;
//#line  27
      goto found___2;
    }
//#line  27
    i___0 ++;
  }
//#line  27
  goto found___3;
  found___3: 
//#line  27
  _SEARCH_target___0 += 5;
//#line  27
  goto retry___1;
  found___2: 
//#line  27
  res = -9 + (value + value___0);
//#line  29
  return (res);
}
}
