/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "li.c"
struct foo {
   int x ;
   int *y ;
};
//#line  1 "li.c"
typedef struct foo Foo;
//#line  6 "li.c"
Foo *xlarg(Foo **pargs ) 
{ 
  void *make_me_wild ;

  {
//#line  7
  make_me_wild = (void *)pargs;
//#line  8
  return (*pargs);
}
}
//#line  11 "li.c"
Foo *xeval(Foo *args ) 
{ 
  Foo *expr ;
  Foo *tmp ;

  {
//#line  12
  tmp = xlarg(& args);
//#line  12
  expr = tmp;
//#line  13
  return ((Foo *)0);
}
}
