/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  9 "linux_signal.c"
struct sigaction {
   void (*sa_handler)(int  ) ;
   unsigned long sa_flags ;
   void (*sa_restorer)(void) ;
   long sa_mask ;
};
//#line  16 "linux_signal.c"
struct k_sigaction {
   struct sigaction sa ;
};
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  21 "linux_signal.c"
int main(void) 
{ 
  struct k_sigaction sa ;

  {
//#line  25
  sa.sa.sa_handler = (void (*)(int  ))1;
//#line  27
  printf("Success\n");
//#line  27
  exit(0);
}
}
