/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
//#line  5 "list.c"
struct list {
   void *car ;
   struct list *cdr ;
};
//#line  5 "list.c"
typedef struct list LIST;
//#line  5 "list.c"
typedef struct list *PLIST;
//#line  321 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) long ( __attribute__((__leaf__)) random)(void) ;
//#line  466
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
//#line  362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  11 "list.c"
PLIST prepend(PLIST l , void *el ) 
{ 
  PLIST n ;
  void *tmp ;

  {
//#line  12
  tmp = malloc(sizeof(LIST ));
//#line  12
  n = (PLIST )tmp;
//#line  13
  n->car = el;
//#line  14
  n->cdr = l;
//#line  15
  return (n);
}
}
//#line  19 "list.c"
PLIST append(PLIST l , void *el ) 
{ 
  PLIST parent ;
  PLIST n ;
  void *tmp ;

  {
//#line  20
  parent = (PLIST )0;
//#line  21
  n = l;
//#line  22
  while (n) {
//#line  23
    parent = n;
//#line  24
    n = n->cdr;
  }
//#line  26
  tmp = malloc(sizeof(LIST ));
//#line  26
  n = (PLIST )tmp;
//#line  27
  n->car = el;
//#line  28
  n->cdr = (struct list *)0;
//#line  29
  if (parent) {
//#line  30
    parent->cdr = n;
//#line  31
    return (l);
  } else {
//#line  33
    return (n);
  }
}
}
//#line  38 "list.c"
PLIST insert(PLIST l , void *el , int pos ) 
{ 
  PLIST n ;
  PLIST t ;
  void *tmp ;

  {
//#line  39
  n = l;
//#line  41
  if (l) {
//#line  42
    while (1) {
//#line  42
      if (n->cdr) {
//#line  42
        if (! (pos > 0)) {
//#line  42
          break;
        }
      } else {
//#line  42
        break;
      }
//#line  43
      n = n->cdr;
    }
  }
//#line  46
  tmp = malloc(sizeof(LIST ));
//#line  46
  t = (PLIST )tmp;
//#line  47
  if (! l) {
//#line  48
    t->cdr = (struct list *)((void *)0);
//#line  49
    return (t);
  } else {
//#line  51
    t->cdr = n->cdr;
//#line  52
    n->cdr = t;
//#line  53
    return (l);
  }
}
}
//#line  57 "list.c"
int exists(PLIST l , void *el ) 
{ 


  {
//#line  58
  while (1) {
//#line  58
    if (l) {
//#line  58
      if (! ((unsigned long )l->car != (unsigned long )el)) {
//#line  58
        break;
      }
    } else {
//#line  58
      break;
    }
//#line  59
    l = l->cdr;
  }
//#line  63
  return ((unsigned long )l != (unsigned long )((PLIST )0));
}
}
//#line  66 "list.c"
int length(PLIST l ) 
{ 
  int len ;

  {
//#line  67
  len = 0;
//#line  68
  while (l) {
//#line  69
    len ++;
//#line  70
    l = l->cdr;
  }
//#line  72
  return (len);
}
}
//#line  75 "list.c"
int main(void) 
{ 
  int i ;
  PLIST l ;
  double clk ;
  int sum ;
  int k ;
  long tmp ;
  int tmp___0 ;
  long tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;

  {
//#line  78
  l = (PLIST )((void *)0);
//#line  79
  clk = 0.0;
//#line  80
  sum = 0;
//#line  83
  i = 1;
//#line  83
  while (i < 1000) {
//#line  84
    tmp = random();
//#line  84
    k = (int )(tmp % 1000L);
//#line  85
    tmp___0 = length(l);
//#line  85
    if (tmp___0 & 1) {
//#line  86
      l = insert(l, (void *)k, k % i);
    } else {
//#line  88
      l = append(l, (void *)k);
    }
//#line  83
    i ++;
  }
//#line  91
  i = 0;
//#line  91
  while (i < 10000) {
//#line  92
    tmp___1 = random();
//#line  92
    k = (int )(tmp___1 % 1000L);
//#line  93
    tmp___2 = exists(l, (void *)k);
//#line  93
    if (tmp___2) {
//#line  94
      sum ++;
    }
//#line  91
    i ++;
  }
//#line  97
  tmp___3 = length(l);
//#line  97
  printf((char const   */* __restrict  */)"Ran the test %d times in %8.3lfms. Length is %d. Success %d times.\n",
         i, clk / 1000.0, tmp___3, sizeof(char *), sum);
//#line  100
  return (0);
}
}
