/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "localinit.c"
int main(void) 
{ 
  int x ;
  int i ;

  {
//#line  4
  x = 5;
//#line  5
  x = 42;
//#line  6
  i = x;
//#line  7
  if (i != 42) {
//#line  7
    printf("Error %d\n", 99);
//#line  7
    exit(99);
  }
//#line  9
  printf("Success\n");
//#line  9
  exit(0);
}
}
