/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "logical1.c"
int main(void) 
{ 
  long long x ;
  int i ;

  {
//#line  4
  x = 4294967296LL;
//#line  5
  i = 1;
//#line  6
  if (i && x) {
//#line  6
    printf("Success\n");
//#line  6
    exit(0);
  }
//#line  7
  printf("Error %d\n", 1);
//#line  7
  exit(1);
}
}
