/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "logical2.c"
int main(void) 
{ 
  int x ;
  int keep1 ;
  int keep2 ;
  int keep3 ;
  int tmp ;
  int keep4 ;
  int tmp___0 ;
  int unfold1 ;
  int tmp___1 ;
  int tmp___2 ;
  int unfold2 ;
  int tmp___3 ;

  {
//#line  2
  x = 0;
//#line  3
  keep1 = x && x;
//#line  4
  keep2 = x || x;
//#line  5
  tmp = x;
//#line  5
  x ++;
//#line  5
  keep3 = tmp && x;
//#line  6
  tmp___0 = x;
//#line  6
  x ++;
//#line  6
  keep4 = tmp___0 || x;
//#line  7
  if (x) {
//#line  7
    tmp___1 = x;
//#line  7
    x ++;
//#line  7
    if (tmp___1) {
//#line  7
      tmp___2 = 1;
    } else {
//#line  7
      tmp___2 = 0;
    }
  } else {
//#line  7
    tmp___2 = 0;
  }
//#line  7
  unfold1 = tmp___2;
//#line  8
  if (x) {
//#line  8
    tmp___3 = 1;
  } else {
//#line  8
    x ++;
//#line  8
    if (x) {
//#line  8
      tmp___3 = 1;
    } else {
//#line  8
      tmp___3 = 0;
    }
  }
//#line  8
  unfold2 = tmp___3;
//#line  9
  return (0);
}
}
