/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "logical.c"
int main(void) 
{ 
  int x ;
  int *p ;

  {
//#line  5
  p = (int *)0;
//#line  6
  x = 1;
//#line  7
  if (x) {
//#line  8
    x = 0;
  } else
//#line  7
  if (*p) {
//#line  8
    x = 0;
  }
//#line  10
  if (x) {
//#line  10
    if (*p) {
//#line  11
      printf("Error %d\n", 1);
//#line  11
      exit(1);
    }
  }
//#line  13
  printf("Success\n");
//#line  13
  exit(0);
}
}
