/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "lval1.c"
int main(void) 
{ 
  int a ;
  int b ;
  int *pi ;
  double *pa ;
  double *pb ;

  {
//#line  4
  a = 0;
//#line  4
  b = 10;
//#line  8
  a ++;
//#line  8
  b ++;
//#line  10
  a += b;
//#line  12
  if (a != 12) {
//#line  12
    printf("Error %d\n", 1);
//#line  12
    exit(1);
  } else
//#line  12
  if (b != 11) {
//#line  12
    printf("Error %d\n", 1);
//#line  12
    exit(1);
  }
//#line  14
  a ++;
//#line  14
  b = 5;
//#line  16
  if (a != 13) {
//#line  16
    printf("Error %d\n", 2);
//#line  16
    exit(2);
  } else
//#line  16
  if (b != 5) {
//#line  16
    printf("Error %d\n", 2);
//#line  16
    exit(2);
  }
//#line  18
  pi = & b;
//#line  18
  *pi += 4;
//#line  20
  if (a != 13) {
//#line  20
    printf("Error %d\n", 3);
//#line  20
    exit(3);
  } else
//#line  20
  if (b != 9) {
//#line  20
    printf("Error %d\n", 3);
//#line  20
    exit(3);
  }
//#line  25
  if (a > 12) {
//#line  25
    a += 5;
  } else {
//#line  25
    b += 5;
  }
//#line  27
  if (a != 18) {
//#line  27
    printf("Error %d\n", 4);
//#line  27
    exit(4);
  } else
//#line  27
  if (b != 9) {
//#line  27
    printf("Error %d\n", 4);
//#line  27
    exit(4);
  }
//#line  29
  if (a < 16) {
//#line  29
    b = 7;
  } else {
//#line  29
    a = 7;
  }
//#line  31
  if (a != 7) {
//#line  31
    printf("Error %d\n", 5);
//#line  31
    exit(5);
  } else
//#line  31
  if (b != 9) {
//#line  31
    printf("Error %d\n", 5);
//#line  31
    exit(5);
  }
//#line  33
  if (a < 12) {
//#line  33
    pi = & a;
  } else {
//#line  33
    pi = & b;
  }
//#line  33
  *pi += 4;
//#line  35
  if (a != 11) {
//#line  35
    printf("Error %d\n", 6);
//#line  35
    exit(6);
  } else
//#line  35
  if (b != 9) {
//#line  35
    printf("Error %d\n", 6);
//#line  35
    exit(6);
  }
//#line  40
  pa = (double *)16;
//#line  43
  pb = (double *)8;
//#line  43
  pa += (int )pb;
//#line  45
  if ((unsigned long )((int )pa) != 16UL + 8UL * sizeof(double )) {
//#line  45
    printf("Error %d\n", 7);
//#line  45
    exit(7);
  } else
//#line  45
  if ((int )pb != 8) {
//#line  45
    printf("Error %d\n", 7);
//#line  45
    exit(7);
  }
//#line  47
  pa = (double *)((int )pa + 5);
//#line  49
  if ((unsigned long )((int )pa) != (16UL + 8UL * sizeof(double )) + 5UL) {
//#line  49
    printf("Error %d\n", 8);
//#line  49
    exit(8);
  }
//#line  52
  printf("Success\n");
//#line  52
  exit(0);
//#line  53
  return (0);
}
}
