/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

/* compiler builtin: 
   double __builtin_huge_val(void) ;  */
/* compiler builtin: 
   long double __builtin_huge_vall(void) ;  */
/* compiler builtin: 
   float __builtin_huge_valf(void) ;  */
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  5 "math1.c"
int main(void) 
{ 
  double d ;
  double tmp ;
  double df ;
  float tmp___0 ;
  double dl ;
  long double tmp___1 ;

  {
//#line  6
  tmp = __builtin_huge_val();
//#line  6
  d = tmp;
//#line  9
  tmp___0 = __builtin_huge_valf();
//#line  9
  df = (double )tmp___0;
//#line  10
  tmp___1 = __builtin_huge_vall();
//#line  10
  dl = (double )tmp___1;
//#line  13
  printf("Success\n");
//#line  13
  exit(0);
}
}
