/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
//#line  5 "memcpy1.c"
struct __anonstruct_T1_1047488896 {
   char *f1 ;
   int f2 ;
};
//#line  5 "memcpy1.c"
typedef struct __anonstruct_T1_1047488896 T1;
//#line  12 "testharness.h"
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
//#line  42 "/usr/include/string.h"
extern  __attribute__((__nothrow__)) void *( __attribute__((__nonnull__(1,2), __leaf__)) memcpy)(void * __restrict  __dest ,
                                                                                                 void const   * __restrict  __src ,
                                                                                                 size_t __n ) ;
//#line  466 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
//#line  13 "memcpy1.c"
T1 globarray[5]  ;
//#line  27 "memcpy1.c"
void main(void) 
{ 
  T1 *p ;
  void *tmp ;

  {
//#line  29
  tmp = malloc(8UL * sizeof(T1 ));
//#line  29
  p = (T1 *)tmp;
//#line  42
  memcpy((void */* __restrict  */)p, (void const   */* __restrict  */)(globarray),
         sizeof(globarray));
//#line  63
  exit(0);
}
}
