/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  10 "min.c"
double global  =    5.0;
//#line  12 "min.c"
int main(void) 
{ 
  double res ;
  double _x ;
  double _y___0 ;
  double _x___1 ;
  double _y___1 ;
  double tmp___0 ;
  double tmp___1 ;

  {
//#line  13
  _x = global - (double )1;
//#line  13
  _x___1 = global / (double )2;
//#line  13
  _y___1 = global;
//#line  13
  if (_x___1 < _y___1) {
//#line  13
    tmp___0 = _x___1;
  } else {
//#line  13
    tmp___0 = _y___1;
  }
//#line  13
  _y___0 = tmp___0;
//#line  13
  if (_x < _y___0) {
//#line  13
    tmp___1 = _x;
  } else {
//#line  13
    tmp___1 = _y___0;
  }
//#line  13
  res = tmp___1;
//#line  15
  if (res != 2.5) {
//#line  15
    printf("Error %d\n", 2);
//#line  15
    exit(2);
  }
//#line  16
  printf("Success\n");
//#line  16
  exit(0);
}
}
