/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  7 "msvc1.c"
int bar(void) 
{ 


  {
//#line  8
  return (1);
}
}
//#line  12 "msvc1.c"
int const   *global  =    (int const   *)0;
//#line  15 "msvc1.c"
int main(void) 
{ 


  {
//#line  16
  return (0);
}
}
