/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "msvc5.c"
union __anonunion____missing_field_name_773697287 {
   int SendHandler ;
   int WanSendHandler ;
};
//#line  3 "msvc5.c"
union __anonunion____missing_field_name_773697288 {
   int TransferDataHandler ;
   int WanTransferDataHandler ;
};
//#line  3 "msvc5.c"
struct _NDIS30_MINIPORT_CHARACTERISTICS {
   int MajorNdisVersion ;
   int MinorNdisVersion ;
   int Filler ;
   int Reserved ;
   int CheckForHangHandler ;
   int DisableInterruptHandler ;
   int EnableInterruptHandler ;
   int HaltHandler ;
   int HandleInterruptHandler ;
   int InitializeHandler ;
   int ISRHandler ;
   int QueryInformationHandler ;
   int ReconfigureHandler ;
   int ResetHandler ;
   union __anonunion____missing_field_name_773697287 __annonCompField1 ;
   int SetInformationHandler ;
   union __anonunion____missing_field_name_773697288 __annonCompField2 ;
};
//#line  3 "msvc5.c"
typedef struct _NDIS30_MINIPORT_CHARACTERISTICS NDIS30_MINIPORT_CHARACTERISTICS;
//#line  32 "msvc5.c"
struct _NDIS40_MINIPORT_CHARACTERISTICS {
   NDIS30_MINIPORT_CHARACTERISTICS __annonCompField3 ;
   int ReturnPacketHandler ;
   int SendPacketsHandler ;
   int AllocateCompleteHandler ;
};
//#line  32 "msvc5.c"
typedef struct _NDIS40_MINIPORT_CHARACTERISTICS NDIS40_MINIPORT_CHARACTERISTICS;
//#line  40 "msvc5.c"
struct _NDIS50_MINIPORT_CHARACTERISTICS {
   NDIS40_MINIPORT_CHARACTERISTICS __annonCompField4 ;
   int CoCreateVcHandler ;
   int CoDeleteVcHandler ;
   int CoActivateVcHandler ;
   int CoDeactivateVcHandler ;
   int CoSendPacketsHandler ;
   int CoRequestHandler ;
};
//#line  40 "msvc5.c"
typedef struct _NDIS50_MINIPORT_CHARACTERISTICS NDIS50_MINIPORT_CHARACTERISTICS;
//#line  52 "msvc5.c"
struct _NDIS51_MINIPORT_CHARACTERISTICS {
   NDIS50_MINIPORT_CHARACTERISTICS __annonCompField5 ;
   int CancelSendPacketsHandler ;
   int PnPEventNotifyHandler ;
   int AdapterShutdownHandler ;
   int Reserved1 ;
   int Reserved2 ;
   int Reserved3 ;
   int Reserved4 ;
};
//#line  63 "msvc5.c"
typedef struct _NDIS51_MINIPORT_CHARACTERISTICS NDIS_MINIPORT_CHARACTERISTICS;
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  66 "msvc5.c"
int main(void) 
{ 
  NDIS_MINIPORT_CHARACTERISTICS m ;
  int i ;

  {
//#line  70
  m.__annonCompField5.__annonCompField4.__annonCompField3.MajorNdisVersion = 1;
//#line  71
  m.__annonCompField5.__annonCompField4.__annonCompField3.MinorNdisVersion = 2;
//#line  72
  m.__annonCompField5.__annonCompField4.__annonCompField3.Filler = 3;
//#line  73
  m.__annonCompField5.__annonCompField4.__annonCompField3.Reserved = 4;
//#line  75
  m.__annonCompField5.__annonCompField4.__annonCompField3.CheckForHangHandler = 5;
//#line  76
  m.__annonCompField5.__annonCompField4.__annonCompField3.DisableInterruptHandler = 6;
//#line  77
  m.__annonCompField5.__annonCompField4.__annonCompField3.EnableInterruptHandler = 7;
//#line  78
  m.__annonCompField5.__annonCompField4.__annonCompField3.HaltHandler = 8;
//#line  79
  m.__annonCompField5.__annonCompField4.__annonCompField3.HandleInterruptHandler = 9;
//#line  80
  m.__annonCompField5.__annonCompField4.__annonCompField3.InitializeHandler = 10;
//#line  81
  m.__annonCompField5.__annonCompField4.__annonCompField3.ISRHandler = 11;
//#line  82
  m.__annonCompField5.__annonCompField4.__annonCompField3.QueryInformationHandler = 12;
//#line  83
  m.__annonCompField5.__annonCompField4.__annonCompField3.ReconfigureHandler = 13;
//#line  84
  m.__annonCompField5.__annonCompField4.__annonCompField3.ResetHandler = 14;
//#line  86
  m.__annonCompField5.__annonCompField4.__annonCompField3.__annonCompField1.SendHandler = 15;
//#line  87
  if (m.__annonCompField5.__annonCompField4.__annonCompField3.__annonCompField1.WanSendHandler != 15) {
//#line  87
    printf("Error %d\n", 1);
//#line  87
    exit(1);
  }
//#line  89
  m.__annonCompField5.__annonCompField4.__annonCompField3.SetInformationHandler = 16;
//#line  90
  m.__annonCompField5.__annonCompField4.__annonCompField3.__annonCompField2.TransferDataHandler = 17;
//#line  91
  if (m.__annonCompField5.__annonCompField4.__annonCompField3.__annonCompField2.WanTransferDataHandler != 17) {
//#line  91
    printf("Error %d\n", 2);
//#line  91
    exit(2);
  }
//#line  94
  m.__annonCompField5.__annonCompField4.ReturnPacketHandler = 18;
//#line  95
  m.__annonCompField5.__annonCompField4.SendPacketsHandler = 19;
//#line  96
  m.__annonCompField5.__annonCompField4.AllocateCompleteHandler = 20;
//#line  100
  m.__annonCompField5.CoCreateVcHandler = 21;
//#line  101
  m.__annonCompField5.CoDeleteVcHandler = 22;
//#line  102
  m.__annonCompField5.CoActivateVcHandler = 23;
//#line  103
  m.__annonCompField5.CoDeactivateVcHandler = 24;
//#line  104
  m.__annonCompField5.CoSendPacketsHandler = 25;
//#line  105
  m.__annonCompField5.CoRequestHandler = 26;
//#line  108
  m.CancelSendPacketsHandler = 27;
//#line  109
  m.PnPEventNotifyHandler = 28;
//#line  110
  m.AdapterShutdownHandler = 29;
//#line  111
  m.Reserved1 = 30;
//#line  112
  m.Reserved2 = 31;
//#line  113
  m.Reserved3 = 32;
//#line  114
  m.Reserved4 = 33;
//#line  120
  i = 0;
//#line  120
  while ((unsigned long )i < sizeof(m) / sizeof(int )) {
//#line  121
    if (*((int *)(& m) + i) != i + 1) {
//#line  122
      printf("The %dth word is %d\n", i, *((int *)(& m) + i));
//#line  123
      printf("Error %d\n", 3);
//#line  123
      exit(3);
    }
//#line  120
    i ++;
  }
//#line  127
  printf("Success\n");
//#line  127
  exit(0);
}
}
