/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "noreturn.c"
extern  __attribute__((__noreturn__)) void direct() ;
//#line  4 "noreturn.c"
 __attribute__((__noreturn__)) void (*indirect)()  =    & direct;
//#line  7 "noreturn.c"
 __attribute__((__noreturn__)) void (*afun[2])()  = {      & direct,      & direct};
//#line  9 "noreturn.c"
void caller(void) 
{ 


  {
//#line  11
  direct();
//#line  12
  (*indirect)();
}
}
//#line  16 "noreturn.c"
int main(void) 
{ 


  {
//#line  17
  return (0);
}
}
