/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "offsetof.c"
struct mystruct {
   int a ;
   int b ;
};
//#line  4 "offsetof.c"
typedef struct mystruct Mystruct;
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  9 "offsetof.c"
Mystruct Foo  ;
//#line  11 "offsetof.c"
int main(void) 
{ 
  long addr_b ;

  {
//#line  14
  addr_b = (long )(& Foo);
//#line  16
  addr_b += (long )((unsigned long )(& ((Mystruct *)0)->b));
//#line  18
  if (addr_b != (long )(& Foo.b)) {
//#line  18
    printf("Error %d\n", 1);
//#line  18
    exit(1);
  }
//#line  20
  printf("Success\n");
//#line  20
  exit(0);
}
}
