/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  6 "offsetof3.c"
struct bar {
   int a[8] ;
   int b ;
};
//#line  6 "offsetof3.c"
struct baz {
   int c[4] ;
};
//#line  6 "offsetof3.c"
struct foo {
   struct bar f1 ;
   struct baz f2[2] ;
};
//#line  18 "offsetof3.c"
typedef struct foo f2;
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  20 "offsetof3.c"
int main(void) 
{ 


  {
//#line  24
  if ((unsigned long )(& ((struct foo *)0)->f1.b) != 8UL * sizeof(int )) {
//#line  24
    printf("Error %d\n", 1);
//#line  24
    exit(1);
  }
//#line  26
  if ((unsigned long )(& ((struct foo *)0)->f1.a[2]) != 2UL * sizeof(int )) {
//#line  26
    printf("Error %d\n", 2);
//#line  26
    exit(2);
  }
//#line  28
  if ((unsigned long )(& ((f2 *)0)->f2[1].c[3]) != (sizeof(struct bar ) + sizeof(struct baz )) + 3UL * sizeof(int )) {
//#line  29
    printf("Error %d\n", 3);
//#line  29
    exit(3);
  }
//#line  31
  if ((unsigned long )(& ((f2 *)0)->f2) != sizeof(struct bar )) {
//#line  31
    printf("Error %d\n", 4);
//#line  31
    exit(4);
  }
//#line  33
  printf("Success\n");
//#line  33
  exit(0);
}
}
