/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  2 "offsetof1.c"
struct align_short {
   char c ;
   short a ;
};
//#line  9 "offsetof1.c"
int main(void) 
{ 
  int align_of_short ;

  {
//#line  13
  align_of_short = (int )((char *)(& ((struct align_short *)0)->a) - (char *)0);
//#line  16
  return (0);
}
}
