/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "outofmem.c"
struct elim_table {
   int foo ;
};
/* compiler builtin: 
   void *__builtin_alloca(unsigned long  ) ;  */
//#line  8 "outofmem.c"
struct elim_table reg_eliminate[5]  ;
//#line  11 "outofmem.c"
static int (*offsets_at)[sizeof(reg_eliminate) / sizeof(reg_eliminate[0])]  ;
//#line  13 "outofmem.c"
void reload2(void) 
{ 
  void *tmp ;

  {
//#line  15
  tmp = __builtin_alloca(sizeof(reg_eliminate) / sizeof(reg_eliminate[0]));
//#line  15
  offsets_at = (int (*)[sizeof(reg_eliminate) / sizeof(reg_eliminate[0])])tmp;
//#line  17
  return;
}
}
