/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  35 "packed2.c"
struct s3 {
   char a ;
   short b  __attribute__((__packed__)) ;
   int c ;
};
//#line  35 "packed2.c"
struct s3 s3  ;
//#line  75 "packed2.c"
int main(void) 
{ 


  {
//#line  76
  return (0);
}
}
