/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  5 "packed.c"
struct s {
   char x1 ;
   double d ;
} __attribute__((__packed__)) ;
//#line  5 "packed.c"
typedef struct s s;
//#line  22 "packed.c"
struct __anonstruct_t1_480146755 {
   int x1 ;
   short x2 ;
   short x3 ;
} __attribute__((__packed__)) ;
//#line  22 "packed.c"
typedef struct __anonstruct_t1_480146755 t1;
//#line  28 "packed.c"
struct __anonstruct_t2_480146756 {
   int x1 ;
   short x2 ;
   short x3 ;
} __attribute__((__packed__)) ;
//#line  28 "packed.c"
typedef struct __anonstruct_t2_480146756 t2;
//#line  34 "packed.c"
struct __anonstruct_t3_480146757 {
   int x1 ;
   short x2 ;
   short x3 ;
} __attribute__((__packed__)) ;
//#line  34 "packed.c"
typedef struct __anonstruct_t3_480146757 t3;
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  10 "packed.c"
s foo  ;
//#line  15 "packed.c"
int main(void) 
{ 


  {
//#line  16
  printf("sizeof(foo) = %d.\n", (int )sizeof(foo));
//#line  17
  if (sizeof(foo) != 9UL) {
//#line  17
    printf("Error %d\n", 1);
//#line  17
    exit(1);
  }
//#line  18
  return (0);
}
}
//#line  40 "packed.c"
t1 t1_  ;
//#line  41 "packed.c"
t2 t2_  ;
//#line  42 "packed.c"
t3 t3_  ;
