/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  190 "/usr/include/x86_64-linux-gnu/sys/syslog.h"
extern void ( /* format attribute */  syslog)(int __pri , char const   *__fmt  , ...) ;
//#line  4 "percentm.c"
int main(void) 
{ 


  {
//#line  5
  syslog(3, "%m");
//#line  6
  return (0);
}
}
