/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  433 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) sscanf)(char const   * __restrict  __s ,
                                                                             char const   * __restrict  __format 
                                                                             , ...)  __asm__("__isoc99_sscanf")  ;
//#line  3 "percent400.c"
int main(void) 
{ 
  char buf[10] ;
  unsigned int tmp ;
  char *str ;

  {
//#line  4
  buf[0] = (char )'a';
//#line  4
  buf[1] = (char )'b';
//#line  4
  buf[2] = (char )'c';
//#line  4
  buf[3] = (char )'\000';
//#line  4
  tmp = 4U;
//#line  4
  while (! (tmp >= 10U)) {
//#line  4
    buf[tmp] = (char)0;
//#line  4
    tmp ++;
  }
//#line  5
  sscanf((char const   */* __restrict  */)(buf), (char const   */* __restrict  */)"%400",
         str);
//#line  6
  return (0);
}
}
