/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "post-assign.c"
int g  ;
//#line  4 "post-assign.c"
void testg(int x , int err ) 
{ 


  {
//#line  5
  if (g != 6) {
//#line  5
    printf("Error %d\n", err);
//#line  5
    exit(err);
  }
//#line  6
  return;
}
}
//#line  8 "post-assign.c"
int main(void) 
{ 
  int x ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;

  {
//#line  10
  x = 7;
//#line  19
  tmp = x;
//#line  19
  x ++;
//#line  19
  x = tmp;
//#line  20
  if (x != 8) {
//#line  20
    printf("Error %d\n", 1);
//#line  20
    exit(1);
  }
//#line  25
  tmp___0 = x;
//#line  25
  x ++;
//#line  25
  tmp___1 = x;
//#line  25
  x ++;
//#line  25
  x = tmp___0 + tmp___1;
//#line  26
  if (x != 18) {
//#line  26
    printf("Error %d\n", 2);
//#line  26
    exit(2);
  }
//#line  29
  g = 5;
//#line  30
  tmp___2 = g;
//#line  30
  g ++;
//#line  30
  testg(tmp___2, 5);
//#line  32
  printf("Success\n");
//#line  32
  exit(0);
}
}
