/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "power1.c"
struct demand {
   double P ;
   double Q ;
};
//#line  3 "power1.c"
typedef struct demand Demand;
//#line  11
struct lateral ;
//#line  11 "power1.c"
struct root {
   Demand D ;
   double theta_R ;
   double theta_I ;
   Demand last ;
   double last_theta_R ;
   double last_theta_I ;
   struct lateral *feeders[10] ;
};
//#line  11 "power1.c"
typedef struct root *Root;
//#line  21
struct branch ;
//#line  21 "power1.c"
struct lateral {
   Demand D ;
   double alpha ;
   double beta ;
   double R ;
   double X ;
   struct lateral *next_lateral ;
   struct branch *branch ;
};
//#line  21 "power1.c"
typedef struct lateral *Lateral;
//#line  31
struct leaf ;
//#line  31 "power1.c"
struct branch {
   Demand D ;
   double alpha ;
   double beta ;
   double R ;
   double X ;
   struct branch *next_branch ;
   struct leaf *leaves[10] ;
};
//#line  31 "power1.c"
typedef struct branch *Branch;
//#line  41 "power1.c"
struct leaf {
   Demand D ;
   double pi_R ;
   double pi_I ;
};
//#line  47
void Compute_Tree(Root r ) ;
//#line  48
Demand Compute_Lateral(Lateral l , double theta_R , double theta_I , double pi_R ,
                       double pi_I ) ;
//#line  51
extern Demand Compute_Branch(Branch b , double theta_R , double theta_I , double pi_R ,
                             double pi_I ) ;
//#line  61 "power1.c"
void Compute_Tree(Root r ) 
{ 
  register int i ;
  Lateral l ;
  Demand a ;
  double theta_R ;
  double theta_I ;

  {
//#line  72
  i = 0;
//#line  72
  while (i < 10) {
//#line  74
    l = r->feeders[i];
//#line  75
    a = Compute_Lateral(l, theta_R, theta_I, theta_R, theta_I);
//#line  72
    i ++;
  }
//#line  77
  return;
}
}
//#line  79 "power1.c"
Demand Compute_Lateral(Lateral l , double theta_R , double theta_I , double pi_R ,
                       double pi_I ) 
{ 
  Demand a1 ;
  Demand a2 ;
  double new_pi_R ;
  double new_pi_I ;
  Lateral next ;
  Branch br ;

  {
//#line  89
  next = l->next_lateral;
//#line  90
  a1 = Compute_Lateral(next, theta_R, theta_I, new_pi_R, new_pi_I);
//#line  92
  br = l->branch;
//#line  93
  a2 = Compute_Branch(br, theta_R, theta_I, new_pi_R, new_pi_I);
//#line  94
  return (l->D);
}
}
