/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
//#line  131 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
//#line  132 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off64_t;
//#line  44 "/usr/include/stdio.h"
struct _IO_FILE ;
//#line  48 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
//#line  150 "/usr/include/libio.h"
typedef void _IO_lock_t;
//#line  156 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
//#line  241 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
//#line  169 "/usr/include/stdio.h"
extern struct _IO_FILE *stdout ;
//#line  356
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
//#line  362
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  3 "printf_const.c"
int main(void) 
{ 
  char const   *p1 ;
  char const   *p2 ;
  int x ;
  int y ;
  int const   *p3 ;
  int const   *p4 ;
  double d ;

  {
//#line  4
  p1 = "first string";
//#line  5
  p2 = "second string";
//#line  6
  x = 5;
//#line  7
  y = 6;
//#line  8
  p3 = (int const   *)(& x);
//#line  9
  p4 = (int const   *)(& y);
//#line  10
  d = 5.5;
//#line  12
  printf((char const   */* __restrict  */)"p1 = %s\n", p1);
//#line  13
  fprintf((FILE */* __restrict  */)stdout, (char const   */* __restrict  */)"p2 = %s\n",
          p2);
//#line  14
  printf((char const   */* __restrict  */)"p3 = %p\n", (long )p3);
//#line  15
  fprintf((FILE */* __restrict  */)stdout, (char const   */* __restrict  */)"p4 = %s\n",
          (long )p4);
//#line  16
  printf((char const   */* __restrict  */)"x = %d\n", x);
//#line  17
  printf((char const   */* __restrict  */)"d = %g\n", d);
//#line  19
  return (0);
}
}
