/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
//#line  131 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
//#line  132 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off64_t;
//#line  44 "/usr/include/stdio.h"
struct _IO_FILE ;
//#line  48 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
//#line  150 "/usr/include/libio.h"
typedef void _IO_lock_t;
//#line  156 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
//#line  241 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
//#line  169 "/usr/include/stdio.h"
extern struct _IO_FILE *stdout ;
//#line  356
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
//#line  362
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  364
extern  __attribute__((__nothrow__)) int sprintf(char * __restrict  __s , char const   * __restrict  __format 
                                                 , ...) ;
//#line  3 "printf.c"
int main(void) 
{ 
  int x ;
  int y ;
  int z ;
  int len ;
  char *p ;
  char *q ;
  char *r ;
  char dest_buf[1024] ;
  char *s1 ;
  char *s2 ;

  {
//#line  4
  x = 100;
//#line  4
  y = 200;
//#line  4
  z = 300;
//#line  4
  len = 6;
//#line  6
  p = (char *)"<<p>>";
//#line  6
  q = (char *)"<<q>>";
//#line  6
  r = (char *)"<<r>>";
//#line  10
  printf((char const   */* __restrict  */)"printf: %s %ld %0.20s %x\n", p, x, q, y);
//#line  11
  fprintf((FILE */* __restrict  */)stdout, (char const   */* __restrict  */)"fprintf: %s %ld %0.20s %x\n",
          p, y, q, z);
//#line  12
  sprintf((char */* __restrict  */)(dest_buf), (char const   */* __restrict  */)"sprintf: %s %ld %0.20s %x",
          p, z, q, x);
//#line  13
  printf((char const   */* __restrict  */)"printf: dest_buf = [%s]\n", dest_buf);
//#line  15
  s1 = & dest_buf[5];
//#line  16
  s2 = s1 + 5;
//#line  18
  printf((char const   */* __restrict  */)"printf: chop 5: [%s]\n", s1);
//#line  19
  printf((char const   */* __restrict  */)"printf: chop 5 more, print %d: [%.*s]\n",
         len, len, s2);
//#line  21
  printf((char const   */* __restrict  */)"printf: null = %s\n", (char *)0);
//#line  23
  return (0);
}
}
