/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  364 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) int sprintf(char * __restrict  __s , char const   * __restrict  __format 
                                                 , ...) ;
//#line  6 "printf2.c"
int main(void) 
{ 
  char buffer[16] ;
  double d ;

  {
//#line  8
  d = 7.75;
//#line  10
  sprintf((char */* __restrict  */)(buffer), (char const   */* __restrict  */)"%5.2f",
          d);
//#line  12
  printf((char const   */* __restrict  */)"The buffer is: %s\n", buffer);
//#line  14
  if ((int )buffer[0] != 32) {
//#line  14
    printf((char const   */* __restrict  */)"Error %d\n", 1);
//#line  14
    exit(1);
  } else
//#line  14
  if ((int )buffer[1] != 55) {
//#line  14
    printf((char const   */* __restrict  */)"Error %d\n", 1);
//#line  14
    exit(1);
  } else
//#line  14
  if ((int )buffer[2] != 46) {
//#line  14
    printf((char const   */* __restrict  */)"Error %d\n", 1);
//#line  14
    exit(1);
  }
//#line  16
  printf((char const   */* __restrict  */)"Success\n");
//#line  16
  exit(0);
}
}
