/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "proto1.c"
struct bar {
   int x ;
   int y ;
};
//#line  2
int foo(struct bar *a ) ;
//#line  8 "proto1.c"
int (*pfoo)()  =    & foo;
//#line  11 "proto1.c"
int foo(struct bar *a ) 
{ 


  {
//#line  12
  return (a->x + a->y);
}
}
