/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "pure.c"
int pure[700000UL / sizeof(int )]  = {      0};
//#line  3 "pure.c"
int main(void) 
{ 
  char *blah ;

  {
//#line  4
  blah = (char *)(pure);
//#line  5
  return (0);
}
}
