/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  48 "question2.c"
extern int ( /* missing proto */  printf)() ;
//#line  46 "question2.c"
int main(void) 
{ 
  int log ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;
  int tmp___7 ;
  int tmp___8 ;
  int tmp___9 ;
  int tmp___10 ;
  int tmp___11 ;
  int tmp___12 ;
  int tmp___13 ;
  int tmp___14 ;
  int tmp___15 ;
  int tmp___16 ;
  int tmp___17 ;
  int tmp___18 ;
  int tmp___19 ;
  int tmp___20 ;
  int tmp___21 ;
  int tmp___22 ;
  int tmp___23 ;
  int tmp___24 ;
  int tmp___25 ;
  int tmp___26 ;
  int tmp___27 ;
  int tmp___28 ;
  int tmp___29 ;

  {
//#line  47
  if (63ULL & (1ULL << 31)) {
//#line  47
    tmp___29 = 31;
  } else {
//#line  47
    if (63ULL & (1ULL << 30)) {
//#line  47
      tmp___28 = 30;
    } else {
//#line  47
      if (63ULL & (1ULL << 29)) {
//#line  47
        tmp___27 = 29;
      } else {
//#line  47
        if (63ULL & (1ULL << 28)) {
//#line  47
          tmp___26 = 28;
        } else {
//#line  47
          if (63ULL & (1ULL << 27)) {
//#line  47
            tmp___25 = 27;
          } else {
//#line  47
            if (63ULL & (1ULL << 26)) {
//#line  47
              tmp___24 = 26;
            } else {
//#line  47
              if (63ULL & (1ULL << 25)) {
//#line  47
                tmp___23 = 25;
              } else {
//#line  47
                if (63ULL & (1ULL << 24)) {
//#line  47
                  tmp___22 = 24;
                } else {
//#line  47
                  if (63ULL & (1ULL << 23)) {
//#line  47
                    tmp___21 = 23;
                  } else {
//#line  47
                    if (63ULL & (1ULL << 22)) {
//#line  47
                      tmp___20 = 22;
                    } else {
//#line  47
                      if (63ULL & (1ULL << 21)) {
//#line  47
                        tmp___19 = 21;
                      } else {
//#line  47
                        if (63ULL & (1ULL << 20)) {
//#line  47
                          tmp___18 = 20;
                        } else {
//#line  47
                          if (63ULL & (1ULL << 19)) {
//#line  47
                            tmp___17 = 19;
                          } else {
//#line  47
                            if (63ULL & (1ULL << 18)) {
//#line  47
                              tmp___16 = 18;
                            } else {
//#line  47
                              if (63ULL & (1ULL << 17)) {
//#line  47
                                tmp___15 = 17;
                              } else {
//#line  47
                                if (63ULL & (1ULL << 16)) {
//#line  47
                                  tmp___14 = 16;
                                } else {
//#line  47
                                  if (63ULL & (1ULL << 15)) {
//#line  47
                                    tmp___13 = 15;
                                  } else {
//#line  47
                                    if (63ULL & (1ULL << 14)) {
//#line  47
                                      tmp___12 = 14;
                                    } else {
//#line  47
                                      if (63ULL & (1ULL << 13)) {
//#line  47
                                        tmp___11 = 13;
                                      } else {
//#line  47
                                        if (63ULL & (1ULL << 12)) {
//#line  47
                                          tmp___10 = 12;
                                        } else {
//#line  47
                                          if (63ULL & (1ULL << 11)) {
//#line  47
                                            tmp___9 = 11;
                                          } else {
//#line  47
                                            if (63ULL & (1ULL << 10)) {
//#line  47
                                              tmp___8 = 10;
                                            } else {
//#line  47
                                              if (63ULL & (1ULL << 9)) {
//#line  47
                                                tmp___7 = 9;
                                              } else {
//#line  47
                                                if (63ULL & (1ULL << 8)) {
//#line  47
                                                  tmp___6 = 8;
                                                } else {
//#line  47
                                                  if (63ULL & (1ULL << 7)) {
//#line  47
                                                    tmp___5 = 7;
                                                  } else {
//#line  47
                                                    if (63ULL & (1ULL << 6)) {
//#line  47
                                                      tmp___4 = 6;
                                                    } else {
//#line  47
                                                      if (63ULL & (1ULL << 5)) {
//#line  47
                                                        tmp___3 = 5;
                                                      } else {
//#line  47
                                                        if (63ULL & (1ULL << 4)) {
//#line  47
                                                          tmp___2 = 4;
                                                        } else {
//#line  47
                                                          if (63ULL & (1ULL << 3)) {
//#line  47
                                                            tmp___1 = 3;
                                                          } else {
//#line  47
                                                            if (63ULL & (1ULL << 2)) {
//#line  47
                                                              tmp___0 = 2;
                                                            } else {
//#line  47
                                                              if (63ULL & (1ULL << 1)) {
//#line  47
                                                                tmp = 1;
                                                              } else {
//#line  47
                                                                tmp = 0;
                                                              }
//#line  47
                                                              tmp___0 = tmp;
                                                            }
//#line  47
                                                            tmp___1 = tmp___0;
                                                          }
//#line  47
                                                          tmp___2 = tmp___1;
                                                        }
//#line  47
                                                        tmp___3 = tmp___2;
                                                      }
//#line  47
                                                      tmp___4 = tmp___3;
                                                    }
//#line  47
                                                    tmp___5 = tmp___4;
                                                  }
//#line  47
                                                  tmp___6 = tmp___5;
                                                }
//#line  47
                                                tmp___7 = tmp___6;
                                              }
//#line  47
                                              tmp___8 = tmp___7;
                                            }
//#line  47
                                            tmp___9 = tmp___8;
                                          }
//#line  47
                                          tmp___10 = tmp___9;
                                        }
//#line  47
                                        tmp___11 = tmp___10;
                                      }
//#line  47
                                      tmp___12 = tmp___11;
                                    }
//#line  47
                                    tmp___13 = tmp___12;
                                  }
//#line  47
                                  tmp___14 = tmp___13;
                                }
//#line  47
                                tmp___15 = tmp___14;
                              }
//#line  47
                              tmp___16 = tmp___15;
                            }
//#line  47
                            tmp___17 = tmp___16;
                          }
//#line  47
                          tmp___18 = tmp___17;
                        }
//#line  47
                        tmp___19 = tmp___18;
                      }
//#line  47
                      tmp___20 = tmp___19;
                    }
//#line  47
                    tmp___21 = tmp___20;
                  }
//#line  47
                  tmp___22 = tmp___21;
                }
//#line  47
                tmp___23 = tmp___22;
              }
//#line  47
              tmp___24 = tmp___23;
            }
//#line  47
            tmp___25 = tmp___24;
          }
//#line  47
          tmp___26 = tmp___25;
        }
//#line  47
        tmp___27 = tmp___26;
      }
//#line  47
      tmp___28 = tmp___27;
    }
//#line  47
    tmp___29 = tmp___28;
  }
//#line  47
  log = tmp___29;
//#line  48
  printf("%d\n", log);
//#line  49
  return (0);
}
}
