/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "question.c"
int main(void) 
{ 
  char const   *string ;
  char const   *p ;

  {
//#line  4
  string = "hello";
//#line  6
  if (string) {
//#line  6
    p = string;
  } else {
//#line  6
    p = "NULL";
  }
//#line  7
  printf("Success\n");
//#line  7
  exit(0);
}
}
