/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "question-fold-float.c"
struct s {
   _Bool s : 1 ;
   _Bool t ;
};
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  2 "question-fold-float.c"
#pragma GCC diagnostic ignored "-Waddress"
//#line  4 "question-fold-float.c"
struct s s  ;
//#line  6 "question-fold-float.c"
char a[1]  ;
//#line  7 "question-fold-float.c"
char b[1]  ;
//#line  8 "question-fold-float.c"
char c[1]  ;
//#line  10 "question-fold-float.c"
char d[(int )((_Bool )0.5) == 1 ? 1 : -1]  ;
//#line  12 "question-fold-float.c"
_Bool e  =    (_Bool )(& s);
//#line  15 "question-fold-float.c"
char f[(int )((_Bool )0.0) == 0 ? 1 : -1]  ;
//#line  17 "question-fold-float.c"
char g[1]  ;
//#line  18 "question-fold-float.c"
char h[sizeof(_Bool )]  ;
//#line  20 "question-fold-float.c"
char i[sizeof(s.t)]  ;
//#line  23 "question-fold-float.c"
_Bool n[256]  ;
//#line  24 "question-fold-float.c"
char o[1]  ;
//#line  25 "question-fold-float.c"
char p[1]  ;
//#line  27 "question-fold-float.c"
_Bool q  =    (_Bool)1;
//#line  28 "question-fold-float.c"
_Bool *pq  =    & q;
//#line  30 "question-fold-float.c"
int main(void) 
{ 
  _Bool e1 ;
  char digs[11] ;

  {
//#line  34
  e1 = (_Bool )(& s);
//#line  35
  if (! e1) {
//#line  36
    printf("Error %d\n", 1);
//#line  36
    exit(1);
  }
//#line  39
  digs[0] = (char )'0';
//#line  39
  digs[1] = (char )'1';
//#line  39
  digs[2] = (char )'2';
//#line  39
  digs[3] = (char )'3';
//#line  39
  digs[4] = (char )'4';
//#line  39
  digs[5] = (char )'5';
//#line  39
  digs[6] = (char )'6';
//#line  39
  digs[7] = (char )'7';
//#line  39
  digs[8] = (char )'8';
//#line  39
  digs[9] = (char )'9';
//#line  39
  digs[10] = (char )'\000';
//#line  40
  if ((unsigned long )((digs + 5) + -1) != (unsigned long )(& digs[4])) {
//#line  41
    printf("Error %d\n", 2);
//#line  41
    exit(2);
  }
//#line  44
  printf("Success\n");
//#line  44
  exit(0);
}
}
