/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "question3.c"
int main(void) 
{ 
  int x ;
  int y ;
  int z ;
  int keep1 ;
  int unfold1 ;
  int tmp ;
  int tmp___0 ;
  int unfold2 ;
  int tmp___1 ;
  int tmp___2 ;
  int unfold3 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int keep2 ;
  int tmp___6 ;
  int unfold4 ;
  int tmp___8 ;
  int tmp___9 ;
  int tmp___10 ;
  int unfold5 ;
  int tmp___12 ;
  int tmp___13 ;
  int tmp___14 ;
  int unfold6 ;
  int tmp___16 ;
  int tmp___17 ;
  int tmp___18 ;
  int tmp___19 ;

  {
//#line  3
  keep1 = x ? y : z;
//#line  4
  if (x) {
//#line  4
    tmp___0 = y;
  } else {
//#line  4
    tmp = z;
//#line  4
    z ++;
//#line  4
    tmp___0 = tmp;
  }
//#line  4
  unfold1 = tmp___0;
//#line  5
  if (x) {
//#line  5
    tmp___1 = y;
//#line  5
    y ++;
//#line  5
    tmp___2 = tmp___1;
  } else {
//#line  5
    tmp___2 = z;
  }
//#line  5
  unfold2 = tmp___2;
//#line  6
  if (x) {
//#line  6
    tmp___3 = y;
//#line  6
    y ++;
//#line  6
    tmp___5 = tmp___3;
  } else {
//#line  6
    tmp___4 = z;
//#line  6
    z ++;
//#line  6
    tmp___5 = tmp___4;
  }
//#line  6
  unfold3 = tmp___5;
//#line  7
  tmp___6 = x;
//#line  7
  x ++;
//#line  7
  keep2 = tmp___6 ? y : z;
//#line  8
  tmp___10 = x;
//#line  8
  x ++;
//#line  8
  if (tmp___10) {
//#line  8
    tmp___9 = y;
  } else {
//#line  8
    tmp___8 = z;
//#line  8
    z ++;
//#line  8
    tmp___9 = tmp___8;
  }
//#line  8
  unfold4 = tmp___9;
//#line  9
  tmp___14 = x;
//#line  9
  x ++;
//#line  9
  if (tmp___14) {
//#line  9
    tmp___12 = y;
//#line  9
    y ++;
//#line  9
    tmp___13 = tmp___12;
  } else {
//#line  9
    tmp___13 = z;
  }
//#line  9
  unfold5 = tmp___13;
//#line  10
  tmp___19 = x;
//#line  10
  x ++;
//#line  10
  if (tmp___19) {
//#line  10
    tmp___16 = y;
//#line  10
    y ++;
//#line  10
    tmp___18 = tmp___16;
  } else {
//#line  10
    tmp___17 = z;
//#line  10
    z ++;
//#line  10
    tmp___18 = tmp___17;
  }
//#line  10
  unfold6 = tmp___18;
//#line  11
  return (0);
}
}
