/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "restrict1.c"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  3 "restrict1.c"
int main(void) 
{ 


  {
//#line  4
  printf((char const   */* __restrict  */)"Hello world\n");
//#line  5
  return (0);
}
}
