/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "restrict.c"
void vadd(double const   * __restrict  a , double const   * __restrict  b , double * __restrict  c ,
          int n ) 
{ 
  int i ;

  {
//#line  7
  i = 0;
//#line  7
  while (i < n) {
//#line  7
    *(c + i) = (double )(*(a + i) + *(b + i));
//#line  7
    i ++;
  }
//#line  8
  return;
}
}
//#line  10 "restrict.c"
int main(void) 
{ 
  double a[10] ;
  double b[10] ;
  double c[10] ;

  {
//#line  12
  vadd((double const   */* __restrict  */)(a), (double const   */* __restrict  */)(b),
       (double */* __restrict  */)(c), 10);
//#line  14
  return (0);
}
}
