/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  2 "return1.c"
void destroy(int *x ) 
{ 


  {
//#line  3
  x = (int *)0;
//#line  4
  return;
}
}
//#line  6 "return1.c"
int main(void) 
{ 
  int x ;

  {
//#line  8
  destroy(& x);
//#line  8
  return (0);
}
}
