/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  2 "returnvoid.c"
void g(void) ;
//#line  3
void h(void) ;
//#line  5 "returnvoid.c"
int main(int argc , char **argv ) 
{ 


  {
//#line  6
  h();
//#line  7
  return (0);
}
}
//#line  10 "returnvoid.c"
void h(void) 
{ 


  {
//#line  11
  g();
//#line  11
  return;
}
}
//#line  14 "returnvoid.c"
void g(void) 
{ 


  {
//#line  15
  return;
}
}
