/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  7 "returnvoid1.c"
struct b_data_t {
   int node_boot_start ;
   int node_low_pfn ;
};
//#line  7 "returnvoid1.c"
typedef struct b_data_t bootmem_data_t;
//#line  12 "returnvoid1.c"
struct pg_d_t {
   struct b_data_t *bdata ;
};
//#line  12 "returnvoid1.c"
typedef struct pg_d_t pg_data_t;
//#line  362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  16 "returnvoid1.c"
static void free_bootmem_core(bootmem_data_t *bdata , unsigned long addr , unsigned long size ) 
{ 
  unsigned long eidx ;
  unsigned long end ;

  {
//#line  21
  eidx = ((addr + size) - (unsigned long )bdata->node_boot_start) / 512UL;
//#line  22
  end = (addr + size) / 512UL;
//#line  24
  if (! size) {
//#line  24
    printf((char const   */* __restrict  */)"wow.");
  }
//#line  25
  if (end > (unsigned long )bdata->node_low_pfn) {
//#line  26
    printf((char const   */* __restrict  */)"wow.");
  }
//#line  28
  return;
}
}
//#line  30 "returnvoid1.c"
void free_bootmem_node(pg_data_t *pgdat , unsigned long physaddr , unsigned long size ) 
{ 


  {
//#line  31
  free_bootmem_core(pgdat->bdata, physaddr, size);
//#line  31
  return;
}
}
//#line  34 "returnvoid1.c"
int main(int charc , char **argv ) 
{ 


  {
//#line  35
  return (0);
}
}
