/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  2 "retval.c"
struct rbNode {
   int filler ;
   char data[0] ;
};
//#line  2 "retval.c"
typedef struct rbNode RBNode;
//#line  7 "retval.c"
char *ret_field(RBNode *r ) 
{ 


  {
//#line  8
  return (& r->data[0]);
}
}
