/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "rmtmps-attr.c"
int main(void) 
{ 
  int b  __attribute__((__myattribute__((a) ==  (a) ))) ;

  {
//#line  7
  b = 5;
//#line  13
  printf("Success\n");
//#line  13
  exit(0);
}
}
