/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  5 "rmtmps1.c"
int system_utsname ;
//#line  5 "rmtmps1.c"
struct nlm_rqst {
   unsigned int a_flags ;
   char a_owner[sizeof(system_utsname) + 10UL] ;
};
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "rmtmps1.c"
int system_utsname  ;
//#line  11 "rmtmps1.c"
int main(void) 
{ 
  struct nlm_rqst s ;

  {
//#line  14
  if (sizeof(s) != sizeof(struct nlm_rqst )) {
//#line  14
    printf("Error %d\n", 1);
//#line  14
    exit(1);
  }
//#line  16
  printf("Success\n");
//#line  16
  exit(0);
}
}
