/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "scope2.c"
struct str {
   int x ;
};
//#line  4 "scope2.c"
typedef struct str STR;
//#line  9 "scope2.c"
struct str___0 {
   int y ;
};
//#line  15 "scope2.c"
struct __anonstruct_Z_109580352 {
   int g ;
};
//#line  15 "scope2.c"
typedef struct __anonstruct_Z_109580352 Z;
//#line  24 "scope2.c"
struct str___2 {
   int z ;
};
//#line  24 "scope2.c"
typedef struct str___2 Z___0;
//#line  8 "scope2.c"
int f1(STR *s1 ) 
{ 
  struct str___0 x ;

  {
//#line  12
  s1->x = x.y;
//#line  13
  return (0);
}
}
//#line  17 "scope2.c"
struct str glob1  ;
//#line  19 "scope2.c"
int f2(void) 
{ 


  {
//#line  23
  while (1) {
//#line  29
    glob1.x = ((Z___0 *)(& glob1))->z;
  }
}
}
//#line  34 "scope2.c"
Z globz  ;
//#line  35 "scope2.c"
int *globza  =    & globz.g;
