/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  11 "scope1.c"
struct Person {
   char *name ;
};
//#line  11 "scope1.c"
typedef struct Person Person;
//#line  29
enum __anonenum_z_639295868 {
    l1___1 = 7,
    l2___1 = 9
} ;
//#line  1
extern void exit(int  ) ;
//#line  3 "scope1.c"
int foo[5]  ;
//#line  19 "scope1.c"
int globint  ;
//#line  28
void increm(int *i ) ;
//#line  17 "scope1.c"
int main(void) 
{ 
  int l ;
  int *l2___0 ;
  Person *Person___0 ;
  int *l1___0 ;

  {
//#line  18
  l2___0 = & l;
//#line  20
  Person___0 = (Person *)0;
//#line  22
  l1___0 = l2___0;
//#line  23
  *l1___0 = *l2___0 + 2;
//#line  24
  globint = 2;
//#line  33
  increm(& globint);
//#line  34
  return (globint - 3);
//#line  36
  *l2___0 = 2;
//#line  37
  exit(1);
}
}
//#line  40 "scope1.c"
void increm(int *i ) 
{ 


  {
//#line  41
  (*i) ++;
//#line  42
  return;
}
}
