/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "scope6.c"
struct foo {
   int x ;
   int y ;
};
//#line  10 "scope6.c"
typedef struct foo *PFOO;
//#line  14 "scope6.c"
struct foo___0 {
   int a ;
   int b ;
};
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "scope6.c"
struct foo foo  ;
//#line  8 "scope6.c"
int main(void) 
{ 
  PFOO pfoo ;
  struct foo___0 anotherfoo ;
  int z ;

  {
//#line  12
  pfoo = & foo;
//#line  19
  z = pfoo->x + anotherfoo.a;
//#line  21
  printf("Success\n");
//#line  21
  exit(0);
}
}
