/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
//#line  466 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
//#line  4 "scope4.c"
char **pm_allocarray(int cols , int rows , int size ) 
{ 
  char **its ;
  void *tmp ;
  void *tmp___0 ;

  {
//#line  8
  tmp = malloc((unsigned long )rows * sizeof(char *));
//#line  8
  its = (char **)tmp;
//#line  9
  tmp___0 = malloc((size_t )((rows * cols) * size));
//#line  9
  *(its + 0) = (char *)tmp___0;
//#line  10
  return (its);
}
}
//#line  15 "scope4.c"
int ppm_parsecolor(char *colorname , int maxval ) 
{ 
  int p ;

  {
//#line  19
  return (p);
}
}
