/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  11 "scope12.c"
static int unused_word_type[1000]  ;
//#line  13 "scope12.c"
int main(void) 
{ 
  int *x ;

  {
//#line  14
  x = unused_word_type;
//#line  15
  return (0);
}
}
