/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "scope10.c"
int blah(void) ;
//#line  3 "scope10.c"
static float test___0  =    (float )0;
//#line  1 "scope10.c"
int blah(void) 
{ 


  {
//#line  4
  test___0 += (float )1;
//#line  5
  return (0);
}
}
//#line  7 "scope10.c"
static int test  =    0;
//#line  9 "scope10.c"
int main(int argc , char **argv ) 
{ 


  {
//#line  11
  blah();
//#line  12
  test = 1;
//#line  13
  return (0);
}
}
