/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  2 "scope9.c"
int v  =    3;
//#line  10
extern int ( /* missing proto */  abort)() ;
//#line  4 "scope9.c"
int f(void) 
{ 
  int v___0 ;

  {
//#line  6
  v___0 = 4;
//#line  9
  if (v != 3) {
//#line  10
    abort();
  }
//#line  12
  return (0);
}
}
//#line  17
extern int ( /* missing proto */  exit)() ;
//#line  14 "scope9.c"
int main(void) 
{ 


  {
//#line  16
  f();
//#line  17
  exit(0);
}
}
