/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  2 "scope5.c"
int *external(int *x ) ;
//#line  5 "scope5.c"
int foo(int *y ) 
{ 
  int (*local1)() ;
  int (*local2[4])() ;
  int *tmp ;

  {
//#line  7
  local1 = (int (*)())0;
//#line  10
  local2[0] = local1;
//#line  12
  tmp = external(y);
//#line  12
  return (*tmp);
}
}
//#line  15 "scope5.c"
int *external(int *x ) 
{ 


  {
//#line  18
  return (x + 1);
}
}
//#line  23 "scope5.c"
int main(void) 
{ 
  int x[2] ;
  int tmp ;
  int tmp___0 ;

  {
//#line  25
  x[0] = 1;
//#line  26
  x[1] = 7;
//#line  27
  tmp = foo(x);
//#line  27
  if (tmp == 7) {
//#line  27
    tmp___0 = 0;
  } else {
//#line  27
    tmp___0 = 1;
  }
//#line  27
  return (tmp___0);
}
}
