/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  2 "semicolon.c"
struct foo {
   int g ;
   char *d ;
};
//#line  2 "semicolon.c"
struct foo x  ;
//#line  8 "semicolon.c"
int main(void) 
{ 


  {
//#line  9
  x.g = 1;
//#line  10
  return (0);
}
}
