/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  6 "shell-escape.c"
int main(void) 
{ 


  {
//#line  8
  printf((char const   */* __restrict  */)"Success\n");
//#line  8
  exit(0);
}
}
