/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "simon6.c"
extern void printf(char *fmt  , ...) ;
//#line  5
/* #pragma ccuredvararg("printf",printf(1)) */
//#line  6
extern void exit(int  ) ;
//#line  8 "simon6.c"
int argc  ;
//#line  10 "simon6.c"
void main(void) 
{ 
  int n ;
  int i ;
  int a[10] ;
  int *p ;
  int *tmp ;

  {
//#line  12
  n = argc;
//#line  15
  if (argc % 2) {
//#line  15
    tmp = (int *)0;
  } else {
//#line  15
    tmp = a;
  }
//#line  15
  p = tmp;
//#line  17
  a[0] = 10;
//#line  18
  printf((char *)"%d\n", *(p + 0));
//#line  22
  i = 0;
//#line  22
  while (i < 10) {
//#line  23
    a[i] = (i * 3 + 1) % 10;
//#line  24
    printf((char *)"[%d:%d]", i, *(p + i));
//#line  22
    i ++;
  }
//#line  26
  exit(0);
}
}
