/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  2 "simplify_structs1.c"
struct two {
   int i_1 ;
   int i_2 ;
};
//#line  7 "simplify_structs1.c"
struct nosplit {
   int i_5 ;
   int i_6[10] ;
};
//#line  14 "simplify_structs1.c"
struct three {
   int i_0 ;
   struct two i_1and2 ;
   struct nosplit i_56 ;
};
//#line  20 "simplify_structs1.c"
struct three global  =    {0, {10, 20}, {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}};
//#line  22
extern struct three bar(int argi_0 , int argi_1 , int argi_2 , struct nosplit argi_56 ) ;
//#line  23
extern void barvoid(int argi_0 , int argi_1 , int argi_2 , struct nosplit argi_56 ) ;
//#line  25
extern struct three externstruct ;
//#line  27 "simplify_structs1.c"
int main(void) 
{ 
  struct three local1 ;
  struct three local2 ;
  struct three local3 ;
  struct nosplit local1_i_564 ;
  int local1_i_25 ;
  int local1_i_16 ;
  int local1_i_07 ;
  struct nosplit local2_i_568 ;
  int local2_i_29 ;
  int local2_i_110 ;
  int local2_i_011 ;

  {
//#line  28
  local1_i_07 = externstruct.i_0;
//#line  28
  local1_i_16 = externstruct.i_1and2.i_1;
//#line  28
  local1_i_25 = externstruct.i_1and2.i_2;
//#line  28
  local1_i_564 = externstruct.i_56;
//#line  29
  local2_i_011 = externstruct.i_0;
//#line  29
  local2_i_110 = externstruct.i_1and2.i_1;
//#line  29
  local2_i_29 = externstruct.i_1and2.i_2;
//#line  29
  local2_i_568 = externstruct.i_56;
//#line  30
  local3.i_0 = local2_i_011;
//#line  30
  local3.i_1and2.i_1 = local2_i_110;
//#line  30
  local3.i_1and2.i_2 = local2_i_29;
//#line  30
  local3.i_56 = local2_i_568;
//#line  32
  barvoid(local1_i_07, local1_i_16, local1_i_25, local1_i_564);
//#line  33
  local3 = bar(local2_i_011, local2_i_110, local2_i_29, local2_i_568);
//#line  35
  barvoid(global.i_0, global.i_1and2.i_1, global.i_1and2.i_2, global.i_56);
//#line  37
  externstruct = bar(externstruct.i_0, externstruct.i_1and2.i_1, externstruct.i_1and2.i_2,
                     externstruct.i_56);
//#line  40
  return (0);
}
}
