/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "simplify_volatile.c"
struct M {
   int foo[1] ;
};
//#line  1 "simplify_volatile.c"
struct M  volatile  m  ;
//#line  5 "simplify_volatile.c"
int main(void) 
{ 
  struct M  volatile  *__cil_tmp1 ;
  int ( volatile  (*__cil_tmp2))[1] ;

  {
  {
//#line  7
  __cil_tmp1 = & m;
//#line  7
  __cil_tmp2 = (int ( volatile  (*))[1])__cil_tmp1;
//#line  7
  return ((int )__cil_tmp2);
  }
}
}
