/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  8 "sizeof3.c"
char tab[1000000000]  ;
//#line  11 "sizeof3.c"
char foo[sizeof(tab)]  ;
//#line  15 "sizeof3.c"
int main(void) 
{ 
  int i ;

  {
//#line  18
  tab[999999999] = foo[5];
//#line  19
  i = (int )sizeof(tab);
//#line  21
  return (0);
}
}
