/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  20 "static2.c"
struct s {
   int c ;
};
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "static2.c"
int f1(void) 
{ 


  {
//#line  3
  return (1);
}
}
//#line  6
static int bar(void) ;
//#line  7
int foo(void) ;
//#line  7 "static2.c"
static int (*pbar___0)()  =    (int (*)())(& f1);
//#line  5 "static2.c"
int foo(void) 
{ 
  int tmp ;
  int tmp___0 ;

  {
//#line  9
  tmp = bar();
//#line  9
  tmp___0 = (*pbar___0)();
//#line  9
  return (tmp + tmp___0);
}
}
//#line  12 "static2.c"
static int bar(void) 
{ 


  {
//#line  13
  return (55);
}
}
//#line  16 "static2.c"
static int (*pbar)()  =    (int (*)())(& bar);
//#line  23 "static2.c"
static char device[4UL]  ;
//#line  21 "static2.c"
void qux(void) 
{ 


  {
//#line  24
  device[0] = (char)0;
//#line  25
  return;
}
}
//#line  27 "static2.c"
int main(void) 
{ 
  int tmp ;
  int tmp___0 ;

  {
//#line  28
  tmp = foo();
//#line  28
  if (tmp != 56) {
//#line  28
    printf("Error %d\n", 1);
//#line  28
    exit(1);
  }
//#line  30
  tmp___0 = (*pbar)();
//#line  30
  if (tmp___0 != 55) {
//#line  30
    printf("Error %d\n", 2);
//#line  30
    exit(2);
  }
//#line  32
  qux();
//#line  34
  printf("Success\n");
//#line  34
  exit(0);
}
}
