/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  4 "static.c"
int counter(void) ;
//#line  4 "static.c"
static int counter___0  =    18;
//#line  3 "static.c"
int counter(void) 
{ 


  {
//#line  5
  counter___0 ++;
//#line  6
  return (counter___0);
}
}
//#line  10 "static.c"
int s1  =    17;
//#line  13
int sets1(void) ;
//#line  13 "static.c"
static int s1___0  =    5;
//#line  14 "static.c"
static int s2___0  ;
//#line  16
int sets1(void) ;
//#line  16 "static.c"
static int counter___1  =    29;
//#line  12 "static.c"
int sets1(void) 
{ 


  {
//#line  18
  s2___0 ++;
//#line  20
  return (s1___0 + counter___1);
}
}
//#line  23 "static.c"
static int s2  ;
//#line  26 "static.c"
int main(void) 
{ 
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
//#line  27
  s2 = 28;
//#line  29
  tmp = counter();
//#line  29
  if (tmp != 19) {
//#line  29
    printf("Error %d\n", 1);
//#line  29
    exit(1);
  }
//#line  30
  tmp___0 = counter();
//#line  30
  if (tmp___0 != 20) {
//#line  30
    printf("Error %d\n", 2);
//#line  30
    exit(2);
  }
//#line  31
  tmp___1 = sets1();
//#line  31
  if (tmp___1 != 34) {
//#line  31
    printf("Error %d\n", 3);
//#line  31
    exit(3);
  }
//#line  34
  if (s1 != 17) {
//#line  34
    printf("Error %d\n", 4);
//#line  34
    exit(4);
  }
//#line  37
  if (s2 != 28) {
//#line  37
    printf("Error %d\n", 5);
//#line  37
    exit(5);
  }
//#line  39
  printf("Success\n");
//#line  39
  exit(0);
}
}
