/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "static1.c"
int foo(void) ;
//#line  3 "static1.c"
static int x  =    0;
//#line  1 "static1.c"
int foo(void) 
{ 


  {
//#line  4
  return (x);
}
}
//#line  9
int bar(void) ;
//#line  9 "static1.c"
static int x___0  =    5;
//#line  7 "static1.c"
int bar(void) 
{ 


  {
//#line  10
  return (x___0);
}
}
