/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  2 "strcpy.c"
char *mod_gzip_strcpy(char *s1 , char *s2 ) 
{ 
  int len ;
  char *tmp ;
  char *tmp___0 ;
  char *tmp___1 ;
  char *tmp___2 ;

  {
//#line  4
  len = 0;
//#line  5
  if ((unsigned long )s1 != (unsigned long )((char *)0)) {
//#line  5
    if ((unsigned long )s2 != (unsigned long )((char *)0)) {
//#line  7
      while ((int )*s2 != 0) {
//#line  7
        tmp = s1;
//#line  7
        s1 ++;
//#line  7
        tmp___0 = s2;
//#line  7
        s2 ++;
//#line  7
        *tmp = *tmp___0;
//#line  7
        len ++;
      }
//#line  8
      *s1 = (char)0;
    }
  }
//#line  10
  tmp___1 = mod_gzip_strcpy(s1, s1);
//#line  10
  tmp___2 = mod_gzip_strcpy(tmp___1, s2);
//#line  10
  return (tmp___2);
}
}
//#line  13
extern int puts(char *s ) ;
//#line  15 "strcpy.c"
int main(void) 
{ 
  char *x ;
  char *y ;

  {
//#line  19
  y = mod_gzip_strcpy(x, (char *)"/tmp/");
//#line  20
  puts(y);
//#line  22
  return (1);
}
}
