/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  7 "stringsize.c"
extern int strcmp(char const   * , char const   * ) ;
//#line  10 "stringsize.c"
int main(void) 
{ 
  char tmp[sizeof("a string literal for testing.")] ;
  int tmp___0 ;

  {
//#line  12
  tmp[0] = (char )'a';
//#line  12
  tmp[1] = (char )' ';
//#line  12
  tmp[2] = (char )'s';
//#line  12
  tmp[3] = (char )'t';
//#line  12
  tmp[4] = (char )'r';
//#line  12
  tmp[5] = (char )'i';
//#line  12
  tmp[6] = (char )'n';
//#line  12
  tmp[7] = (char )'g';
//#line  12
  tmp[8] = (char )' ';
//#line  12
  tmp[9] = (char )'l';
//#line  12
  tmp[10] = (char )'i';
//#line  12
  tmp[11] = (char )'t';
//#line  12
  tmp[12] = (char )'e';
//#line  12
  tmp[13] = (char )'r';
//#line  12
  tmp[14] = (char )'a';
//#line  12
  tmp[15] = (char )'l';
//#line  12
  tmp[16] = (char )' ';
//#line  12
  tmp[17] = (char )'f';
//#line  12
  tmp[18] = (char )'o';
//#line  12
  tmp[19] = (char )'r';
//#line  12
  tmp[20] = (char )' ';
//#line  12
  tmp[21] = (char )'t';
//#line  12
  tmp[22] = (char )'e';
//#line  12
  tmp[23] = (char )'s';
//#line  12
  tmp[24] = (char )'t';
//#line  12
  tmp[25] = (char )'i';
//#line  12
  tmp[26] = (char )'n';
//#line  12
  tmp[27] = (char )'g';
//#line  12
  tmp[28] = (char )'.';
//#line  12
  tmp[29] = (char )'\000';
//#line  14
  tmp___0 = strcmp("a string literal for testing.", (char const   *)(tmp));
//#line  14
  if (tmp___0) {
//#line  14
    printf("Error %d\n", 1);
//#line  14
    exit(1);
  }
//#line  18
  if (sizeof(tmp) != 30UL) {
//#line  18
    printf("Error %d\n", 2);
//#line  18
    exit(2);
  }
//#line  19
  if ((int )tmp[10] != (int )*("a string literal for testing." + 10)) {
//#line  19
    printf("Error %d\n", 3);
//#line  19
    exit(3);
  }
//#line  22
  if (sizeof("Hello, world.") != 14UL) {
//#line  22
    printf("Error %d\n", 4);
//#line  22
    exit(4);
  }
//#line  25
  if (sizeof((char *)"Hello, world.") != sizeof(void *)) {
//#line  25
    printf("Error %d\n", 5);
//#line  25
    exit(5);
  }
//#line  27
  printf("%d\n", sizeof("ertewrtert"));
//#line  29
  printf("Success\n");
//#line  29
  exit(0);
}
}
