/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  4 "strloop.c"
void BuildWord(char *pchWord ) 
{ 
  int i ;
  char *pch ;

  {
//#line  6
  pch = pchWord;
//#line  12
  while (1) {
//#line  13
    i = (int )*pch;
//#line  15
    pch ++;
//#line  12
    if (! (i != 0)) {
//#line  12
      break;
    }
  }
//#line  18
  printf((char const   */* __restrict  */)"%s\n", pchWord);
//#line  19
  return;
}
}
//#line  21 "strloop.c"
int main(void) 
{ 
  char *test ;

  {
//#line  22
  test = (char *)"foo";
//#line  24
  test ++;
//#line  25
  test --;
//#line  27
  BuildWord(test);
//#line  29
  printf((char const   */* __restrict  */)"Success\n");
//#line  29
  exit(0);
}
}
