/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  5 "struct_init.c"
struct __anonstruct_cmd_488594144 {
   char *name ;
   int data ;
};
//#line  5 "struct_init.c"
typedef struct __anonstruct_cmd_488594144 cmd;
//#line  16 "struct_init.c"
struct __anonstruct_main_struct_561313254 {
   int x ;
   cmd *cmds ;
   int y ;
};
//#line  10 "struct_init.c"
cmd our_cmds[4]  = {      {(char *)"command 1", 1}, 
        {(char *)"command 2", 2}, 
        {(char *)"command 3", 3}, 
        {(char *)0, 0}};
//#line  16 "struct_init.c"
struct __anonstruct_main_struct_561313254 main_struct  =    {100, our_cmds, 200};
//#line  26 "struct_init.c"
int main(void) 
{ 
  char *p ;

  {
//#line  27
  p = (char *)"HELLO";
//#line  28
  return (0);
}
}
