/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  2 "structassign.c"
struct __anonstruct_STR_773697287 {
   int *a[20] ;
   int b ;
};
//#line  2 "structassign.c"
typedef struct __anonstruct_STR_773697287 STR;
//#line  7 "structassign.c"
STR glob  ;
//#line  10 "structassign.c"
int main(STR *s ) 
{ 
  STR loc ;

  {
//#line  11
  loc = glob;
//#line  13
  *s = glob;
//#line  15
  return (0);
}
}
