/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "struct1.c"
struct __anonstruct_pte_t_143082958 {
   unsigned long pte_low ;
};
//#line  3 "struct1.c"
typedef struct __anonstruct_pte_t_143082958 pte_t;
//#line  6 "struct1.c"
struct __anonstruct_pgprot_t_143082959 {
   unsigned long pgprot ;
};
//#line  6 "struct1.c"
typedef struct __anonstruct_pgprot_t_143082959 pgprot_t;
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  9 "struct1.c"
int main(void) 
{ 
  pte_t one ;
  pte_t *pte ;
  pte_t __constr_expr_0 ;
  pgprot_t __constr_expr_1 ;

  {
//#line  11
  pte = & one;
//#line  13
  __constr_expr_1.pgprot = 37UL;
//#line  13
  __constr_expr_0.pte_low = __constr_expr_1.pgprot;
//#line  13
  *pte = __constr_expr_0;
//#line  16
  if (pte->pte_low != 37UL) {
//#line  16
    printf("Error %d\n", 1);
//#line  16
    exit(1);
  }
//#line  18
  printf("Success\n");
//#line  18
  exit(0);
}
}
