/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  21 "sync-1.c"
struct S {
   struct S *next ;
   int x ;
};
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_and_and_fetch(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_or(...) ;  */
/* compiler builtin: 
   void __sync_synchronize(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_or_and_fetch(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_add_and_fetch(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_nand(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_sub_and_fetch(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_nand_and_fetch(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_xor_and_fetch(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_and(...) ;  */
/* compiler builtin: 
   void __sync_lock_release(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_xor(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_val_compare_and_swap(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_lock_test_and_set(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_add(...) ;  */
/* compiler builtin: 
   _Bool __sync_bool_compare_and_swap(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_sub(...) ;  */
//#line  9 "sync-1.c"
signed char sc  ;
//#line  10 "sync-1.c"
unsigned char uc  ;
//#line  11 "sync-1.c"
short ss  ;
//#line  12 "sync-1.c"
unsigned short us  ;
//#line  13 "sync-1.c"
int si  ;
//#line  14 "sync-1.c"
unsigned int ui  ;
//#line  15 "sync-1.c"
long sl  ;
//#line  16 "sync-1.c"
unsigned long ul  ;
//#line  17 "sync-1.c"
long long sll  ;
//#line  18 "sync-1.c"
unsigned long long ull  ;
//#line  19 "sync-1.c"
void *vp  ;
//#line  20 "sync-1.c"
int *ip  ;
//#line  21 "sync-1.c"
struct S *sp  ;
//#line  23 "sync-1.c"
void test_op_ignore(void) 
{ 


  {
//#line  25
  __sync_fetch_and_add(& sc, 1);
//#line  26
  __sync_fetch_and_add(& uc, 1);
//#line  27
  __sync_fetch_and_add(& ss, 1);
//#line  28
  __sync_fetch_and_add(& us, 1);
//#line  29
  __sync_fetch_and_add(& si, 1);
//#line  30
  __sync_fetch_and_add(& ui, 1);
//#line  31
  __sync_fetch_and_add(& sl, 1);
//#line  32
  __sync_fetch_and_add(& ul, 1);
//#line  33
  __sync_fetch_and_add(& sll, 1);
//#line  34
  __sync_fetch_and_add(& ull, 1);
//#line  36
  __sync_fetch_and_sub(& sc, 1);
//#line  37
  __sync_fetch_and_sub(& uc, 1);
//#line  38
  __sync_fetch_and_sub(& ss, 1);
//#line  39
  __sync_fetch_and_sub(& us, 1);
//#line  40
  __sync_fetch_and_sub(& si, 1);
//#line  41
  __sync_fetch_and_sub(& ui, 1);
//#line  42
  __sync_fetch_and_sub(& sl, 1);
//#line  43
  __sync_fetch_and_sub(& ul, 1);
//#line  44
  __sync_fetch_and_sub(& sll, 1);
//#line  45
  __sync_fetch_and_sub(& ull, 1);
//#line  47
  __sync_fetch_and_or(& sc, 1);
//#line  48
  __sync_fetch_and_or(& uc, 1);
//#line  49
  __sync_fetch_and_or(& ss, 1);
//#line  50
  __sync_fetch_and_or(& us, 1);
//#line  51
  __sync_fetch_and_or(& si, 1);
//#line  52
  __sync_fetch_and_or(& ui, 1);
//#line  53
  __sync_fetch_and_or(& sl, 1);
//#line  54
  __sync_fetch_and_or(& ul, 1);
//#line  55
  __sync_fetch_and_or(& sll, 1);
//#line  56
  __sync_fetch_and_or(& ull, 1);
//#line  58
  __sync_fetch_and_xor(& sc, 1);
//#line  59
  __sync_fetch_and_xor(& uc, 1);
//#line  60
  __sync_fetch_and_xor(& ss, 1);
//#line  61
  __sync_fetch_and_xor(& us, 1);
//#line  62
  __sync_fetch_and_xor(& si, 1);
//#line  63
  __sync_fetch_and_xor(& ui, 1);
//#line  64
  __sync_fetch_and_xor(& sl, 1);
//#line  65
  __sync_fetch_and_xor(& ul, 1);
//#line  66
  __sync_fetch_and_xor(& sll, 1);
//#line  67
  __sync_fetch_and_xor(& ull, 1);
//#line  69
  __sync_fetch_and_and(& sc, 1);
//#line  70
  __sync_fetch_and_and(& uc, 1);
//#line  71
  __sync_fetch_and_and(& ss, 1);
//#line  72
  __sync_fetch_and_and(& us, 1);
//#line  73
  __sync_fetch_and_and(& si, 1);
//#line  74
  __sync_fetch_and_and(& ui, 1);
//#line  75
  __sync_fetch_and_and(& sl, 1);
//#line  76
  __sync_fetch_and_and(& ul, 1);
//#line  77
  __sync_fetch_and_and(& sll, 1);
//#line  78
  __sync_fetch_and_and(& ull, 1);
//#line  80
  __sync_fetch_and_nand(& sc, 1);
//#line  81
  __sync_fetch_and_nand(& uc, 1);
//#line  82
  __sync_fetch_and_nand(& ss, 1);
//#line  83
  __sync_fetch_and_nand(& us, 1);
//#line  84
  __sync_fetch_and_nand(& si, 1);
//#line  85
  __sync_fetch_and_nand(& ui, 1);
//#line  86
  __sync_fetch_and_nand(& sl, 1);
//#line  87
  __sync_fetch_and_nand(& ul, 1);
//#line  88
  __sync_fetch_and_nand(& sll, 1);
//#line  89
  __sync_fetch_and_nand(& ull, 1);
//#line  90
  return;
}
}
//#line  92 "sync-1.c"
void test_fetch_and_op(void) 
{ 


  {
//#line  94
  sc = (signed char )__sync_fetch_and_add(& sc, 11);
//#line  95
  uc = (unsigned char )__sync_fetch_and_add(& uc, 11);
//#line  96
  ss = (short )__sync_fetch_and_add(& ss, 11);
//#line  97
  us = (unsigned short )__sync_fetch_and_add(& us, 11);
//#line  98
  si = (int )__sync_fetch_and_add(& si, 11);
//#line  99
  ui = (unsigned int )__sync_fetch_and_add(& ui, 11);
//#line  100
  sl = (long )__sync_fetch_and_add(& sl, 11);
//#line  101
  ul = (unsigned long )__sync_fetch_and_add(& ul, 11);
//#line  102
  sll = (long long )__sync_fetch_and_add(& sll, 11);
//#line  103
  ull = (unsigned long long )__sync_fetch_and_add(& ull, 11);
//#line  105
  sc = (signed char )__sync_fetch_and_sub(& sc, 11);
//#line  106
  uc = (unsigned char )__sync_fetch_and_sub(& uc, 11);
//#line  107
  ss = (short )__sync_fetch_and_sub(& ss, 11);
//#line  108
  us = (unsigned short )__sync_fetch_and_sub(& us, 11);
//#line  109
  si = (int )__sync_fetch_and_sub(& si, 11);
//#line  110
  ui = (unsigned int )__sync_fetch_and_sub(& ui, 11);
//#line  111
  sl = (long )__sync_fetch_and_sub(& sl, 11);
//#line  112
  ul = (unsigned long )__sync_fetch_and_sub(& ul, 11);
//#line  113
  sll = (long long )__sync_fetch_and_sub(& sll, 11);
//#line  114
  ull = (unsigned long long )__sync_fetch_and_sub(& ull, 11);
//#line  116
  sc = (signed char )__sync_fetch_and_or(& sc, 11);
//#line  117
  uc = (unsigned char )__sync_fetch_and_or(& uc, 11);
//#line  118
  ss = (short )__sync_fetch_and_or(& ss, 11);
//#line  119
  us = (unsigned short )__sync_fetch_and_or(& us, 11);
//#line  120
  si = (int )__sync_fetch_and_or(& si, 11);
//#line  121
  ui = (unsigned int )__sync_fetch_and_or(& ui, 11);
//#line  122
  sl = (long )__sync_fetch_and_or(& sl, 11);
//#line  123
  ul = (unsigned long )__sync_fetch_and_or(& ul, 11);
//#line  124
  sll = (long long )__sync_fetch_and_or(& sll, 11);
//#line  125
  ull = (unsigned long long )__sync_fetch_and_or(& ull, 11);
//#line  127
  sc = (signed char )__sync_fetch_and_xor(& sc, 11);
//#line  128
  uc = (unsigned char )__sync_fetch_and_xor(& uc, 11);
//#line  129
  ss = (short )__sync_fetch_and_xor(& ss, 11);
//#line  130
  us = (unsigned short )__sync_fetch_and_xor(& us, 11);
//#line  131
  si = (int )__sync_fetch_and_xor(& si, 11);
//#line  132
  ui = (unsigned int )__sync_fetch_and_xor(& ui, 11);
//#line  133
  sl = (long )__sync_fetch_and_xor(& sl, 11);
//#line  134
  ul = (unsigned long )__sync_fetch_and_xor(& ul, 11);
//#line  135
  sll = (long long )__sync_fetch_and_xor(& sll, 11);
//#line  136
  ull = (unsigned long long )__sync_fetch_and_xor(& ull, 11);
//#line  138
  sc = (signed char )__sync_fetch_and_and(& sc, 11);
//#line  139
  uc = (unsigned char )__sync_fetch_and_and(& uc, 11);
//#line  140
  ss = (short )__sync_fetch_and_and(& ss, 11);
//#line  141
  us = (unsigned short )__sync_fetch_and_and(& us, 11);
//#line  142
  si = (int )__sync_fetch_and_and(& si, 11);
//#line  143
  ui = (unsigned int )__sync_fetch_and_and(& ui, 11);
//#line  144
  sl = (long )__sync_fetch_and_and(& sl, 11);
//#line  145
  ul = (unsigned long )__sync_fetch_and_and(& ul, 11);
//#line  146
  sll = (long long )__sync_fetch_and_and(& sll, 11);
//#line  147
  ull = (unsigned long long )__sync_fetch_and_and(& ull, 11);
//#line  149
  sc = (signed char )__sync_fetch_and_nand(& sc, 11);
//#line  150
  uc = (unsigned char )__sync_fetch_and_nand(& uc, 11);
//#line  151
  ss = (short )__sync_fetch_and_nand(& ss, 11);
//#line  152
  us = (unsigned short )__sync_fetch_and_nand(& us, 11);
//#line  153
  si = (int )__sync_fetch_and_nand(& si, 11);
//#line  154
  ui = (unsigned int )__sync_fetch_and_nand(& ui, 11);
//#line  155
  sl = (long )__sync_fetch_and_nand(& sl, 11);
//#line  156
  ul = (unsigned long )__sync_fetch_and_nand(& ul, 11);
//#line  157
  sll = (long long )__sync_fetch_and_nand(& sll, 11);
//#line  158
  ull = (unsigned long long )__sync_fetch_and_nand(& ull, 11);
//#line  159
  return;
}
}
//#line  161 "sync-1.c"
void test_op_and_fetch(void) 
{ 


  {
//#line  163
  sc = (signed char )__sync_add_and_fetch(& sc, (int )uc);
//#line  164
  uc = (unsigned char )__sync_add_and_fetch(& uc, (int )uc);
//#line  165
  ss = (short )__sync_add_and_fetch(& ss, (int )uc);
//#line  166
  us = (unsigned short )__sync_add_and_fetch(& us, (int )uc);
//#line  167
  si = (int )__sync_add_and_fetch(& si, (int )uc);
//#line  168
  ui = (unsigned int )__sync_add_and_fetch(& ui, (int )uc);
//#line  169
  sl = (long )__sync_add_and_fetch(& sl, (int )uc);
//#line  170
  ul = (unsigned long )__sync_add_and_fetch(& ul, (int )uc);
//#line  171
  sll = (long long )__sync_add_and_fetch(& sll, (int )uc);
//#line  172
  ull = (unsigned long long )__sync_add_and_fetch(& ull, (int )uc);
//#line  174
  sc = (signed char )__sync_sub_and_fetch(& sc, (int )uc);
//#line  175
  uc = (unsigned char )__sync_sub_and_fetch(& uc, (int )uc);
//#line  176
  ss = (short )__sync_sub_and_fetch(& ss, (int )uc);
//#line  177
  us = (unsigned short )__sync_sub_and_fetch(& us, (int )uc);
//#line  178
  si = (int )__sync_sub_and_fetch(& si, (int )uc);
//#line  179
  ui = (unsigned int )__sync_sub_and_fetch(& ui, (int )uc);
//#line  180
  sl = (long )__sync_sub_and_fetch(& sl, (int )uc);
//#line  181
  ul = (unsigned long )__sync_sub_and_fetch(& ul, (int )uc);
//#line  182
  sll = (long long )__sync_sub_and_fetch(& sll, (int )uc);
//#line  183
  ull = (unsigned long long )__sync_sub_and_fetch(& ull, (int )uc);
//#line  185
  sc = (signed char )__sync_or_and_fetch(& sc, (int )uc);
//#line  186
  uc = (unsigned char )__sync_or_and_fetch(& uc, (int )uc);
//#line  187
  ss = (short )__sync_or_and_fetch(& ss, (int )uc);
//#line  188
  us = (unsigned short )__sync_or_and_fetch(& us, (int )uc);
//#line  189
  si = (int )__sync_or_and_fetch(& si, (int )uc);
//#line  190
  ui = (unsigned int )__sync_or_and_fetch(& ui, (int )uc);
//#line  191
  sl = (long )__sync_or_and_fetch(& sl, (int )uc);
//#line  192
  ul = (unsigned long )__sync_or_and_fetch(& ul, (int )uc);
//#line  193
  sll = (long long )__sync_or_and_fetch(& sll, (int )uc);
//#line  194
  ull = (unsigned long long )__sync_or_and_fetch(& ull, (int )uc);
//#line  196
  sc = (signed char )__sync_xor_and_fetch(& sc, (int )uc);
//#line  197
  uc = (unsigned char )__sync_xor_and_fetch(& uc, (int )uc);
//#line  198
  ss = (short )__sync_xor_and_fetch(& ss, (int )uc);
//#line  199
  us = (unsigned short )__sync_xor_and_fetch(& us, (int )uc);
//#line  200
  si = (int )__sync_xor_and_fetch(& si, (int )uc);
//#line  201
  ui = (unsigned int )__sync_xor_and_fetch(& ui, (int )uc);
//#line  202
  sl = (long )__sync_xor_and_fetch(& sl, (int )uc);
//#line  203
  ul = (unsigned long )__sync_xor_and_fetch(& ul, (int )uc);
//#line  204
  sll = (long long )__sync_xor_and_fetch(& sll, (int )uc);
//#line  205
  ull = (unsigned long long )__sync_xor_and_fetch(& ull, (int )uc);
//#line  207
  sc = (signed char )__sync_and_and_fetch(& sc, (int )uc);
//#line  208
  uc = (unsigned char )__sync_and_and_fetch(& uc, (int )uc);
//#line  209
  ss = (short )__sync_and_and_fetch(& ss, (int )uc);
//#line  210
  us = (unsigned short )__sync_and_and_fetch(& us, (int )uc);
//#line  211
  si = (int )__sync_and_and_fetch(& si, (int )uc);
//#line  212
  ui = (unsigned int )__sync_and_and_fetch(& ui, (int )uc);
//#line  213
  sl = (long )__sync_and_and_fetch(& sl, (int )uc);
//#line  214
  ul = (unsigned long )__sync_and_and_fetch(& ul, (int )uc);
//#line  215
  sll = (long long )__sync_and_and_fetch(& sll, (int )uc);
//#line  216
  ull = (unsigned long long )__sync_and_and_fetch(& ull, (int )uc);
//#line  218
  sc = (signed char )__sync_nand_and_fetch(& sc, (int )uc);
//#line  219
  uc = (unsigned char )__sync_nand_and_fetch(& uc, (int )uc);
//#line  220
  ss = (short )__sync_nand_and_fetch(& ss, (int )uc);
//#line  221
  us = (unsigned short )__sync_nand_and_fetch(& us, (int )uc);
//#line  222
  si = (int )__sync_nand_and_fetch(& si, (int )uc);
//#line  223
  ui = (unsigned int )__sync_nand_and_fetch(& ui, (int )uc);
//#line  224
  sl = (long )__sync_nand_and_fetch(& sl, (int )uc);
//#line  225
  ul = (unsigned long )__sync_nand_and_fetch(& ul, (int )uc);
//#line  226
  sll = (long long )__sync_nand_and_fetch(& sll, (int )uc);
//#line  227
  ull = (unsigned long long )__sync_nand_and_fetch(& ull, (int )uc);
//#line  228
  return;
}
}
//#line  230 "sync-1.c"
void test_compare_and_swap(void) 
{ 
  _Bool tmp ;
  _Bool tmp___0 ;
  _Bool tmp___1 ;
  _Bool tmp___2 ;
  _Bool tmp___3 ;
  _Bool tmp___4 ;
  _Bool tmp___5 ;
  _Bool tmp___6 ;
  _Bool tmp___7 ;
  _Bool tmp___8 ;

  {
//#line  232
  sc = (signed char )__sync_val_compare_and_swap(& sc, (int )uc, (int )sc);
//#line  233
  uc = (unsigned char )__sync_val_compare_and_swap(& uc, (int )uc, (int )sc);
//#line  234
  ss = (short )__sync_val_compare_and_swap(& ss, (int )uc, (int )sc);
//#line  235
  us = (unsigned short )__sync_val_compare_and_swap(& us, (int )uc, (int )sc);
//#line  236
  si = (int )__sync_val_compare_and_swap(& si, (int )uc, (int )sc);
//#line  237
  ui = (unsigned int )__sync_val_compare_and_swap(& ui, (int )uc, (int )sc);
//#line  238
  sl = (long )__sync_val_compare_and_swap(& sl, (int )uc, (int )sc);
//#line  239
  ul = (unsigned long )__sync_val_compare_and_swap(& ul, (int )uc, (int )sc);
//#line  240
  sll = (long long )__sync_val_compare_and_swap(& sll, (int )uc, (int )sc);
//#line  241
  ull = (unsigned long long )__sync_val_compare_and_swap(& ull, (int )uc, (int )sc);
//#line  243
  tmp = __sync_bool_compare_and_swap(& sc, (int )uc, (int )sc);
//#line  243
  ui = (unsigned int )tmp;
//#line  244
  tmp___0 = __sync_bool_compare_and_swap(& uc, (int )uc, (int )sc);
//#line  244
  ui = (unsigned int )tmp___0;
//#line  245
  tmp___1 = __sync_bool_compare_and_swap(& ss, (int )uc, (int )sc);
//#line  245
  ui = (unsigned int )tmp___1;
//#line  246
  tmp___2 = __sync_bool_compare_and_swap(& us, (int )uc, (int )sc);
//#line  246
  ui = (unsigned int )tmp___2;
//#line  247
  tmp___3 = __sync_bool_compare_and_swap(& si, (int )uc, (int )sc);
//#line  247
  ui = (unsigned int )tmp___3;
//#line  248
  tmp___4 = __sync_bool_compare_and_swap(& ui, (int )uc, (int )sc);
//#line  248
  ui = (unsigned int )tmp___4;
//#line  249
  tmp___5 = __sync_bool_compare_and_swap(& sl, (int )uc, (int )sc);
//#line  249
  ui = (unsigned int )tmp___5;
//#line  250
  tmp___6 = __sync_bool_compare_and_swap(& ul, (int )uc, (int )sc);
//#line  250
  ui = (unsigned int )tmp___6;
//#line  251
  tmp___7 = __sync_bool_compare_and_swap(& sll, (int )uc, (int )sc);
//#line  251
  ui = (unsigned int )tmp___7;
//#line  252
  tmp___8 = __sync_bool_compare_and_swap(& ull, (int )uc, (int )sc);
//#line  252
  ui = (unsigned int )tmp___8;
//#line  253
  return;
}
}
//#line  255 "sync-1.c"
void test_lock(void) 
{ 


  {
//#line  257
  sc = (signed char )__sync_lock_test_and_set(& sc, 1);
//#line  258
  uc = (unsigned char )__sync_lock_test_and_set(& uc, 1);
//#line  259
  ss = (short )__sync_lock_test_and_set(& ss, 1);
//#line  260
  us = (unsigned short )__sync_lock_test_and_set(& us, 1);
//#line  261
  si = (int )__sync_lock_test_and_set(& si, 1);
//#line  262
  ui = (unsigned int )__sync_lock_test_and_set(& ui, 1);
//#line  263
  sl = (long )__sync_lock_test_and_set(& sl, 1);
//#line  264
  ul = (unsigned long )__sync_lock_test_and_set(& ul, 1);
//#line  265
  sll = (long long )__sync_lock_test_and_set(& sll, 1);
//#line  266
  ull = (unsigned long long )__sync_lock_test_and_set(& ull, 1);
//#line  268
  __sync_synchronize();
//#line  270
  __sync_lock_release(& sc);
//#line  271
  __sync_lock_release(& uc);
//#line  272
  __sync_lock_release(& ss);
//#line  273
  __sync_lock_release(& us);
//#line  274
  __sync_lock_release(& si);
//#line  275
  __sync_lock_release(& ui);
//#line  276
  __sync_lock_release(& sl);
//#line  277
  __sync_lock_release(& ul);
//#line  278
  __sync_lock_release(& sll);
//#line  279
  __sync_lock_release(& ull);
//#line  280
  return;
}
}
