/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_or(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_nand(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_and(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_xor(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_lock_test_and_set(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_add(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_sub(...) ;  */
//#line  8 "sync-3.c"
void test_op_ignore(void) 
{ 
  signed char sc[2] ;
  unsigned char uc[2] ;
  short ss[2] ;
  unsigned short us[2] ;
  int si[2] ;
  unsigned int ui[2] ;
  long sl[2] ;
  unsigned long ul[2] ;
  long long sll[2] ;
  unsigned long long ull[2] ;

  {
//#line  20
  __sync_fetch_and_add(& sc[1], -1);
//#line  21
  __sync_fetch_and_add(& uc[1], -1);
//#line  22
  __sync_fetch_and_add(& ss[1], -1);
//#line  23
  __sync_fetch_and_add(& us[1], -1);
//#line  24
  __sync_fetch_and_add(& si[1], -1);
//#line  25
  __sync_fetch_and_add(& ui[1], -1);
//#line  26
  __sync_fetch_and_add(& sl[1], -1);
//#line  27
  __sync_fetch_and_add(& ul[1], -1);
//#line  28
  __sync_fetch_and_add(& sll[1], -1);
//#line  29
  __sync_fetch_and_add(& ull[1], -1);
//#line  31
  __sync_fetch_and_sub(& sc[1], -1);
//#line  32
  __sync_fetch_and_sub(& uc[1], -1);
//#line  33
  __sync_fetch_and_sub(& ss[1], -1);
//#line  34
  __sync_fetch_and_sub(& us[1], -1);
//#line  35
  __sync_fetch_and_sub(& si[1], -1);
//#line  36
  __sync_fetch_and_sub(& ui[1], -1);
//#line  37
  __sync_fetch_and_sub(& sl[1], -1);
//#line  38
  __sync_fetch_and_sub(& ul[1], -1);
//#line  39
  __sync_fetch_and_sub(& sll[1], -1);
//#line  40
  __sync_fetch_and_sub(& ull[1], -1);
//#line  42
  __sync_fetch_and_or(& sc[1], -1);
//#line  43
  __sync_fetch_and_or(& uc[1], -1);
//#line  44
  __sync_fetch_and_or(& ss[1], -1);
//#line  45
  __sync_fetch_and_or(& us[1], -1);
//#line  46
  __sync_fetch_and_or(& si[1], -1);
//#line  47
  __sync_fetch_and_or(& ui[1], -1);
//#line  48
  __sync_fetch_and_or(& sl[1], -1);
//#line  49
  __sync_fetch_and_or(& ul[1], -1);
//#line  50
  __sync_fetch_and_or(& sll[1], -1);
//#line  51
  __sync_fetch_and_or(& ull[1], -1);
//#line  53
  __sync_fetch_and_xor(& sc[1], -1);
//#line  54
  __sync_fetch_and_xor(& uc[1], -1);
//#line  55
  __sync_fetch_and_xor(& ss[1], -1);
//#line  56
  __sync_fetch_and_xor(& us[1], -1);
//#line  57
  __sync_fetch_and_xor(& si[1], -1);
//#line  58
  __sync_fetch_and_xor(& ui[1], -1);
//#line  59
  __sync_fetch_and_xor(& sl[1], -1);
//#line  60
  __sync_fetch_and_xor(& ul[1], -1);
//#line  61
  __sync_fetch_and_xor(& sll[1], -1);
//#line  62
  __sync_fetch_and_xor(& ull[1], -1);
//#line  64
  __sync_fetch_and_and(& sc[1], -1);
//#line  65
  __sync_fetch_and_and(& uc[1], -1);
//#line  66
  __sync_fetch_and_and(& ss[1], -1);
//#line  67
  __sync_fetch_and_and(& us[1], -1);
//#line  68
  __sync_fetch_and_and(& si[1], -1);
//#line  69
  __sync_fetch_and_and(& ui[1], -1);
//#line  70
  __sync_fetch_and_and(& sl[1], -1);
//#line  71
  __sync_fetch_and_and(& ul[1], -1);
//#line  72
  __sync_fetch_and_and(& sll[1], -1);
//#line  73
  __sync_fetch_and_and(& ull[1], -1);
//#line  75
  __sync_fetch_and_nand(& sc[1], -1);
//#line  76
  __sync_fetch_and_nand(& uc[1], -1);
//#line  77
  __sync_fetch_and_nand(& ss[1], -1);
//#line  78
  __sync_fetch_and_nand(& us[1], -1);
//#line  79
  __sync_fetch_and_nand(& si[1], -1);
//#line  80
  __sync_fetch_and_nand(& ui[1], -1);
//#line  81
  __sync_fetch_and_nand(& sl[1], -1);
//#line  82
  __sync_fetch_and_nand(& ul[1], -1);
//#line  83
  __sync_fetch_and_nand(& sll[1], -1);
//#line  84
  __sync_fetch_and_nand(& ull[1], -1);
//#line  85
  return;
}
}
//#line  87 "sync-3.c"
void test_fetch_and_op(void) 
{ 
  signed char sc[2] ;
  unsigned char uc[2] ;
  short ss[2] ;
  unsigned short us[2] ;
  int si[2] ;
  unsigned int ui[2] ;
  long sl[2] ;
  unsigned long ul[2] ;
  long long sll[2] ;
  unsigned long long ull[2] ;

  {
//#line  99
  sc[1] = (signed char )__sync_fetch_and_add(& sc[1], -11);
//#line  100
  uc[1] = (unsigned char )__sync_fetch_and_add(& uc[1], -11);
//#line  101
  ss[1] = (short )__sync_fetch_and_add(& ss[1], -11);
//#line  102
  us[1] = (unsigned short )__sync_fetch_and_add(& us[1], -11);
//#line  103
  si[1] = (int )__sync_fetch_and_add(& si[1], -11);
//#line  104
  ui[1] = (unsigned int )__sync_fetch_and_add(& ui[1], -11);
//#line  105
  sl[1] = (long )__sync_fetch_and_add(& sl[1], -11);
//#line  106
  ul[1] = (unsigned long )__sync_fetch_and_add(& ul[1], -11);
//#line  107
  sll[1] = (long long )__sync_fetch_and_add(& sll[1], -11);
//#line  108
  ull[1] = (unsigned long long )__sync_fetch_and_add(& ull[1], -11);
//#line  110
  sc[1] = (signed char )__sync_fetch_and_sub(& sc[1], -11);
//#line  111
  uc[1] = (unsigned char )__sync_fetch_and_sub(& uc[1], -11);
//#line  112
  ss[1] = (short )__sync_fetch_and_sub(& ss[1], -11);
//#line  113
  us[1] = (unsigned short )__sync_fetch_and_sub(& us[1], -11);
//#line  114
  si[1] = (int )__sync_fetch_and_sub(& si[1], -11);
//#line  115
  ui[1] = (unsigned int )__sync_fetch_and_sub(& ui[1], -11);
//#line  116
  sl[1] = (long )__sync_fetch_and_sub(& sl[1], -11);
//#line  117
  ul[1] = (unsigned long )__sync_fetch_and_sub(& ul[1], -11);
//#line  118
  sll[1] = (long long )__sync_fetch_and_sub(& sll[1], -11);
//#line  119
  ull[1] = (unsigned long long )__sync_fetch_and_sub(& ull[1], -11);
//#line  121
  sc[1] = (signed char )__sync_fetch_and_or(& sc[1], -11);
//#line  122
  uc[1] = (unsigned char )__sync_fetch_and_or(& uc[1], -11);
//#line  123
  ss[1] = (short )__sync_fetch_and_or(& ss[1], -11);
//#line  124
  us[1] = (unsigned short )__sync_fetch_and_or(& us[1], -11);
//#line  125
  si[1] = (int )__sync_fetch_and_or(& si[1], -11);
//#line  126
  ui[1] = (unsigned int )__sync_fetch_and_or(& ui[1], -11);
//#line  127
  sl[1] = (long )__sync_fetch_and_or(& sl[1], -11);
//#line  128
  ul[1] = (unsigned long )__sync_fetch_and_or(& ul[1], -11);
//#line  129
  sll[1] = (long long )__sync_fetch_and_or(& sll[1], -11);
//#line  130
  ull[1] = (unsigned long long )__sync_fetch_and_or(& ull[1], -11);
//#line  132
  sc[1] = (signed char )__sync_fetch_and_xor(& sc[1], -11);
//#line  133
  uc[1] = (unsigned char )__sync_fetch_and_xor(& uc[1], -11);
//#line  134
  ss[1] = (short )__sync_fetch_and_xor(& ss[1], -11);
//#line  135
  us[1] = (unsigned short )__sync_fetch_and_xor(& us[1], -11);
//#line  136
  si[1] = (int )__sync_fetch_and_xor(& si[1], -11);
//#line  137
  ui[1] = (unsigned int )__sync_fetch_and_xor(& ui[1], -11);
//#line  138
  sl[1] = (long )__sync_fetch_and_xor(& sl[1], -11);
//#line  139
  ul[1] = (unsigned long )__sync_fetch_and_xor(& ul[1], -11);
//#line  140
  sll[1] = (long long )__sync_fetch_and_xor(& sll[1], -11);
//#line  141
  ull[1] = (unsigned long long )__sync_fetch_and_xor(& ull[1], -11);
//#line  143
  sc[1] = (signed char )__sync_fetch_and_and(& sc[1], -11);
//#line  144
  uc[1] = (unsigned char )__sync_fetch_and_and(& uc[1], -11);
//#line  145
  ss[1] = (short )__sync_fetch_and_and(& ss[1], -11);
//#line  146
  us[1] = (unsigned short )__sync_fetch_and_and(& us[1], -11);
//#line  147
  si[1] = (int )__sync_fetch_and_and(& si[1], -11);
//#line  148
  ui[1] = (unsigned int )__sync_fetch_and_and(& ui[1], -11);
//#line  149
  sl[1] = (long )__sync_fetch_and_and(& sl[1], -11);
//#line  150
  ul[1] = (unsigned long )__sync_fetch_and_and(& ul[1], -11);
//#line  151
  sll[1] = (long long )__sync_fetch_and_and(& sll[1], -11);
//#line  152
  ull[1] = (unsigned long long )__sync_fetch_and_and(& ull[1], -11);
//#line  154
  sc[1] = (signed char )__sync_fetch_and_nand(& sc[1], -11);
//#line  155
  uc[1] = (unsigned char )__sync_fetch_and_nand(& uc[1], -11);
//#line  156
  ss[1] = (short )__sync_fetch_and_nand(& ss[1], -11);
//#line  157
  us[1] = (unsigned short )__sync_fetch_and_nand(& us[1], -11);
//#line  158
  si[1] = (int )__sync_fetch_and_nand(& si[1], -11);
//#line  159
  ui[1] = (unsigned int )__sync_fetch_and_nand(& ui[1], -11);
//#line  160
  sl[1] = (long )__sync_fetch_and_nand(& sl[1], -11);
//#line  161
  ul[1] = (unsigned long )__sync_fetch_and_nand(& ul[1], -11);
//#line  162
  sll[1] = (long long )__sync_fetch_and_nand(& sll[1], -11);
//#line  163
  ull[1] = (unsigned long long )__sync_fetch_and_nand(& ull[1], -11);
//#line  164
  return;
}
}
//#line  166 "sync-3.c"
void test_lock(void) 
{ 
  signed char sc[2] ;
  unsigned char uc[2] ;
  short ss[2] ;
  unsigned short us[2] ;
  int si[2] ;
  unsigned int ui[2] ;
  long sl[2] ;
  unsigned long ul[2] ;
  long long sll[2] ;
  unsigned long long ull[2] ;

  {
//#line  178
  sc[1] = (signed char )__sync_lock_test_and_set(& sc[1], -1);
//#line  179
  uc[1] = (unsigned char )__sync_lock_test_and_set(& uc[1], -1);
//#line  180
  ss[1] = (short )__sync_lock_test_and_set(& ss[1], -1);
//#line  181
  us[1] = (unsigned short )__sync_lock_test_and_set(& us[1], -1);
//#line  182
  si[1] = (int )__sync_lock_test_and_set(& si[1], -1);
//#line  183
  ui[1] = (unsigned int )__sync_lock_test_and_set(& ui[1], -1);
//#line  184
  sl[1] = (long )__sync_lock_test_and_set(& sl[1], -1);
//#line  185
  ul[1] = (unsigned long )__sync_lock_test_and_set(& ul[1], -1);
//#line  186
  sll[1] = (long long )__sync_lock_test_and_set(& sll[1], -1);
//#line  187
  ull[1] = (unsigned long long )__sync_lock_test_and_set(& ull[1], -1);
//#line  188
  return;
}
}
