/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  5 "tags.c"
struct __anonstruct_S1_58036087 {
   int x ;
   char *p ;
   int a[20] ;
};
//#line  5 "tags.c"
typedef struct __anonstruct_S1_58036087 S1;
//#line  11 "tags.c"
struct __anonstruct_S2_349281051 {
   S1 s1test ;
   double f1 ;
   double f2 ;
};
//#line  11 "tags.c"
typedef struct __anonstruct_S2_349281051 S2;
//#line  17 "tags.c"
int extint  =    5;
//#line  18 "tags.c"
S1 exts1  =    {7, (char *)0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}};
//#line  19 "tags.c"
S2 exts2  ;
//#line  21 "tags.c"
int *fooptr  =    (int *)5;
//#line  23
extern int extarr[] ;
//#line  30 "tags.c"
int foo(int k ) 
{ 
  int t ;
  S2 locs2 ;

  {
//#line  31
  t = extint + extarr[5];
//#line  34
  *((int *)(& locs2)) = 0;
//#line  37
  return (0);
}
}
