/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "task.c"
struct __anonstruct_spinlock_t_129913994 {

};
//#line  4 "task.c"
typedef struct __anonstruct_spinlock_t_129913994 spinlock_t;
//#line  6 "task.c"
struct task_struct {
   spinlock_t sigmask_lock ;
};
//#line  10 "task.c"
struct task_struct my_task  ;
//#line  12
extern int printf(char const   *  , ...) ;
//#line  14 "task.c"
int main(void) 
{ 
  spinlock_t *sp ;
  spinlock_t *sp_2 ;

  {
//#line  16
  sp = & my_task.sigmask_lock;
//#line  18
  printf("Sizeof(mytask) = %d\n", sizeof(my_task));
//#line  19
  printf("Sizeof(void) = %d\n", sizeof(void ));
//#line  20
  printf("Sizeof(spinlock_t) = %d\n", sizeof(spinlock_t ));
//#line  21
  printf("& (spinlock_t) = %x\n", (long )sp);
//#line  22
  printf("(& spinlock) + 1 = %x\n", (long )(sp + 1));
//#line  24
  if (sizeof(my_task) != 0UL) {
//#line  24
    return (1);
  }
//#line  25
  if (sizeof(spinlock_t ) != 0UL) {
//#line  25
    return (2);
  }
//#line  28
  sp_2 = sp + 1;
//#line  29
  if ((unsigned long )sp_2 != (unsigned long )sp) {
//#line  29
    return (3);
  }
//#line  30
  *sp_2 = *sp;
//#line  32
  return (0);
}
}
