/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  22 "typeof1.c"
struct foo {
   int a ;
   int b ;
};
//#line  43 "typeof1.c"
typedef int ARRAY[8];
//#line  3
extern int printf(char const   *fmt  , ...) ;
//#line  6
extern void foo() ;
//#line  9
void afun(void) ;
//#line  10 "typeof1.c"
void afun(void) 
{ 


  {
//#line  10
  return;
}
}
//#line  12
extern void bfun(void) ;
//#line  13 "typeof1.c"
extern void bfun(void) 
{ 


  {
//#line  13
  afun();
//#line  13
  return;
}
}
//#line  15 "typeof1.c"
int arr[9]  ;
//#line  17 "typeof1.c"
int barr[9]  = {      0,      1,      2,      3};
//#line  20 "typeof1.c"
char const   str[sizeof("a long string")]  ;
//#line  23 "typeof1.c"
struct foo returnsAStruct(int a ) 
{ 
  struct foo __constr_expr_0 ;

  {
//#line  24
  __constr_expr_0.a = a;
//#line  24
  __constr_expr_0.b = 2;
//#line  24
  return (__constr_expr_0);
}
}
//#line  25 "typeof1.c"
struct foo a_struct  ;
//#line  27 "typeof1.c"
void *funp  ;
//#line  33
int fptr(int x ) ;
//#line  39 "typeof1.c"
int fptr(int x ) 
{ 


  {
//#line  40
  return (x - 1);
}
}
//#line  45 "typeof1.c"
ARRAY carr  ;
//#line  60
extern int ( /* missing proto */  exit)() ;
//#line  47 "typeof1.c"
int main(void) 
{ 
  char a[2] ;
  char a___0[2] ;
  char a___1[15] ;
  char a___2[15] ;
  char a___3[37] ;
  char a___4[37] ;
  char a___5[9] ;
  char a___6[2] ;
  char a___7[2] ;
  char a___8[2] ;
  char a___9[2] ;
  char a___10[5] ;
  char a___11[5] ;
  char a___12[9] ;
  int tmp ;

  {
//#line  50
  afun();
//#line  51
  bfun();
//#line  60
  a[0] = (char)0;
//#line  60
  a[1] = (char)34;
//#line  60
  printf("sizeof(foo) = %d (CIL) and %d (Compiler)\n", sizeof(a) - 1UL, sizeof(foo));
//#line  60
  if (sizeof(foo) != sizeof(a) - 1UL) {
//#line  60
    exit(1);
  }
//#line  61
  a___0[0] = (char)0;
//#line  61
  a___0[1] = (char)34;
//#line  61
  printf("sizeof(afun) = %d (CIL) and %d (Compiler)\n", sizeof(a___0) - 1UL, sizeof(afun));
//#line  61
  if (sizeof(afun) != sizeof(a___0) - 1UL) {
//#line  61
    exit(1);
  }
//#line  62
  a___1[0] = (char)0;
//#line  62
  a___1[1] = (char)0;
//#line  62
  a___1[2] = (char)0;
//#line  62
  a___1[3] = (char)0;
//#line  62
  a___1[4] = (char)0;
//#line  62
  a___1[5] = (char)0;
//#line  62
  a___1[6] = (char)0;
//#line  62
  a___1[7] = (char)0;
//#line  62
  a___1[8] = (char)0;
//#line  62
  a___1[9] = (char)0;
//#line  62
  a___1[10] = (char)0;
//#line  62
  a___1[11] = (char)0;
//#line  62
  a___1[12] = (char)0;
//#line  62
  a___1[13] = (char)0;
//#line  62
  a___1[14] = (char)34;
//#line  62
  printf("sizeof(\"a long string\") = %d (CIL) and %d (Compiler)\n", sizeof(a___1) - 1UL,
         sizeof("a long string"));
//#line  62
  if (sizeof("a long string") != sizeof(a___1) - 1UL) {
//#line  62
    exit(1);
  }
//#line  63
  a___2[0] = (char)0;
//#line  63
  a___2[1] = (char)0;
//#line  63
  a___2[2] = (char)0;
//#line  63
  a___2[3] = (char)0;
//#line  63
  a___2[4] = (char)0;
//#line  63
  a___2[5] = (char)0;
//#line  63
  a___2[6] = (char)0;
//#line  63
  a___2[7] = (char)0;
//#line  63
  a___2[8] = (char)0;
//#line  63
  a___2[9] = (char)0;
//#line  63
  a___2[10] = (char)0;
//#line  63
  a___2[11] = (char)0;
//#line  63
  a___2[12] = (char)0;
//#line  63
  a___2[13] = (char)0;
//#line  63
  a___2[14] = (char)34;
//#line  63
  printf("sizeof(str) = %d (CIL) and %d (Compiler)\n", sizeof(a___2) - 1UL, sizeof(str));
//#line  63
  if (sizeof(str) != sizeof(a___2) - 1UL) {
//#line  63
    exit(1);
  }
//#line  64
  a___3[0] = (char)0;
//#line  64
  a___3[1] = (char)0;
//#line  64
  a___3[2] = (char)0;
//#line  64
  a___3[3] = (char)0;
//#line  64
  a___3[4] = (char)0;
//#line  64
  a___3[5] = (char)0;
//#line  64
  a___3[6] = (char)0;
//#line  64
  a___3[7] = (char)0;
//#line  64
  a___3[8] = (char)0;
//#line  64
  a___3[9] = (char)0;
//#line  64
  a___3[10] = (char)0;
//#line  64
  a___3[11] = (char)0;
//#line  64
  a___3[12] = (char)0;
//#line  64
  a___3[13] = (char)0;
//#line  64
  a___3[14] = (char)0;
//#line  64
  a___3[15] = (char)0;
//#line  64
  a___3[16] = (char)0;
//#line  64
  a___3[17] = (char)0;
//#line  64
  a___3[18] = (char)0;
//#line  64
  a___3[19] = (char)0;
//#line  64
  a___3[20] = (char)0;
//#line  64
  a___3[21] = (char)0;
//#line  64
  a___3[22] = (char)0;
//#line  64
  a___3[23] = (char)0;
//#line  64
  a___3[24] = (char)0;
//#line  64
  a___3[25] = (char)0;
//#line  64
  a___3[26] = (char)0;
//#line  64
  a___3[27] = (char)0;
//#line  64
  a___3[28] = (char)0;
//#line  64
  a___3[29] = (char)0;
//#line  64
  a___3[30] = (char)0;
//#line  64
  a___3[31] = (char)0;
//#line  64
  a___3[32] = (char)0;
//#line  64
  a___3[33] = (char)0;
//#line  64
  a___3[34] = (char)0;
//#line  64
  a___3[35] = (char)0;
//#line  64
  a___3[36] = (char)34;
//#line  64
  printf("sizeof(arr) = %d (CIL) and %d (Compiler)\n", sizeof(a___3) - 1UL, sizeof(arr));
//#line  64
  if (sizeof(arr) != sizeof(a___3) - 1UL) {
//#line  64
    exit(1);
  }
//#line  65
  a___4[0] = (char)0;
//#line  65
  a___4[1] = (char)0;
//#line  65
  a___4[2] = (char)0;
//#line  65
  a___4[3] = (char)0;
//#line  65
  a___4[4] = (char)0;
//#line  65
  a___4[5] = (char)0;
//#line  65
  a___4[6] = (char)0;
//#line  65
  a___4[7] = (char)0;
//#line  65
  a___4[8] = (char)0;
//#line  65
  a___4[9] = (char)0;
//#line  65
  a___4[10] = (char)0;
//#line  65
  a___4[11] = (char)0;
//#line  65
  a___4[12] = (char)0;
//#line  65
  a___4[13] = (char)0;
//#line  65
  a___4[14] = (char)0;
//#line  65
  a___4[15] = (char)0;
//#line  65
  a___4[16] = (char)0;
//#line  65
  a___4[17] = (char)0;
//#line  65
  a___4[18] = (char)0;
//#line  65
  a___4[19] = (char)0;
//#line  65
  a___4[20] = (char)0;
//#line  65
  a___4[21] = (char)0;
//#line  65
  a___4[22] = (char)0;
//#line  65
  a___4[23] = (char)0;
//#line  65
  a___4[24] = (char)0;
//#line  65
  a___4[25] = (char)0;
//#line  65
  a___4[26] = (char)0;
//#line  65
  a___4[27] = (char)0;
//#line  65
  a___4[28] = (char)0;
//#line  65
  a___4[29] = (char)0;
//#line  65
  a___4[30] = (char)0;
//#line  65
  a___4[31] = (char)0;
//#line  65
  a___4[32] = (char)0;
//#line  65
  a___4[33] = (char)0;
//#line  65
  a___4[34] = (char)0;
//#line  65
  a___4[35] = (char)0;
//#line  65
  a___4[36] = (char)34;
//#line  65
  printf("sizeof(barr) = %d (CIL) and %d (Compiler)\n", sizeof(a___4) - 1UL, sizeof(barr));
//#line  65
  if (sizeof(barr) != sizeof(a___4) - 1UL) {
//#line  65
    exit(1);
  }
//#line  66
  a___5[0] = (char)0;
//#line  66
  a___5[1] = (char)0;
//#line  66
  a___5[2] = (char)0;
//#line  66
  a___5[3] = (char)0;
//#line  66
  a___5[4] = (char)0;
//#line  66
  a___5[5] = (char)0;
//#line  66
  a___5[6] = (char)0;
//#line  66
  a___5[7] = (char)0;
//#line  66
  a___5[8] = (char)34;
//#line  66
  printf("sizeof(funp) = %d (CIL) and %d (Compiler)\n", sizeof(a___5) - 1UL, sizeof(funp));
//#line  66
  if (sizeof(funp) != sizeof(a___5) - 1UL) {
//#line  66
    exit(1);
  }
//#line  68
  a___6[0] = (char)0;
//#line  68
  a___6[1] = (char)34;
//#line  68
  printf("__alignof(\"a string\") = %d (CIL) and %d (Compiler)\n", sizeof(a___6) - 1UL,
         __alignof__("a string"));
//#line  68
  if (__alignof__("a string") != sizeof(a___6) - 1UL) {
//#line  68
    exit(1);
  }
//#line  69
  a___7[0] = (char)0;
//#line  69
  a___7[1] = (char)34;
//#line  69
  printf("__alignof(str) = %d (CIL) and %d (Compiler)\n", sizeof(a___7) - 1UL, __alignof__(str));
//#line  69
  if (__alignof__(str) != sizeof(a___7) - 1UL) {
//#line  69
    exit(1);
  }
//#line  70
  a___8[0] = (char)0;
//#line  70
  a___8[1] = (char)34;
//#line  70
  printf("__alignof(foo) = %d (CIL) and %d (Compiler)\n", sizeof(a___8) - 1UL, __alignof__(foo));
//#line  70
  if (__alignof__(foo) != sizeof(a___8) - 1UL) {
//#line  70
    exit(1);
  }
//#line  71
  a___9[0] = (char)0;
//#line  71
  a___9[1] = (char)34;
//#line  71
  printf("__alignof(afun) = %d (CIL) and %d (Compiler)\n", sizeof(a___9) - 1UL, __alignof__(afun));
//#line  71
  if (__alignof__(afun) != sizeof(a___9) - 1UL) {
//#line  71
    exit(1);
  }
//#line  72
  a___10[0] = (char)0;
//#line  72
  a___10[1] = (char)0;
//#line  72
  a___10[2] = (char)0;
//#line  72
  a___10[3] = (char)0;
//#line  72
  a___10[4] = (char)34;
//#line  72
  printf("__alignof(arr) = %d (CIL) and %d (Compiler)\n", sizeof(a___10) - 1UL, __alignof__(arr));
//#line  72
  if (__alignof__(arr) != sizeof(a___10) - 1UL) {
//#line  72
    exit(1);
  }
//#line  73
  a___11[0] = (char)0;
//#line  73
  a___11[1] = (char)0;
//#line  73
  a___11[2] = (char)0;
//#line  73
  a___11[3] = (char)0;
//#line  73
  a___11[4] = (char)34;
//#line  73
  printf("__alignof(barr) = %d (CIL) and %d (Compiler)\n", sizeof(a___11) - 1UL, __alignof__(barr));
//#line  73
  if (__alignof__(barr) != sizeof(a___11) - 1UL) {
//#line  73
    exit(1);
  }
//#line  74
  a___12[0] = (char)0;
//#line  74
  a___12[1] = (char)0;
//#line  74
  a___12[2] = (char)0;
//#line  74
  a___12[3] = (char)0;
//#line  74
  a___12[4] = (char)0;
//#line  74
  a___12[5] = (char)0;
//#line  74
  a___12[6] = (char)0;
//#line  74
  a___12[7] = (char)0;
//#line  74
  a___12[8] = (char)34;
//#line  74
  printf("__alignof(funp) = %d (CIL) and %d (Compiler)\n", sizeof(a___12) - 1UL, __alignof__(funp));
//#line  74
  if (__alignof__(funp) != sizeof(a___12) - 1UL) {
//#line  74
    exit(1);
  }
//#line  77
  if (sizeof(carr) != sizeof(ARRAY )) {
//#line  78
    exit(8);
  }
//#line  80
  if (sizeof(a_struct) != sizeof(struct foo )) {
//#line  82
    exit(9);
  } else
//#line  80
  if (__alignof__(a_struct) != __alignof__(struct foo )) {
//#line  82
    exit(9);
  }
//#line  85
  tmp = fptr(1);
//#line  85
  return (tmp);
}
}
