/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  2 "unimplemented.c"
struct dirent {
   char d_name[256] ;
};
//#line  7 "unimplemented.c"
struct isc_direntry {
   char name[256] ;
};
//#line  7 "unimplemented.c"
typedef struct isc_direntry isc_direntry_t;
//#line  11 "unimplemented.c"
struct isc_dir {
   isc_direntry_t entry ;
};
//#line  11 "unimplemented.c"
typedef struct isc_dir isc_dir_t;
//#line  125 "/usr/include/string.h"
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1,2), __leaf__)) strcpy)(char * __restrict  __dest ,
                                                                                                 char const   * __restrict  __src ) ;
//#line  16 "unimplemented.c"
void isc_dir_init(isc_dir_t *dir ) 
{ 


  {
//#line  19
  dir->entry.name[0] = (char )'\000';
//#line  21
  return;
}
}
//#line  23 "unimplemented.c"
unsigned int isc_dir_read(isc_dir_t *dir ) 
{ 
  struct dirent *entry ;

  {
//#line  27
  strcpy((char */* __restrict  */)(dir->entry.name), (char const   */* __restrict  */)(entry->d_name));
//#line  29
  return (0U);
}
}
