/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "union5.c"
union Argument {
   int field1 ;
   char *field2 ;
} __attribute__((__transparent_union__)) ;
//#line  20 "union5.c"
struct __anonstruct_s_562920233 {
   double d ;
   union Argument a ;
};
//#line  7 "union5.c"
int callee(int __cil_tmp2 ) 
{ 
  union Argument arg ;

  {
//#line  8
  arg.field1 = __cil_tmp2;
//#line  8
  return ((int )*(arg.field2) + 1);
}
}
//#line  11 "union5.c"
union Argument mkArgument(void) 
{ 
  union Argument a ;

  {
//#line  13
  return (a);
}
}
//#line  16 "union5.c"
void caller(void) 
{ 
  char c ;
  union Argument a ;
  struct __anonstruct_s_562920233 s ;
  union Argument tmp ;

  {
//#line  26
  callee(5);
//#line  27
  callee((int )(& c));
//#line  30
  callee(a.field1);
//#line  31
  callee(s.a.field1);
//#line  35
  tmp = mkArgument();
//#line  35
  callee(tmp.field1);
//#line  36
  return;
}
}
