/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  8 "va-arg-7.c"
union __anonunion_375160861 {
   int i ;
   double d ;
};
//#line  40 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h"
typedef __builtin_va_list __gnuc_va_list;
//#line  98 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h"
typedef __gnuc_va_list va_list;
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned long  , void * ) ;  */
//#line  1 "va-arg-7.c"
extern void exit(int  ) ;
//#line  2
extern void abort(void) ;
//#line  8
/* #pragma ccuredvararg("debug",sizeof(union __anonunion_375160861 )) */
//#line  13 "va-arg-7.c"
__inline void debug(int i1 , int i2 , int i3 , int i4 , int i5 , int i6 , int i7 ,
                    double f1 , double f2 , double f3 , double f4 , double f5 , double f6 ,
                    double f7 , double f8 , double f9  , ...) 
{ 
  va_list ap ;
  int tmp___0 ;
  int tmp___2 ;
  int tmp___4 ;

  {
//#line  32
  __builtin_va_start(ap, f9);
//#line  37
  tmp___0 = __builtin_va_arg(ap, int );
//#line  37
  if (tmp___0 != 8) {
//#line  38
    abort();
  }
//#line  39
  tmp___2 = __builtin_va_arg(ap, int );
//#line  39
  if (tmp___2 != 9) {
//#line  40
    abort();
  }
//#line  41
  tmp___4 = __builtin_va_arg(ap, int );
//#line  41
  if (tmp___4 != 10) {
//#line  42
    abort();
  }
//#line  44
  __builtin_va_end(ap);
//#line  45
  return;
}
}
//#line  47 "va-arg-7.c"
int main(void) 
{ 


  {
//#line  50
  debug(1, 2, 3, 4, 5, 6, 7, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 8, 9, 10);
//#line  52
  exit(0);
}
}
