/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  40 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h"
typedef __builtin_va_list __gnuc_va_list;
//#line  98 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h"
typedef __gnuc_va_list va_list;
//#line  6 "va-arg-1.c"
union __anonunion_721778306 {
   long l ;
};
//#line  8 "va-arg-1.c"
typedef unsigned long L;
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned long  , void * ) ;  */
//#line  3
extern void exit(int  ) ;
//#line  4
extern void abort(void) ;
//#line  6
/* #pragma ccuredvararg("f",sizeof(union __anonunion_721778306 )) */
//#line  9 "va-arg-1.c"
int f(L p0 , L p1 , L p2 , L p3 , L p4 , L p5 , L p6 , L p7 , L p8  , ...) 
{ 
  va_list select ;
  L tmp___0 ;
  L tmp___2 ;
  L tmp___4 ;

  {
//#line  13
  __builtin_va_start(select, p8);
//#line  15
  tmp___0 = __builtin_va_arg(select, L );
//#line  15
  if (tmp___0 != 10UL) {
//#line  16
    abort();
  }
//#line  17
  tmp___2 = __builtin_va_arg(select, L );
//#line  17
  if (tmp___2 != 11UL) {
//#line  18
    abort();
  }
//#line  19
  tmp___4 = __builtin_va_arg(select, L );
//#line  19
  if (tmp___4 != 0UL) {
//#line  20
    abort();
  }
//#line  22
  __builtin_va_end(select);
//#line  23
  return (0);
}
}
//#line  25 "va-arg-1.c"
int main(void) 
{ 


  {
//#line  27
  f((L )1L, (L )2L, (L )3L, (L )4L, (L )5L, (L )6L, (L )7L, (L )8L, (L )9L, 10L, 11L,
    0L);
//#line  28
  exit(0);
}
}
