/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  40 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h"
typedef __builtin_va_list __gnuc_va_list;
//#line  98 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h"
typedef __gnuc_va_list va_list;
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned long  , void * ) ;  */
//#line  1 "va-arg-2.c"
extern void exit(int  ) ;
//#line  2
extern void abort(void) ;
//#line  13
extern unsigned int strlen(char const   * ) ;
//#line  18
int to_hex(unsigned int a ) ;
//#line  18 "va-arg-2.c"
static char hex[17]  = 
//#line  18
  {      (char )'0',      (char )'1',      (char )'2',      (char )'3', 
        (char )'4',      (char )'5',      (char )'6',      (char )'7', 
        (char )'8',      (char )'9',      (char )'a',      (char )'b', 
        (char )'c',      (char )'d',      (char )'e',      (char )'f', 
        (char )'\000'};
//#line  15 "va-arg-2.c"
int to_hex(unsigned int a ) 
{ 


  {
//#line  20
  if (a > 15U) {
//#line  21
    abort();
  }
//#line  22
  return ((int )hex[a]);
}
}
//#line  25
/* #pragma ccuredvararg("f0",sizeof(int )) */
//#line  26 "va-arg-2.c"
void f0(char *format  , ...) 
{ 
  va_list ap ;
  unsigned int tmp ;
  char *tmp___0 ;
  int tmp___2 ;
  int tmp___3 ;

  {
//#line  31
  __builtin_va_start(ap, format);
//#line  32
  tmp = strlen((char const   *)format);
//#line  32
  if (tmp != 16U) {
//#line  33
    abort();
  }
//#line  34
  while (*format) {
//#line  35
    tmp___0 = format;
//#line  35
    format ++;
//#line  35
    tmp___2 = __builtin_va_arg(ap, int );
//#line  35
    tmp___3 = to_hex((unsigned int )tmp___2);
//#line  35
    if ((int )*tmp___0 != tmp___3) {
//#line  36
      abort();
    }
  }
//#line  37
  __builtin_va_end(ap);
//#line  38
  return;
}
}
//#line  40
/* #pragma ccuredvararg("f1",sizeof(int )) */
//#line  41 "va-arg-2.c"
void f1(int a1 , char *format  , ...) 
{ 
  va_list ap ;
  unsigned int tmp ;
  char *tmp___0 ;
  int tmp___2 ;
  int tmp___3 ;

  {
//#line  46
  __builtin_va_start(ap, format);
//#line  47
  tmp = strlen((char const   *)format);
//#line  47
  if (tmp != 15U) {
//#line  48
    abort();
  }
//#line  49
  while (*format) {
//#line  50
    tmp___0 = format;
//#line  50
    format ++;
//#line  50
    tmp___2 = __builtin_va_arg(ap, int );
//#line  50
    tmp___3 = to_hex((unsigned int )tmp___2);
//#line  50
    if ((int )*tmp___0 != tmp___3) {
//#line  51
      abort();
    }
  }
//#line  52
  __builtin_va_end(ap);
//#line  53
  return;
}
}
//#line  55
/* #pragma ccuredvararg("f2",sizeof(int )) */
//#line  56 "va-arg-2.c"
void f2(int a1 , int a2 , char *format  , ...) 
{ 
  va_list ap ;
  unsigned int tmp ;
  char *tmp___0 ;
  int tmp___2 ;
  int tmp___3 ;

  {
//#line  61
  __builtin_va_start(ap, format);
//#line  62
  tmp = strlen((char const   *)format);
//#line  62
  if (tmp != 14U) {
//#line  63
    abort();
  }
//#line  64
  while (*format) {
//#line  65
    tmp___0 = format;
//#line  65
    format ++;
//#line  65
    tmp___2 = __builtin_va_arg(ap, int );
//#line  65
    tmp___3 = to_hex((unsigned int )tmp___2);
//#line  65
    if ((int )*tmp___0 != tmp___3) {
//#line  66
      abort();
    }
  }
//#line  67
  __builtin_va_end(ap);
//#line  68
  return;
}
}
//#line  70
/* #pragma ccuredvararg("f3",sizeof(int )) */
//#line  71 "va-arg-2.c"
void f3(int a1 , int a2 , int a3 , char *format  , ...) 
{ 
  va_list ap ;
  unsigned int tmp ;
  char *tmp___0 ;
  int tmp___2 ;
  int tmp___3 ;

  {
//#line  76
  __builtin_va_start(ap, format);
//#line  77
  tmp = strlen((char const   *)format);
//#line  77
  if (tmp != 13U) {
//#line  78
    abort();
  }
//#line  79
  while (*format) {
//#line  80
    tmp___0 = format;
//#line  80
    format ++;
//#line  80
    tmp___2 = __builtin_va_arg(ap, int );
//#line  80
    tmp___3 = to_hex((unsigned int )tmp___2);
//#line  80
    if ((int )*tmp___0 != tmp___3) {
//#line  81
      abort();
    }
  }
//#line  82
  __builtin_va_end(ap);
//#line  83
  return;
}
}
//#line  85
/* #pragma ccuredvararg("f4",sizeof(int )) */
//#line  86 "va-arg-2.c"
void f4(int a1 , int a2 , int a3 , int a4 , char *format  , ...) 
{ 
  va_list ap ;
  unsigned int tmp ;
  char *tmp___0 ;
  int tmp___2 ;
  int tmp___3 ;

  {
//#line  91
  __builtin_va_start(ap, format);
//#line  92
  tmp = strlen((char const   *)format);
//#line  92
  if (tmp != 12U) {
//#line  93
    abort();
  }
//#line  94
  while (*format) {
//#line  95
    tmp___0 = format;
//#line  95
    format ++;
//#line  95
    tmp___2 = __builtin_va_arg(ap, int );
//#line  95
    tmp___3 = to_hex((unsigned int )tmp___2);
//#line  95
    if ((int )*tmp___0 != tmp___3) {
//#line  96
      abort();
    }
  }
//#line  97
  __builtin_va_end(ap);
//#line  98
  return;
}
}
//#line  100
/* #pragma ccuredvararg("f5",sizeof(int )) */
//#line  101 "va-arg-2.c"
void f5(int a1 , int a2 , int a3 , int a4 , int a5 , char *format  , ...) 
{ 
  va_list ap ;
  unsigned int tmp ;
  char *tmp___0 ;
  int tmp___2 ;
  int tmp___3 ;

  {
//#line  107
  __builtin_va_start(ap, format);
//#line  108
  tmp = strlen((char const   *)format);
//#line  108
  if (tmp != 11U) {
//#line  109
    abort();
  }
//#line  110
  while (*format) {
//#line  111
    tmp___0 = format;
//#line  111
    format ++;
//#line  111
    tmp___2 = __builtin_va_arg(ap, int );
//#line  111
    tmp___3 = to_hex((unsigned int )tmp___2);
//#line  111
    if ((int )*tmp___0 != tmp___3) {
//#line  112
      abort();
    }
  }
//#line  113
  __builtin_va_end(ap);
//#line  114
  return;
}
}
//#line  116
/* #pragma ccuredvararg("f6",sizeof(int )) */
//#line  117 "va-arg-2.c"
void f6(int a1 , int a2 , int a3 , int a4 , int a5 , int a6 , char *format  , ...) 
{ 
  va_list ap ;
  unsigned int tmp ;
  char *tmp___0 ;
  int tmp___2 ;
  int tmp___3 ;

  {
//#line  124
  __builtin_va_start(ap, format);
//#line  125
  tmp = strlen((char const   *)format);
//#line  125
  if (tmp != 10U) {
//#line  126
    abort();
  }
//#line  127
  while (*format) {
//#line  128
    tmp___0 = format;
//#line  128
    format ++;
//#line  128
    tmp___2 = __builtin_va_arg(ap, int );
//#line  128
    tmp___3 = to_hex((unsigned int )tmp___2);
//#line  128
    if ((int )*tmp___0 != tmp___3) {
//#line  129
      abort();
    }
  }
//#line  130
  __builtin_va_end(ap);
//#line  131
  return;
}
}
//#line  133
/* #pragma ccuredvararg("f7",sizeof(int )) */
//#line  134 "va-arg-2.c"
void f7(int a1 , int a2 , int a3 , int a4 , int a5 , int a6 , int a7 , char *format 
        , ...) 
{ 
  va_list ap ;
  unsigned int tmp ;
  char *tmp___0 ;
  int tmp___2 ;
  int tmp___3 ;

  {
//#line  141
  __builtin_va_start(ap, format);
//#line  142
  tmp = strlen((char const   *)format);
//#line  142
  if (tmp != 9U) {
//#line  143
    abort();
  }
//#line  144
  while (*format) {
//#line  145
    tmp___0 = format;
//#line  145
    format ++;
//#line  145
    tmp___2 = __builtin_va_arg(ap, int );
//#line  145
    tmp___3 = to_hex((unsigned int )tmp___2);
//#line  145
    if ((int )*tmp___0 != tmp___3) {
//#line  146
      abort();
    }
  }
//#line  147
  __builtin_va_end(ap);
//#line  148
  return;
}
}
//#line  150
/* #pragma ccuredvararg("f8",sizeof(int )) */
//#line  151 "va-arg-2.c"
void f8(int a1 , int a2 , int a3 , int a4 , int a5 , int a6 , int a7 , int a8 , char *format 
        , ...) 
{ 
  va_list ap ;
  unsigned int tmp ;
  char *tmp___0 ;
  int tmp___2 ;
  int tmp___3 ;

  {
//#line  158
  __builtin_va_start(ap, format);
//#line  159
  tmp = strlen((char const   *)format);
//#line  159
  if (tmp != 8U) {
//#line  160
    abort();
  }
//#line  161
  while (*format) {
//#line  162
    tmp___0 = format;
//#line  162
    format ++;
//#line  162
    tmp___2 = __builtin_va_arg(ap, int );
//#line  162
    tmp___3 = to_hex((unsigned int )tmp___2);
//#line  162
    if ((int )*tmp___0 != tmp___3) {
//#line  163
      abort();
    }
  }
//#line  164
  __builtin_va_end(ap);
//#line  165
  return;
}
}
//#line  167
/* #pragma ccuredvararg("f9",sizeof(int )) */
//#line  168 "va-arg-2.c"
void f9(int a1 , int a2 , int a3 , int a4 , int a5 , int a6 , int a7 , int a8 , int a9 ,
        char *format  , ...) 
{ 
  va_list ap ;
  unsigned int tmp ;
  char *tmp___0 ;
  int tmp___2 ;
  int tmp___3 ;

  {
//#line  175
  __builtin_va_start(ap, format);
//#line  176
  tmp = strlen((char const   *)format);
//#line  176
  if (tmp != 7U) {
//#line  177
    abort();
  }
//#line  178
  while (*format) {
//#line  179
    tmp___0 = format;
//#line  179
    format ++;
//#line  179
    tmp___2 = __builtin_va_arg(ap, int );
//#line  179
    tmp___3 = to_hex((unsigned int )tmp___2);
//#line  179
    if ((int )*tmp___0 != tmp___3) {
//#line  180
      abort();
    }
  }
//#line  181
  __builtin_va_end(ap);
//#line  182
  return;
}
}
//#line  184
/* #pragma ccuredvararg("f10",sizeof(int )) */
//#line  185 "va-arg-2.c"
void f10(int a1 , int a2 , int a3 , int a4 , int a5 , int a6 , int a7 , int a8 , int a9 ,
         int a10 , char *format  , ...) 
{ 
  va_list ap ;
  unsigned int tmp ;
  char *tmp___0 ;
  int tmp___2 ;
  int tmp___3 ;

  {
//#line  192
  __builtin_va_start(ap, format);
//#line  193
  tmp = strlen((char const   *)format);
//#line  193
  if (tmp != 6U) {
//#line  194
    abort();
  }
//#line  195
  while (*format) {
//#line  196
    tmp___0 = format;
//#line  196
    format ++;
//#line  196
    tmp___2 = __builtin_va_arg(ap, int );
//#line  196
    tmp___3 = to_hex((unsigned int )tmp___2);
//#line  196
    if ((int )*tmp___0 != tmp___3) {
//#line  197
      abort();
    }
  }
//#line  198
  __builtin_va_end(ap);
//#line  199
  return;
}
}
//#line  201
/* #pragma ccuredvararg("f11",sizeof(int )) */
//#line  202 "va-arg-2.c"
void f11(int a1 , int a2 , int a3 , int a4 , int a5 , int a6 , int a7 , int a8 , int a9 ,
         int a10 , int a11 , char *format  , ...) 
{ 
  va_list ap ;
  unsigned int tmp ;
  char *tmp___0 ;
  int tmp___2 ;
  int tmp___3 ;

  {
//#line  210
  __builtin_va_start(ap, format);
//#line  211
  tmp = strlen((char const   *)format);
//#line  211
  if (tmp != 5U) {
//#line  212
    abort();
  }
//#line  213
  while (*format) {
//#line  214
    tmp___0 = format;
//#line  214
    format ++;
//#line  214
    tmp___2 = __builtin_va_arg(ap, int );
//#line  214
    tmp___3 = to_hex((unsigned int )tmp___2);
//#line  214
    if ((int )*tmp___0 != tmp___3) {
//#line  215
      abort();
    }
  }
//#line  216
  __builtin_va_end(ap);
//#line  217
  return;
}
}
//#line  219
/* #pragma ccuredvararg("f12",sizeof(int )) */
//#line  220 "va-arg-2.c"
void f12(int a1 , int a2 , int a3 , int a4 , int a5 , int a6 , int a7 , int a8 , int a9 ,
         int a10 , int a11 , int a12 , char *format  , ...) 
{ 
  va_list ap ;
  unsigned int tmp ;
  char *tmp___0 ;
  int tmp___2 ;
  int tmp___3 ;

  {
//#line  228
  __builtin_va_start(ap, format);
//#line  229
  tmp = strlen((char const   *)format);
//#line  229
  if (tmp != 4U) {
//#line  230
    abort();
  }
//#line  231
  while (*format) {
//#line  232
    tmp___0 = format;
//#line  232
    format ++;
//#line  232
    tmp___2 = __builtin_va_arg(ap, int );
//#line  232
    tmp___3 = to_hex((unsigned int )tmp___2);
//#line  232
    if ((int )*tmp___0 != tmp___3) {
//#line  233
      abort();
    }
  }
//#line  234
  __builtin_va_end(ap);
//#line  235
  return;
}
}
//#line  237
/* #pragma ccuredvararg("f13",sizeof(int )) */
//#line  238 "va-arg-2.c"
void f13(int a1 , int a2 , int a3 , int a4 , int a5 , int a6 , int a7 , int a8 , int a9 ,
         int a10 , int a11 , int a12 , int a13 , char *format  , ...) 
{ 
  va_list ap ;
  unsigned int tmp ;
  char *tmp___0 ;
  int tmp___2 ;
  int tmp___3 ;

  {
//#line  246
  __builtin_va_start(ap, format);
//#line  247
  tmp = strlen((char const   *)format);
//#line  247
  if (tmp != 3U) {
//#line  248
    abort();
  }
//#line  249
  while (*format) {
//#line  250
    tmp___0 = format;
//#line  250
    format ++;
//#line  250
    tmp___2 = __builtin_va_arg(ap, int );
//#line  250
    tmp___3 = to_hex((unsigned int )tmp___2);
//#line  250
    if ((int )*tmp___0 != tmp___3) {
//#line  251
      abort();
    }
  }
//#line  252
  __builtin_va_end(ap);
//#line  253
  return;
}
}
//#line  255
/* #pragma ccuredvararg("f14",sizeof(int )) */
//#line  256 "va-arg-2.c"
void f14(int a1 , int a2 , int a3 , int a4 , int a5 , int a6 , int a7 , int a8 , int a9 ,
         int a10 , int a11 , int a12 , int a13 , int a14 , char *format  , ...) 
{ 
  va_list ap ;
  unsigned int tmp ;
  char *tmp___0 ;
  int tmp___2 ;
  int tmp___3 ;

  {
//#line  264
  __builtin_va_start(ap, format);
//#line  265
  tmp = strlen((char const   *)format);
//#line  265
  if (tmp != 2U) {
//#line  266
    abort();
  }
//#line  267
  while (*format) {
//#line  268
    tmp___0 = format;
//#line  268
    format ++;
//#line  268
    tmp___2 = __builtin_va_arg(ap, int );
//#line  268
    tmp___3 = to_hex((unsigned int )tmp___2);
//#line  268
    if ((int )*tmp___0 != tmp___3) {
//#line  269
      abort();
    }
  }
//#line  270
  __builtin_va_end(ap);
//#line  271
  return;
}
}
//#line  273
/* #pragma ccuredvararg("f15",sizeof(int )) */
//#line  274 "va-arg-2.c"
void f15(int a1 , int a2 , int a3 , int a4 , int a5 , int a6 , int a7 , int a8 , int a9 ,
         int a10 , int a11 , int a12 , int a13 , int a14 , int a15 , char *format 
         , ...) 
{ 
  va_list ap ;
  unsigned int tmp ;
  char *tmp___0 ;
  int tmp___2 ;
  int tmp___3 ;

  {
//#line  282
  __builtin_va_start(ap, format);
//#line  283
  tmp = strlen((char const   *)format);
//#line  283
  if (tmp != 1U) {
//#line  284
    abort();
  }
//#line  285
  while (*format) {
//#line  286
    tmp___0 = format;
//#line  286
    format ++;
//#line  286
    tmp___2 = __builtin_va_arg(ap, int );
//#line  286
    tmp___3 = to_hex((unsigned int )tmp___2);
//#line  286
    if ((int )*tmp___0 != tmp___3) {
//#line  287
      abort();
    }
  }
//#line  288
  __builtin_va_end(ap);
//#line  289
  return;
}
}
//#line  291 "va-arg-2.c"
int main(void) 
{ 
  char *f ;

  {
//#line  293
  f = (char *)"0123456789abcdef";
//#line  295
  f0(f + 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);
//#line  296
  f1(0, f + 1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);
//#line  297
  f2(0, 1, f + 2, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);
//#line  298
  f3(0, 1, 2, f + 3, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);
//#line  299
  f4(0, 1, 2, 3, f + 4, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);
//#line  300
  f5(0, 1, 2, 3, 4, f + 5, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);
//#line  301
  f6(0, 1, 2, 3, 4, 5, f + 6, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);
//#line  302
  f7(0, 1, 2, 3, 4, 5, 6, f + 7, 7, 8, 9, 10, 11, 12, 13, 14, 15);
//#line  303
  f8(0, 1, 2, 3, 4, 5, 6, 7, f + 8, 8, 9, 10, 11, 12, 13, 14, 15);
//#line  304
  f9(0, 1, 2, 3, 4, 5, 6, 7, 8, f + 9, 9, 10, 11, 12, 13, 14, 15);
//#line  305
  f10(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, f + 10, 10, 11, 12, 13, 14, 15);
//#line  306
  f11(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, f + 11, 11, 12, 13, 14, 15);
//#line  307
  f12(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, f + 12, 12, 13, 14, 15);
//#line  308
  f13(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, f + 13, 13, 14, 15);
//#line  309
  f14(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, f + 14, 14, 15);
//#line  310
  f15(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, f + 15, 15);
//#line  312
  exit(0);
}
}
