/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

/* compiler builtin: 
   int __builtin_va_arg_pack(void) ;  */
//#line  362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  3 "va_arg_pack.c"
__inline extern int myprintf(char const   *format  , ...) ;
//#line  4 "va_arg_pack.c"
__inline extern int myprintf(char const   *format  , ...) 
{ 
  int r ;
  int tmp ;
  int s ;
  int tmp___0 ;

  {
//#line  6
  tmp = printf((char const   */* __restrict  */)"myprintf: ");
//#line  6
  r = tmp;
//#line  7
  if (r < 0) {
//#line  8
    return (r);
  }
//#line  9
  tmp___0 = printf((char const   */* __restrict  */)format, __builtin_va_arg_pack());
//#line  9
  s = tmp___0;
//#line  10
  if (s < 0) {
//#line  11
    return (s);
  }
//#line  12
  return (r + s);
}
}
