/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  40 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h"
typedef __builtin_va_list __gnuc_va_list;
//#line  79 "/usr/include/stdio.h"
typedef __gnuc_va_list va_list;
//#line  6 "varargauto1.c"
struct foo {
   int f ;
};
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned long  , void * ) ;  */
//#line  3 "testharness.h"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  15 "varargauto1.c"
void myva1(int many  , ...) ;
//#line  17 "varargauto1.c"
int main(void) 
{ 
  struct foo x ;
  struct foo y ;
  struct foo *px ;
  struct foo *py ;

  {
//#line  18
  x.f = 1;
//#line  18
  y.f = 2;
//#line  19
  px = & x;
//#line  19
  py = & y;
//#line  21
  myva1(4, 0, 5, 1, "hello", 1, "world", 2, & px->f);
//#line  25
  printf((char const   */* __restrict  */)"Success\n");
//#line  25
  exit(0);
}
}
//#line  29 "varargauto1.c"
void myva1(int many  , ...) 
{ 
  int count ;
  va_list marker ;
  int tag ;
  int tmp___0 ;
  int data ;
  int tmp___2 ;
  char *data___0 ;
  char *tmp___4 ;
  int *data___1 ;
  int *tmp___6 ;
  struct foo *data___2 ;
  struct foo *tmp___8 ;

  {
//#line  33
  __builtin_va_start(marker, many);
//#line  34
  count = 0;
//#line  34
  while (count < many) {
//#line  35
    tmp___0 = __builtin_va_arg(marker, int );
//#line  35
    tag = tmp___0;
//#line  36
    switch (tag) {
    case 0: 
//#line  39
    tmp___2 = __builtin_va_arg(marker, int );
//#line  39
    data = tmp___2;
//#line  40
    printf((char const   */* __restrict  */)"An_int: %d\n", data);
//#line  41
    break;
    case 1: 
//#line  45
    tmp___4 = __builtin_va_arg(marker, char *);
//#line  45
    data___0 = tmp___4;
//#line  46
    printf((char const   */* __restrict  */)"An_str: %s\n", data___0);
//#line  47
    break;
    case 2: 
//#line  51
    tmp___6 = __builtin_va_arg(marker, int *);
//#line  51
    data___1 = tmp___6;
//#line  52
    printf((char const   */* __restrict  */)"An_intptr: %x (%d)\n", (long )data___1,
           *data___1);
//#line  53
    break;
    case 3: 
//#line  57
    tmp___8 = __builtin_va_arg(marker, struct foo *);
//#line  57
    data___2 = tmp___8;
//#line  58
    printf((char const   */* __restrict  */)"An_fooptr: %d\n", data___2->f);
//#line  59
    break;
    }
//#line  34
    count ++;
  }
//#line  63
  return;
}
}
