/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  40 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h"
typedef __builtin_va_list __gnuc_va_list;
//#line  79 "/usr/include/stdio.h"
typedef __gnuc_va_list va_list;
//#line  11 "vararg1.c"
union vararg_average {
   int ints ;
};
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned long  , void * ) ;  */
//#line  362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  format  , ...) ;
//#line  10 "vararg1.c"
int average(int first  , ...) ;
//#line  12 "testharness.h"
extern void exit(int  ) ;
//#line  17 "vararg1.c"
int main(void) 
{ 
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
//#line  20
  tmp = average(2, 3, 4, -1);
//#line  20
  if (tmp != 3) {
//#line  20
    printf((char const   */* __restrict  */)"Error %d\n", 1);
//#line  20
    exit(1);
  }
//#line  21
  tmp___0 = average(5, 7, 9, 11, 13, -1);
//#line  21
  if (tmp___0 != 9) {
//#line  21
    printf((char const   */* __restrict  */)"Error %d\n", 2);
//#line  21
    exit(2);
  }
//#line  22
  tmp___1 = average(-1);
//#line  22
  if (tmp___1 != 0) {
//#line  22
    printf((char const   */* __restrict  */)"Error %d\n", 3);
//#line  22
    exit(3);
  }
//#line  24
  printf((char const   */* __restrict  */)"Success\n");
//#line  24
  exit(0);
}
}
//#line  30 "vararg1.c"
int average(int first  , ...) 
{ 
  int count ;
  int sum ;
  int i ;
  va_list marker ;
  int tmp ;
  int tmp___0 ;

  {
//#line  32
  count = 0;
//#line  32
  sum = 0;
//#line  32
  i = first;
//#line  35
  __builtin_va_start(marker, first);
//#line  36
  while (i != -1) {
//#line  38
    sum += i;
//#line  39
    count ++;
//#line  40
    tmp = __builtin_va_arg(marker, int );
//#line  40
    i = tmp;
  }
//#line  42
  __builtin_va_end(marker);
//#line  43
  if (sum) {
//#line  43
    tmp___0 = sum / count;
  } else {
//#line  43
    tmp___0 = 0;
  }
//#line  43
  return (tmp___0);
}
}
//#line  47
/* #pragma ccuredvararg("average",sizeof(union vararg_average )) */
