/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  40 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h"
typedef __builtin_va_list __gnuc_va_list;
//#line  98 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h"
typedef __gnuc_va_list va_list;
//#line  216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
//#line  131 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
//#line  132 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off64_t;
//#line  44 "/usr/include/stdio.h"
struct _IO_FILE ;
//#line  48 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
//#line  150 "/usr/include/libio.h"
typedef void _IO_lock_t;
//#line  156 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
//#line  241 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
//#line  3 "testharness.h"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  237 "/usr/include/stdio.h"
extern int fclose(FILE *__stream ) ;
//#line  272
extern FILE *fopen(char const   * __restrict  __filename , char const   * __restrict  __modes ) ;
//#line  371
extern int vfprintf(FILE * __restrict  __s , char const   * __restrict  __format ,
                    __gnuc_va_list __arg ) ;
//#line  709
extern size_t fread(void * __restrict  __ptr , size_t __size , size_t __n , FILE * __restrict  __stream ) ;
//#line  749
extern int fseek(FILE *__stream , long __off , int __whence ) ;
//#line  143 "/usr/include/string.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1,2), __leaf__)) strncmp)(char const   *__s1 ,
                                                                                                char const   *__s2 ,
                                                                                                size_t __n )  __attribute__((__pure__)) ;
//#line  17 "vararg5.c"
/* #pragma ccuredvararg("talking",printf(2)) */
//#line  18
void talking(FILE *out , char *s  , ...) ;
//#line  20 "vararg5.c"
int main(int argc , char **argv ) 
{ 
  int x ;
  int y ;
  char *s ;
  char buff[128] ;
  float f ;
  double d ;
  FILE *out ;
  FILE *tmp ;
  int tmp___0 ;

  {
//#line  24
  f = (float )5.0;
//#line  25
  d = 10.0;
//#line  27
  tmp = fopen((char const   */* __restrict  */)"vararg.out", (char const   */* __restrict  */)"w+");
//#line  27
  out = tmp;
//#line  28
  if (! out) {
//#line  28
    printf((char const   */* __restrict  */)"Error %d\n", 1);
//#line  28
    exit(1);
  }
//#line  30
  x = 5;
//#line  31
  y = 1;
//#line  32
  s = (char *)"hello";
//#line  33
  talking(out, (char *)"%d %3.1f %3.1f\n", x, (double )f, d);
//#line  34
  fseek(out, 0L, 0);
//#line  35
  fread((void */* __restrict  */)(buff), (size_t )1, sizeof(buff) - 1UL, (FILE */* __restrict  */)out);
//#line  36
  fclose(out);
//#line  37
  buff[10] = (char )'\000';
//#line  38
  printf((char const   */* __restrict  */)"Should be 5 5.0 10.0: %s\n", buff);
//#line  39
  tmp___0 = strncmp((char const   *)(buff), "5 5.0 10.0", (size_t )10);
//#line  39
  if (tmp___0) {
//#line  39
    printf((char const   */* __restrict  */)"Error %d\n", 2);
//#line  39
    exit(2);
  }
//#line  40
  printf((char const   */* __restrict  */)"Success\n");
//#line  40
  exit(0);
}
}
//#line  43 "vararg5.c"
void talking(FILE *out , char *s  , ...) 
{ 
  va_list ap ;

  {
//#line  45
  __builtin_va_start(ap, s);
//#line  46
  vfprintf((FILE */* __restrict  */)out, (char const   */* __restrict  */)s, ap);
//#line  47
  __builtin_va_end(ap);
//#line  48
  return;
}
}
