/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
//#line  131 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
//#line  132 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off64_t;
//#line  44 "/usr/include/stdio.h"
struct _IO_FILE ;
//#line  48 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
//#line  40 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h"
typedef __builtin_va_list __gnuc_va_list;
//#line  150 "/usr/include/libio.h"
typedef void _IO_lock_t;
//#line  156 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
//#line  241 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
//#line  310 "/usr/include/libio.h"
typedef struct _IO_FILE _IO_FILE;
//#line  79 "/usr/include/stdio.h"
typedef __gnuc_va_list va_list;
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned long  , void * ) ;  */
//#line  430 "/usr/include/libio.h"
extern int _IO_putc(int __c , _IO_FILE *__fp ) ;
//#line  170 "/usr/include/stdio.h"
extern struct _IO_FILE *stderr ;
//#line  356
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
//#line  362
extern int printf(char const   * __restrict  format  , ...) ;
//#line  573
extern int fputc(int __c , FILE *__stream ) ;
//#line  543 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
//#line  128 "/usr/include/string.h"
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1,2), __leaf__)) strncpy)(char * __restrict  __dest ,
                                                                                                  char const   * __restrict  __src ,
                                                                                                  size_t __n ) ;
//#line  79 "/usr/include/ctype.h"
extern  __attribute__((__nothrow__)) unsigned short const   **( __attribute__((__leaf__)) __ctype_b_loc)(void)  __attribute__((__const__)) ;
//#line  9 "vararg3.c"
char *progname  =    (char *)"vararg3";
//#line  10 "vararg3.c"
int showmessages  =    1;
//#line  12
/* #pragma ccuredvararg("my_vfprintf",printf(2)) */
//#line  13
int my_vfprintf(FILE *stream , char const   *format , va_list vargs ) ;
//#line  15
/* #pragma ccuredvararg("pm_error",printf(1)) */
//#line  16 "vararg3.c"
void pm_error(char *format  , ...) 
{ 
  va_list args ;

  {
//#line  19
  __builtin_va_start(args, format);
//#line  21
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"%s: ",
          progname);
//#line  22
  my_vfprintf(stderr, (char const   *)format, args);
//#line  23
  fputc('\n', stderr);
//#line  24
  __builtin_va_end(args);
//#line  25
  return;
}
}
//#line  33 "vararg3.c"
int my_vfprintf(FILE *stream , char const   *format , va_list vargs ) 
{ 
  int n ;
  char *ep ;
  char fchar ;
  char tformat[512] ;
  int do_long ;
  int i ;
  long l ;
  unsigned int u ;
  unsigned long ul ;
  char *s ;
  double d ;
  unsigned short const   **tmp ;
  unsigned short const   **tmp___0 ;
  long tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  unsigned long tmp___5 ;
  int tmp___6 ;
  unsigned int tmp___7 ;
  int tmp___8 ;
  int tmp___10 ;
  int tmp___11 ;
  char *tmp___12 ;
  int tmp___13 ;
  double tmp___14 ;
  int tmp___15 ;

  {
//#line  46
  n = 0;
//#line  47
  while ((int const   )*format != 0) {
//#line  49
    if ((int const   )*format != 37) {
//#line  51
      _IO_putc((int )*format, stream);
//#line  52
      n ++;
//#line  53
      format ++;
    } else {
//#line  57
      do_long = 0;
//#line  58
      ep = (char *)(format + 1);
//#line  61
      if ((int )*ep == 45) {
//#line  62
        ep ++;
      }
//#line  63
      if ((int )*ep == 48) {
//#line  64
        ep ++;
      }
//#line  65
      while (1) {
//#line  65
        tmp = __ctype_b_loc();
//#line  65
        if (! ((int const   )*(*tmp + (int )*ep) & 2048)) {
//#line  65
          break;
        }
//#line  66
        ep ++;
      }
//#line  67
      if ((int )*ep == 46) {
//#line  69
        ep ++;
//#line  70
        while (1) {
//#line  70
          tmp___0 = __ctype_b_loc();
//#line  70
          if (! ((int const   )*(*tmp___0 + (int )*ep) & 2048)) {
//#line  70
            break;
          }
//#line  71
          ep ++;
        }
      }
//#line  73
      if ((int )*ep == 35) {
//#line  74
        ep ++;
      }
//#line  75
      if ((int )*ep == 108) {
//#line  77
        do_long = 1;
//#line  78
        ep ++;
      }
//#line  84
      fchar = *ep;
//#line  85
      strncpy((char */* __restrict  */)(tformat), (char const   */* __restrict  */)format,
              (size_t )((ep - (char *)format) + 1L));
//#line  86
      tformat[(ep - (char *)format) + 1L] = (char )'\000';
//#line  91
      switch ((int )fchar) {
      case 100: 
//#line  94
      if (do_long) {
//#line  96
        tmp___1 = __builtin_va_arg(vargs, long );
//#line  96
        l = tmp___1;
//#line  97
        tmp___2 = fprintf((FILE */* __restrict  */)stream, (char const   */* __restrict  */)(tformat),
                          l);
//#line  97
        n += tmp___2;
      } else {
//#line  101
        tmp___3 = __builtin_va_arg(vargs, int );
//#line  101
        i = tmp___3;
//#line  102
        tmp___4 = fprintf((FILE */* __restrict  */)stream, (char const   */* __restrict  */)(tformat),
                          i);
//#line  102
        n += tmp___4;
      }
//#line  104
      break;
      case 117: 
      case 88: 
      case 120: 
      case 111: 
//#line  110
      if (do_long) {
//#line  112
        tmp___5 = __builtin_va_arg(vargs, unsigned long );
//#line  112
        ul = tmp___5;
//#line  113
        tmp___6 = fprintf((FILE */* __restrict  */)stream, (char const   */* __restrict  */)(tformat),
                          ul);
//#line  113
        n += tmp___6;
      } else {
//#line  117
        tmp___7 = __builtin_va_arg(vargs, unsigned int );
//#line  117
        u = tmp___7;
//#line  118
        tmp___8 = fprintf((FILE */* __restrict  */)stream, (char const   */* __restrict  */)(tformat),
                          u);
//#line  118
        n += tmp___8;
      }
//#line  120
      break;
      case 99: 
//#line  123
      tmp___10 = __builtin_va_arg(vargs, int );
//#line  123
      i = (int )((char )tmp___10);
//#line  124
      tmp___11 = fprintf((FILE */* __restrict  */)stream, (char const   */* __restrict  */)(tformat),
                         i);
//#line  124
      n += tmp___11;
//#line  125
      break;
      case 115: 
//#line  128
      tmp___12 = __builtin_va_arg(vargs, char *);
//#line  128
      s = tmp___12;
//#line  129
      tmp___13 = fprintf((FILE */* __restrict  */)stream, (char const   */* __restrict  */)(tformat),
                         s);
//#line  129
      n += tmp___13;
//#line  130
      break;
      case 71: 
      case 103: 
      case 102: 
      case 69: 
      case 101: 
//#line  137
      tmp___14 = __builtin_va_arg(vargs, double );
//#line  137
      d = tmp___14;
//#line  138
      tmp___15 = fprintf((FILE */* __restrict  */)stream, (char const   */* __restrict  */)(tformat),
                         d);
//#line  138
      n += tmp___15;
//#line  139
      break;
      case 37: 
//#line  142
      _IO_putc('%', stream);
//#line  143
      n ++;
//#line  144
      break;
      default: 
//#line  147
      return (-1);
      }
//#line  151
      format = (char const   *)(ep + 1);
    }
  }
//#line  154
  return (n);
}
}
//#line  159 "vararg3.c"
int main(void) 
{ 


  {
//#line  160
  pm_error((char *)"Cucu %s", "Bau");
//#line  161
  printf((char const   */* __restrict  */)"Success\n");
//#line  161
  exit(0);
}
}
