/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
//#line  131 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
//#line  132 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off64_t;
//#line  44 "/usr/include/stdio.h"
struct _IO_FILE ;
//#line  48 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
//#line  40 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h"
typedef __builtin_va_list __gnuc_va_list;
//#line  150 "/usr/include/libio.h"
typedef void _IO_lock_t;
//#line  156 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
//#line  241 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
//#line  79 "/usr/include/stdio.h"
typedef __gnuc_va_list va_list;
//#line  8 "vararg7.c"
struct mystruct {
   int i ;
   char *s ;
};
//#line  14 "vararg7.c"
struct dns_rdatacallbacks {
   long add ;
   void ( /* format attribute */ __attribute__((__ccuredvararg__(sizeof(struct mystruct )))) (*error))(struct dns_rdatacallbacks * ,
                                                                                                       char const   * 
                                                                                                       , ...) ;
   void ( /* format attribute */ __attribute__((__ccuredvararg__(sizeof(struct mystruct )))) (*warn))(struct dns_rdatacallbacks * ,
                                                                                                      char const   * 
                                                                                                      , ...) ;
   void *add_private ;
   void *error_private ;
   void *warn_private ;
};
//#line  14 "vararg7.c"
typedef struct dns_rdatacallbacks dns_rdatacallbacks_t;
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
//#line  170 "/usr/include/stdio.h"
extern struct _IO_FILE *stderr ;
//#line  356
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
//#line  371
extern int vfprintf(FILE * __restrict  __s , char const   * __restrict  __format ,
                    __gnuc_va_list __arg ) ;
//#line  40 "vararg7.c"
static void ( /* format attribute */  stdio_error_warn_callback)(dns_rdatacallbacks_t *callbacks ,
                                                                 char const   *fmt 
                                                                 , ...) ;
//#line  44 "vararg7.c"
static void ( /* format attribute */  stdio_error_warn_callback)(dns_rdatacallbacks_t *callbacks ,
                                                                 char const   *fmt 
                                                                 , ...) 
{ 
  va_list ap ;

  {
//#line  52
  __builtin_va_start(ap, fmt);
//#line  53
  vfprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)fmt,
           ap);
//#line  54
  __builtin_va_end(ap);
//#line  55
  fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"\n");
//#line  56
  return;
}
}
//#line  58 "vararg7.c"
void dns_rdatacallbacks_init(dns_rdatacallbacks_t *callbacks ) 
{ 


  {
//#line  60
  callbacks->error = (void ( /* format attribute */ __attribute__((__ccuredvararg__(sizeof(struct mystruct )))) (*))(struct dns_rdatacallbacks * ,
                                                                                                                     char const   * 
                                                                                                                     , ...))(& stdio_error_warn_callback);
//#line  61
  callbacks->warn = (void ( /* format attribute */ __attribute__((__ccuredvararg__(sizeof(struct mystruct )))) (*))(struct dns_rdatacallbacks * ,
                                                                                                                    char const   * 
                                                                                                                    , ...))(& stdio_error_warn_callback);
//#line  62
  return;
}
}
//#line  64 "vararg7.c"
int foo(dns_rdatacallbacks_t *ptr ) 
{ 


  {
//#line  65
  stdio_error_warn_callback(ptr, "Does it work %s", "if we call it directly?");
//#line  66
  (*(ptr->warn))(ptr, "Warning Int %d\n", 55);
//#line  67
  (*(ptr->warn))(ptr, "Warning String %s\n", "mystring");
//#line  68
  return (0);
}
}
