/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  40 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h"
typedef __builtin_va_list __gnuc_va_list;
//#line  79 "/usr/include/stdio.h"
typedef __gnuc_va_list va_list;
//#line  5 "vararg4.c"
union vararg_sum {
   int ints ;
   int *pints ;
};
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned long  , void * ) ;  */
//#line  362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  format  , ...) ;
//#line  11 "vararg4.c"
/* #pragma ccuredvararg("sum",sizeof(union vararg_sum )) */
//#line  12
int sum(int descriptor  , ...) ;
//#line  15
/* #pragma ccuredvararg("sum_valist",sizeof(union vararg_sum )) */
//#line  16
int sum_valist(va_list args , int descriptor ) ;
//#line  12 "testharness.h"
extern void exit(int  ) ;
//#line  20 "vararg4.c"
int main(void) 
{ 
  int i1 ;
  int i2 ;
  int tmp ;

  {
//#line  22
  i1 = 5;
//#line  23
  i2 = 7;
//#line  26
  tmp = sum(10, 3, & i1, 7, & i2, 0);
//#line  26
  if (tmp != 22) {
//#line  26
    printf((char const   */* __restrict  */)"Error %d\n", 1);
//#line  26
    exit(1);
  }
//#line  28
  printf((char const   */* __restrict  */)"Success\n");
//#line  28
  exit(0);
}
}
//#line  36 "vararg4.c"
int sum(int descriptor  , ...) 
{ 
  int sum___0 ;
  va_list marker ;

  {
//#line  41
  __builtin_va_start(marker, descriptor);
//#line  42
  sum___0 = sum_valist(marker, descriptor);
//#line  43
  __builtin_va_end(marker);
//#line  44
  return (sum___0);
}
}
//#line  47 "vararg4.c"
int sum_valist(va_list args , int descriptor ) 
{ 
  int sum___0 ;
  int next ;
  int *tmp___0 ;
  int tmp___1 ;

  {
//#line  48
  sum___0 = 0;
//#line  49
  while (1) {
//#line  51
    if (descriptor & 1) {
//#line  52
      tmp___0 = __builtin_va_arg(args, int *);
//#line  52
      next = *tmp___0;
    } else {
//#line  54
      tmp___1 = __builtin_va_arg(args, int );
//#line  54
      next = tmp___1;
    }
//#line  56
    if (! next) {
//#line  56
      return (sum___0);
    }
//#line  57
    sum___0 += next;
//#line  58
    descriptor >>= 1;
  }
//#line  60
  return (sum___0);
}
}
