/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "voidstar.c"
struct list {
   void *data ;
   struct list *next ;
};
//#line  3 "voidstar.c"
typedef struct list LIST;
//#line  1
extern void *malloc(unsigned int  ) ;
//#line  9
extern void *listfind(LIST *l , int nth ) ;
//#line  12 "voidstar.c"
int listadd(LIST **pl , void *elem ) 
{ 
  LIST *n ;
  void *tmp ;

  {
//#line  13
  tmp = malloc((unsigned int )sizeof(LIST ));
//#line  13
  n = (LIST *)tmp;
//#line  14
  n->data = elem;
//#line  15
  n->next = *pl;
//#line  16
  return ((int )pl);
}
}
//#line  19 "voidstar.c"
LIST *glob  =    (LIST *)0;
//#line  21 "voidstar.c"
int add5(LIST *cell ) 
{ 


  {
//#line  22
  cell->data = (void *)cell;
//#line  23
  listadd(& glob, (void *)(& add5));
//#line  25
  return (0);
}
}
//#line  28 "voidstar.c"
int get1(void) 
{ 
  LIST *l ;
  void *tmp ;

  {
//#line  29
  tmp = listfind(glob, 5);
//#line  29
  l = (LIST *)tmp;
//#line  30
  return (0);
}
}
