/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "voidtypedef.c"
void pimInit(void) ;
//#line  6 "voidtypedef.c"
void pimInit(void) 
{ 


  {
//#line  8
  return;
}
}
//#line  11 "voidtypedef.c"
int main(void) 
{ 


  {
//#line  12
  pimInit();
//#line  13
  return (0);
}
}
