/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  4 "warnings-noreturn.c"
extern  __attribute__((__noreturn__)) void croak() ;
//#line  5
extern  __attribute__((__noreturn__)) void die() ;
//#line  8
 __attribute__((__noreturn__)) void terminate(int frog ) ;
//#line  10
 __attribute__((__noreturn__)) void terminate(int frog ) ;
//#line  10 "warnings-noreturn.c"
void terminate(int frog ) 
{ 


  {
//#line  12
  if (frog) {
//#line  13
    croak();
  } else {
//#line  15
    die();
  }
}
}
//#line  19 "warnings-noreturn.c"
int main(void) 
{ 


  {
//#line  21
  printf("Success\n");
//#line  21
  exit(0);
}
}
