/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  11 "warnings-unused-label.c"
int branch(int selector ) 
{ 


  {
//#line  13
  if (selector) {
//#line  14
    return (1);
  }
//#line  19
  return (0);
}
}
//#line  23 "warnings-unused-label.c"
int main(void) 
{ 


  {
//#line  25
  branch(0);
//#line  26
  printf("Success\n");
//#line  26
  exit(0);
}
}
