/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "warnings-cast.c"
int const   a  =    (int const   )3;
//#line  3 "warnings-cast.c"
int const   *f(void) 
{ 


  {
//#line  4
  return (& a);
}
}
//#line  7 "warnings-cast.c"
int main(void) 
{ 
  int *p ;
  int const   *tmp ;

  {
//#line  10
  tmp = f();
//#line  10
  p = (int *)tmp;
//#line  11
  *p = 4;
//#line  12
  return (*p);
}
}
