/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
//#line  328 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef int wchar_t;
//#line  166 "/usr/include/wchar.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1,2), __leaf__)) wcscmp)(wchar_t const   *__s1 ,
                                                                                               wchar_t const   *__s2 )  __attribute__((__pure__)) ;
//#line  290
extern  __attribute__((__nothrow__)) size_t ( __attribute__((__leaf__)) wcslen)(wchar_t const   *__s )  __attribute__((__pure__)) ;
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  4 "wchar6.c"
int main(void) 
{ 
  wchar_t aa[3] ;
  wchar_t ba[8] ;
  wchar_t *ap ;
  wchar_t *bp ;
  char *p1 ;
  char *p2 ;
  int i ;
  size_t tmp ;
  size_t tmp___0 ;
  size_t tmp___1 ;
  size_t tmp___2 ;
  size_t tmp___3 ;
  size_t tmp___4 ;
  size_t tmp___5 ;
  size_t tmp___6 ;
  int tmp___7 ;
  int tmp___8 ;
  int tmp___9 ;
  int tmp___10 ;

  {
//#line  6
  aa[0] = 65;
//#line  6
  aa[1] = 43981;
//#line  6
  aa[2] = 0;
//#line  7
  ba[0] = 65;
//#line  7
  ba[1] = 92;
//#line  7
  ba[2] = 120;
//#line  7
  ba[3] = 97;
//#line  7
  ba[4] = 98;
//#line  7
  ba[5] = 99;
//#line  7
  ba[6] = 100;
//#line  7
  ba[7] = 0;
//#line  8
  ap = L"A\xABCD" "";
//#line  9
  bp = L"A\\xabcd";
//#line  13
  tmp = wcslen((wchar_t const   *)(aa));
//#line  13
  tmp___0 = wcslen((wchar_t const   *)ap);
//#line  13
  if (tmp != tmp___0) {
//#line  13
    printf("Error %d\n", 1);
//#line  13
    exit(1);
  }
//#line  14
  tmp___1 = wcslen((wchar_t const   *)(ba));
//#line  14
  tmp___2 = wcslen((wchar_t const   *)bp);
//#line  14
  if (tmp___1 != tmp___2) {
//#line  14
    printf("Error %d\n", 2);
//#line  14
    exit(2);
  }
//#line  15
  tmp___3 = wcslen((wchar_t const   *)(aa));
//#line  15
  tmp___4 = wcslen((wchar_t const   *)(ba));
//#line  15
  if (tmp___3 == tmp___4) {
//#line  15
    printf("Error %d\n", 3);
//#line  15
    exit(3);
  }
//#line  16
  tmp___5 = wcslen((wchar_t const   *)ap);
//#line  16
  tmp___6 = wcslen((wchar_t const   *)bp);
//#line  16
  if (tmp___5 == tmp___6) {
//#line  16
    printf("Error %d\n", 4);
//#line  16
    exit(4);
  }
//#line  18
  p1 = (char *)(aa);
//#line  19
  p2 = (char *)ap;
//#line  20
  i = 0;
//#line  20
  while ((unsigned long )i < 2UL * sizeof(wchar_t )) {
//#line  21
    if ((int )*(p1 + i) != (int )*(p2 + i)) {
//#line  21
      printf("Error %d\n", 5);
//#line  21
      exit(5);
    }
//#line  20
    i ++;
  }
//#line  23
  p1 = (char *)(ba);
//#line  24
  p2 = (char *)bp;
//#line  25
  i = 0;
//#line  25
  while ((unsigned long )i < 7UL * sizeof(wchar_t )) {
//#line  26
    if ((int )*(p1 + i) != (int )*(p2 + i)) {
//#line  26
      printf("Error %d\n", 6);
//#line  26
      exit(6);
    }
//#line  25
    i ++;
  }
//#line  29
  tmp___7 = wcscmp((wchar_t const   *)(aa), (wchar_t const   *)ap);
//#line  29
  if (tmp___7 != 0) {
//#line  29
    printf("Error %d\n", 7);
//#line  29
    exit(7);
  }
//#line  30
  tmp___8 = wcscmp((wchar_t const   *)(ba), (wchar_t const   *)bp);
//#line  30
  if (tmp___8 != 0) {
//#line  30
    printf("Error %d\n", 8);
//#line  30
    exit(8);
  }
//#line  31
  tmp___9 = wcscmp((wchar_t const   *)(aa), (wchar_t const   *)(ba));
//#line  31
  if (tmp___9 == 0) {
//#line  31
    printf("Error %d\n", 9);
//#line  31
    exit(9);
  }
//#line  32
  tmp___10 = wcscmp((wchar_t const   *)ap, (wchar_t const   *)bp);
//#line  32
  if (tmp___10 == 0) {
//#line  32
    printf("Error %d\n", 10);
//#line  32
    exit(10);
  }
//#line  34
  printf("Success\n");
//#line  34
  exit(0);
}
}
