/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  328 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef int wchar_t;
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  7 "wchar5.c"
int main(void) 
{ 
  wchar_t a[4] ;
  wchar_t b[4] ;
  int i ;

  {
//#line  11
  a[0] = 72;
//#line  11
  a[1] = 105;
//#line  11
  a[2] = 43981;
//#line  11
  a[3] = 0;
//#line  13
  b[0] = 72;
//#line  13
  b[1] = 105;
//#line  13
  b[2] = 43981;
//#line  13
  b[3] = 0;
//#line  17
  i = 0;
//#line  17
  while (i < 4) {
//#line  18
    if (a[i] != b[i]) {
//#line  18
      printf("Error %d\n", i);
//#line  18
      exit(i);
    }
//#line  17
    i ++;
  }
//#line  21
  printf("Success\n");
//#line  21
  exit(0);
}
}
