/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "wchar2.c"
int main(void) 
{ 
  long w ;
  char *s ;

  {
//#line  4
  w = 87L;
//#line  5
  s = (char *)"W";
//#line  8
  if (w != (long )*(s + 0)) {
//#line  8
    printf("Error %d\n", 1);
//#line  8
    exit(1);
  }
//#line  9
  printf("Success\n");
//#line  9
  exit(0);
}
}
