/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  328 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef int wchar_t;
//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  4 "wchar1.c"
int main(void) 
{ 
  wchar_t *wbase ;
  char *w ;
  char *s ;
  int i ;
  short foo ;
  char little_endian ;
  int tmp ;
  int tmp___0 ;

  {
//#line  5
  wbase = L"Hello, world";
//#line  6
  w = (char *)wbase;
//#line  7
  s = (char *)"Hello, world";
//#line  11
  foo = (short)17;
//#line  12
  little_endian = (char )((int )*((char *)(& foo)));
//#line  14
  i = 0;
//#line  14
  while (i < 10) {
//#line  15
    if (little_endian) {
//#line  15
      tmp = (int )*(s + i);
    } else {
//#line  15
      tmp = 0;
    }
//#line  15
    if ((int )*(w + (unsigned long )i * sizeof(wchar_t )) != tmp) {
//#line  16
      printf("Error %d\n", 1);
//#line  16
      exit(1);
    }
//#line  18
    if (little_endian) {
//#line  18
      tmp___0 = 0;
    } else {
//#line  18
      tmp___0 = (int )*(s + i);
    }
//#line  18
    if ((int )*(w + ((unsigned long )i * sizeof(wchar_t ) + (sizeof(wchar_t ) - 1UL))) != tmp___0) {
//#line  20
      printf("Error %d\n", 2);
//#line  20
      exit(2);
    }
//#line  14
    i ++;
  }
//#line  23
  printf("Success\n");
//#line  23
  exit(0);
}
}
