/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  328 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef int wchar_t;
//#line  362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  format  , ...) ;
//#line  12 "testharness.h"
extern void exit(int  ) ;
//#line  20 "wchar4.c"
int main(void) 
{ 
  wchar_t wa[5] ;
  char *a_16bit ;
  char *a_32bit ;
  wchar_t wb[4] ;
  unsigned char b[4] ;
  int i ;
  char *tmp ;
  char *tmp___0 ;
  wchar_t c ;
  unsigned short s ;
  int c2 ;

  {
//#line  21
  wa[0] = 72;
//#line  21
  wa[1] = 105;
//#line  21
  wa[2] = 43981;
//#line  21
  wa[3] = 101;
//#line  21
  wa[4] = 0;
//#line  26
  a_16bit = (char *)"H\000i\000\315\253e\000";
//#line  27
  a_32bit = (char *)"H\000\000\000i\000\000\000\315\253\000\000e\000\000\000";
//#line  29
  wb[0] = 72;
//#line  29
  wb[1] = 105;
//#line  29
  wb[2] = 192;
//#line  29
  wb[3] = 0;
//#line  30
  b[0] = (unsigned char )'H';
//#line  30
  b[1] = (unsigned char )'i';
//#line  30
  b[2] = (unsigned char )'\300';
//#line  30
  b[3] = (unsigned char )'\000';
//#line  33
  if (sizeof(wchar_t ) == 2UL) {
//#line  35
    tmp = (char *)(wa);
//#line  36
    i = 0;
//#line  36
    while (i < 8) {
//#line  37
      if ((int )*(tmp + i) != (int )*(a_16bit + i)) {
//#line  37
        printf((char const   */* __restrict  */)"Error %d\n", 1);
//#line  37
        exit(1);
      }
//#line  36
      i ++;
    }
  } else
//#line  40
  if (sizeof(wchar_t ) == 4UL) {
//#line  42
    tmp___0 = (char *)(wa);
//#line  43
    i = 0;
//#line  43
    while (i < 16) {
//#line  44
      if ((int )*(tmp___0 + i) != (int )*(a_32bit + i)) {
//#line  44
        printf((char const   */* __restrict  */)"Error %d\n", 2);
//#line  44
        exit(2);
      }
//#line  43
      i ++;
    }
  } else {
//#line  49
    printf((char const   */* __restrict  */)"Error %d\n", 3);
//#line  49
    exit(3);
  }
//#line  52
  i = 0;
//#line  52
  while (i < 4) {
//#line  53
    if ((int )b[i] != (int )((unsigned char )wb[i])) {
//#line  53
      printf((char const   */* __restrict  */)"Error %d\n", 4);
//#line  53
      exit(4);
    }
//#line  52
    i ++;
  }
//#line  61
  c = 43981;
//#line  62
  s = (unsigned short)43981;
//#line  63
  if ((int )s != c) {
//#line  63
    printf((char const   */* __restrict  */)"Error %d\n", 10);
//#line  63
    exit(10);
  }
//#line  64
  c2 = 99;
//#line  65
  if (c2 != 99) {
//#line  65
    printf((char const   */* __restrict  */)"Error %d\n", 11);
//#line  65
    exit(11);
  }
//#line  68
  printf((char const   */* __restrict  */)"Success\n");
//#line  68
  exit(0);
}
}
