/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "testharness.h"
extern int printf(char const   *format  , ...) ;
//#line  12
extern void exit(int  ) ;
//#line  3 "wchar3.c"
int check(char *p1 , char *p2 , int size , int code ) 
{ 
  int i ;

  {
//#line  5
  i = 0;
//#line  5
  while (i < size) {
//#line  6
    if ((int )*(p1 + i) != (int )*(p2 + i)) {
//#line  7
      printf("Error %d\n", code);
//#line  7
      exit(code);
    }
//#line  5
    i ++;
  }
//#line  10
  return (0);
}
}
//#line  12 "wchar3.c"
int main(void) 
{ 
  long l1 ;
  char *s1 ;
  long l2 ;
  char *s2 ;
  long l3 ;
  char *s3 ;
  long l4 ;
  char *s4 ;

  {
//#line  13
  l1 = 16933123L;
//#line  14
  s1 = (char *)"\003a\002\001";
//#line  16
  l2 = 6382179L;
//#line  17
  s2 = (char *)"cba";
//#line  19
  l3 = 1886350406L;
//#line  20
  s3 = (char *)"Flop";
//#line  22
  l4 = 3338L;
//#line  23
  s4 = (char *)"\n\r";
//#line  25
  check((char *)(& l1), s1, 4, 1);
//#line  26
  check((char *)(& l2), s2, 3, 2);
//#line  27
  check((char *)(& l3), s3, 4, 3);
//#line  28
  check((char *)(& l4), s4, 2, 4);
//#line  30
  printf("Success\n");
//#line  30
  exit(0);
}
}
