/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  3 "wrongnumargs.c"
void f(char *s1 , char *s2 ) 
{ 


  {
//#line  5
  printf((char const   */* __restrict  */)s1, s2);
//#line  6
  return;
}
}
//#line  8 "wrongnumargs.c"
int main(int argc , char **argv ) 
{ 


  {
//#line  9
  f((char *)"hello %S!\n", (char *)"wow");
//#line  10
  f((char *)"hello there: %s!\n", (char *)"wow");
//#line  11
  f((char *)"hello again!\n");
//#line  12
  return (0);
}
}
