/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "asmfndecl.c"
typedef void (*__sighandler_t)(int  );
//#line  3
extern __sighandler_t mysignal(int __sig , void (*__handler)(int  ) )  __asm__("__sysv_signal")  ;
//#line  7 "asmfndecl.c"
int main(void) 
{ 


  {
//#line  10
  mysignal(5, (void (*)(int  ))0);
//#line  11
  return (0);
}
}
