/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 5 "baddef2.c"
struct S {
   int x ;
   int y ;
   int z ;
};
#line 362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 11 "baddef2.c"
int size2(void) 
{ 


  {
#line 11
  return ((int )sizeof(struct S ));
}
}
#line 12
extern int size1() ;
#line 14 "baddef2.c"
int main(void) 
{ 
  int s1 ;
  int s2 ;

  {
#line 18
  s1 = size1();
#line 18
  printf((char const   */* __restrict  */)"size1: %d\n", s1);
#line 19
  s2 = size2();
#line 19
  printf((char const   */* __restrict  */)"size2: %d\n", s2);
#line 20
  printf((char const   */* __restrict  */)"(correct output is 8, then 12)\n");
#line 22
  if (s1 == 8) {
#line 22
    if (s2 == 12) {
#line 23
      return (0);
    } else {
#line 26
      return (2);
    }
  } else {
#line 26
    return (2);
  }
}
}
