/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 3 "baddef1.c"
struct S {
   int x ;
   int y ;
};
#line 8 "baddef1.c"
int size1(void) 
{ 


  {
#line 8
  return ((int )sizeof(struct S ));
}
}
