/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "bisonerror.c"
struct core {
   int somefield ;
};
//#line  3 "bisonerror.c"
typedef struct core core;
//#line  7 "bisonerror.c"
void closure(short *core___0 , int n ) 
{ 
  short *csend ;

  {
//#line  10
  csend = core___0 + n;
//#line  11
  return;
}
}
//#line  13 "bisonerror.c"
int main(void) 
{ 


  {
//#line  15
  return (0);
}
}
