/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  8 "bogus_redef.c"
static int bar(void) ;
//#line  5 "bogus_redef.c"
int foo(void) 
{ 
  int tmp ;

  {
//#line  8
  tmp = bar();
//#line  8
  return (tmp);
}
}
//#line  12 "bogus_redef.c"
static int bar(void) 
{ 


  {
//#line  15
  return (4);
}
}
//#line  18 "bogus_redef.c"
int main(void) 
{ 
  int tmp ;

  {
//#line  20
  tmp = foo();
//#line  20
  return (tmp - 4);
}
}
