/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  5 "cmpzero.c"
int main(void) 
{ 
  int *i ;
  char c ;

  {
//#line  7
  i = (int *)512;
//#line  8
  c = (char )i;
//#line  10
  printf((char const   */* __restrict  */)"i: %d\n", (int )i);
//#line  11
  printf((char const   */* __restrict  */)"c: %d\n", (int )c);
//#line  13
  if ((unsigned long )i == (unsigned long )((int *)0)) {
//#line  14
    printf((char const   */* __restrict  */)"yes. This is not correct!!\n");
//#line  15
    return (1);
  } else {
//#line  18
    printf((char const   */* __restrict  */)"no\n");
  }
//#line  21
  if ((int )((char )i) == 0) {
//#line  22
    printf((char const   */* __restrict  */)"2nd yes\n");
  } else {
//#line  25
    printf((char const   */* __restrict  */)"2nd no\n");
  }
//#line  27
  printf((char const   */* __restrict  */)"Success\n");
//#line  28
  return (0);
}
}
