/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 8 "comb1.c"
int global_com4  ;
#line 11 "comb1.c"
int *globalPtr  ;
#line 13 "comb1.c"
void hpfy(void) 
{ 
  int local ;

  {
#line 16
  globalPtr = & local;
#line 17
  return;
}
}
#line 19 "comb1.c"
int foo_com1(int x ) 
{ 


  {
#line 21
  return (x + global_com4);
}
}
