/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 4 "comb4.c"
int global_com4  =    5;
#line 5
extern int foo2_com2(int x ) ;
#line 7 "comb4.c"
int foo2_com4(int x ) 
{ 
  int tmp ;

  {
#line 9
  tmp = foo2_com2(x);
#line 9
  return (tmp + 4);
}
}
