/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 3 "../small1/testharness.h"
extern int printf(char const   *format  , ...) ;
#line 12
extern void exit(int  ) ;
#line 6 "comb2.c"
static int global_com2  =    5;
#line 8 "comb2.c"
int foo2_com2(int x ) 
{ 


  {
#line 10
  return (x + global_com2);
}
}
#line 13
extern int foo_com3(int x ) ;
#line 14
extern void hpfy() ;
#line 19
extern int ( /* missing proto */  foo2_com4)() ;
#line 16 "comb2.c"
int main(void) 
{ 
  int res1 ;
  int tmp ;
  int res2 ;
  int tmp___0 ;

  {
#line 18
  tmp = foo_com3(6);
#line 18
  res1 = tmp;
#line 19
  tmp___0 = foo2_com4(61);
#line 19
  res2 = tmp___0;
#line 20
  printf("foo_com3(6): %d\n", res1);
#line 21
  printf("foo2_com4(61): %d\n", res2);
#line 22
  if ((unsigned long )res1 != 11UL + sizeof(int *)) {
#line 22
    printf("Error %d\n", 1);
#line 22
    exit(1);
  }
#line 23
  if (res2 != 70) {
#line 23
    printf("Error %d\n", 2);
#line 23
    exit(2);
  }
#line 24
  hpfy();
#line 25
  return (0);
}
}
