/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 5 "comb3.c"
extern int foo_com1(int x ) ;
#line 7 "comb3.c"
int foo_com3(int x ) 
{ 
  int tmp ;

  {
#line 9
  tmp = foo_com1(x);
#line 9
  return ((int )((unsigned long )tmp + sizeof(int *)));
}
}
