/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
//#line  394 "/usr/include/string.h"
extern  __attribute__((__nothrow__)) size_t ( __attribute__((__nonnull__(1), __leaf__)) strlen)(char const   *__s )  __attribute__((__pure__)) ;
//#line  6 "constdecl.c"
static int foo(char const   *a , char const   *b ) ;
//#line  9 "constdecl.c"
static int foo(char const   *a , char const   *b ) 
{ 
  size_t tmp ;
  size_t tmp___0 ;

  {
//#line  17
  tmp = strlen(a);
//#line  17
  tmp___0 = strlen(b);
//#line  17
  return ((int )(tmp + tmp___0));
}
}
//#line  20 "constdecl.c"
int main(void) 
{ 
  int tmp ;

  {
//#line  22
  tmp = foo("aa", "bbb");
//#line  22
  return (tmp - 5);
}
}
