/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "constfold.c"
double sqrt(double x ) 
{ 


  {
//#line  6
  return (x * x);
}
}
//#line  9 "constfold.c"
int main(void) 
{ 
  float z10 ;
  float z5 ;
  float tmp12 ;
  double a ;
  double b ;
  double c ;
  double root ;
  double tmp ;

  {
//#line  13
  tmp12 = (float )(- 2.613125930) * z10 + z5;
//#line  18
  tmp = sqrt(b * b - ((double )4 * a) * c);
//#line  18
  root = (- b - tmp) / ((double )2 * a);
//#line  21
  return (0);
}
}
