/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  79 "/usr/include/ctype.h"
extern  __attribute__((__nothrow__)) unsigned short const   **( __attribute__((__leaf__)) __ctype_b_loc)(void)  __attribute__((__const__)) ;
//#line  362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  6 "ctype.c"
void analyze(int ch ) 
{ 
  unsigned short const   **tmp ;
  int tmp___0 ;
  unsigned short const   **tmp___1 ;
  int tmp___2 ;

  {
//#line  8
  printf((char const   */* __restrict  */)"character: %c\n", ch);
//#line  9
  printf((char const   */* __restrict  */)"  decimal: %d\n", ch);
//#line  10
  tmp = __ctype_b_loc();
//#line  10
  if ((int const   )*(*tmp + ch) & 1024) {
//#line  10
    tmp___0 = 1;
  } else {
//#line  10
    tmp___0 = 0;
  }
//#line  10
  printf((char const   */* __restrict  */)"  isalpha: %d\n", tmp___0);
//#line  11
  tmp___1 = __ctype_b_loc();
//#line  11
  if ((int const   )*(*tmp___1 + ch) & 2048) {
//#line  11
    tmp___2 = 1;
  } else {
//#line  11
    tmp___2 = 0;
  }
//#line  11
  printf((char const   */* __restrict  */)"  isdigit: %d\n", tmp___2);
//#line  12
  return;
}
}
//#line  14 "ctype.c"
int main(void) 
{ 


  {
//#line  16
  analyze('a');
//#line  17
  analyze('5');
//#line  18
  analyze('$');
//#line  19
  analyze('Z');
//#line  20
  return (0);
}
}
