/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "enuminit.c"
extern int printf(char const   *fmt  , ...) ;
//#line  17 "enuminit.c"
int main(void) 
{ 


  {
//#line  19
  printf("whazzup?!\n");
//#line  20
  printf("_RLIMIT_CPU = %d\n", 0);
//#line  21
  printf("RLIMIT_CPU = %d\n", 0);
//#line  22
  printf("_RLIMIT_FSIZE = %d\n", 1);
//#line  23
  printf("RLIMIT_FSIZE = %d\n", 1);
//#line  24
  printf("_RLIMIT_DATA = %d\n", 2);
//#line  25
  printf("RLIMIT_DATA = %d\n", 2);
//#line  26
  return (0);
}
}
