/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "enumattr.c"
enum __anonenum_large_enum_59528521 {
    x = 256
}  __attribute__((__packed__)) ;
//#line  4 "enumattr.c"
typedef enum __anonenum_large_enum_59528521 large_enum;
//#line  8 "enumattr.c"
large_enum enum_l  =    (large_enum )256;
//#line  10 "enumattr.c"
int main(void) 
{ 


  {
//#line  12
  return (0);
}
}
