/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  2 "errorinfn.c"
int main(void) 
{ 
  char c[8] ;

  {
//#line  3
  c[0] = (char )'a';
//#line  3
  c[1] = (char )'n';
//#line  3
  c[2] = (char )' ';
//#line  3
  c[3] = (char )'e';
//#line  3
  c[4] = (char )'r';
//#line  3
  c[5] = (char )'r';
//#line  3
  c[6] = (char )'o';
//#line  3
  c[7] = (char )'r';
//#line  4
  return ((((int )c[0] - 97) + (int )c[7]) - 114);
}
}
