/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 9 "./extinline-tmp.c"
__inline static int identity__extinline(int x ) 
{ 


  {
#line 10
  return (x);
}
}
#line 13 "./extinline-tmp.c"
int foo(int x ) 
{ 
  int tmp ;

  {
#line 14
  tmp = identity__extinline(x);
#line 14
  return (tmp);
}
}
#line 25
int identity(int x ) ;
#line 26 "./extinline-tmp.c"
int identity(int x ) 
{ 


  {
#line 27
  return (x + 2);
}
}
#line 31 "./extinline-tmp.c"
int main(int *p , char **argv ) 
{ 
  int tmp ;
  int tmp___0 ;

  {
#line 33
  tmp = identity(-2);
#line 33
  tmp___0 = foo(0);
#line 33
  return (tmp + tmp___0);
}
}
