/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
//#line  6 "funcptr.c"
struct S {
   int ix ;
   int *py ;
};
//#line  12 "funcptr.c"
struct T {
   int *px ;
   int iy ;
};
//#line  466 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
//#line  483
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) free)(void *__ptr ) ;
//#line  362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  19 "funcptr.c"
int multXbyY(struct S *ps , int a ) 
{ 


  {
//#line  21
  printf((char const   */* __restrict  */)"in multXbyY, a is %d\n", a);
//#line  22
  return (ps->ix * *(ps->py) + a);
}
}
//#line  25 "funcptr.c"
int zero  =    0;
//#line  27 "funcptr.c"
int doSomethingToS(struct S *ps , int (*func)(struct S *ps , int a ) ) 
{ 
  struct S *wildptr ;
  struct T *pt ;
  void *tmp ;
  void *tmp___0 ;
  int tmp___1 ;

  {
//#line  29
  wildptr = ps;
//#line  31
  printf((char const   */* __restrict  */)"in doSomethingToS\n");
//#line  34
  if (zero) {
//#line  35
    tmp = malloc(sizeof(*pt));
//#line  35
    pt = (struct T *)tmp;
//#line  36
    tmp___0 = malloc(sizeof(*(pt->px)));
//#line  36
    pt->px = (int *)tmp___0;
//#line  37
    *(pt->px) = 3;
//#line  38
    pt->iy = 13;
//#line  40
    wildptr = (struct S *)pt;
  }
//#line  48
  printf((char const   */* __restrict  */)"calling func with a=%d\n", 9);
//#line  49
  tmp___1 = (*func)(wildptr, 9);
//#line  49
  return (tmp___1);
}
}
//#line  52 "funcptr.c"
int main(void) 
{ 
  struct S *ps ;
  void *tmp ;
  int ret ;
  void *tmp___0 ;
  int tmp___1 ;

  {
//#line  54
  tmp = malloc(sizeof(*ps));
//#line  54
  ps = (struct S *)tmp;
//#line  57
  ps->ix = 8;
//#line  58
  tmp___0 = malloc(sizeof(*(ps->py)));
//#line  58
  ps->py = (int *)tmp___0;
//#line  59
  *(ps->py) = 9;
//#line  60
  tmp___1 = doSomethingToS(ps, & multXbyY);
//#line  60
  ret = tmp___1 - 81;
//#line  62
  free((void *)ps);
//#line  64
  printf((char const   */* __restrict  */)"returning %d from main\n", ret);
//#line  65
  return (ret);
}
}
