/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "funcname.c"
extern void exit(int  ) ;
//#line  2
extern int strcmp(char const   * , char const   * ) ;
//#line  3
extern int printf(char const   *  , ...) ;
//#line  8 "funcname.c"
int main(void) 
{ 
  int tmp ;
  int tmp___0 ;

  {
//#line  10
  printf("__FUNCTION__ = %s\n", "main");
//#line  11
  printf("__PRETTY_FUNCTION__ = %s\n", "main");
//#line  13
  tmp = strcmp("This is main", "This is main");
//#line  13
  if (tmp) {
//#line  15
    exit(1);
  } else {
//#line  13
    tmp___0 = strcmp("This is main", "This is main");
//#line  13
    if (tmp___0) {
//#line  15
      exit(1);
    }
  }
//#line  17
  exit(0);
}
}
