/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "gimpdouble.c"
enum __anonenum_Something_873992740 {
    ZERO = 0,
    ONE = 1
} ;
//#line  4 "gimpdouble.c"
typedef enum __anonenum_Something_873992740 Something;
//#line  9 "gimpdouble.c"
int main(void) 
{ 
  double d ;
  Something s ;

  {
//#line  14
  d = (double )0;
//#line  15
  s = (Something )d;
//#line  17
  return ((int )s);
}
}
