/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  2 "globalprob.c"
struct __anonstruct_spinlock_t_552361886 {
   unsigned int volatile   lock ;
};
//#line  2 "globalprob.c"
typedef struct __anonstruct_spinlock_t_552361886 spinlock_t;
//#line  6 "globalprob.c"
spinlock_t runqueue_lock  __attribute__((__section__(".data.cacheline_aligned"), __aligned__(32)))  =    {(unsigned int volatile   )1};
//#line  10 "globalprob.c"
int main(void) 
{ 


  {
//#line  11
  return (0);
}
}
