/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "invalredef.c"
int wchgat(void const   *opts  __attribute__((__unused__)) ) ;
//#line  5 "invalredef.c"
int wchgat(void const   *opts  __attribute__((__unused__)) ) 
{ 


  {
//#line  7
  return (1);
}
}
//#line  10 "invalredef.c"
int main(void) 
{ 


  {
//#line  11
  return (0);
}
}
