/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  543 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
//#line  7 "lexnum.c"
void print$Int(char *label , int i , int shouldBe ) 
{ 


  {
//#line  9
  printf((char const   */* __restrict  */)"%s: decimal %d, octal 0%o, hex 0x%X, shouldBe %d (decimal)\n",
         label, i, i, i, shouldBe);
//#line  11
  if (i != shouldBe) {
//#line  12
    printf((char const   */* __restrict  */)"this is wrong\n");
//#line  13
    exit(2);
  }
//#line  15
  return;
}
}
//#line  19 "lexnum.c"
int main(void) 
{ 


  {
//#line  21
  print$Int((char *)"0", 0, 0);
//#line  22
  print$Int((char *)"1", 1, 1);
//#line  23
  print$Int((char *)"10", 10, 10);
//#line  24
  print$Int((char *)"010", 8, 8);
//#line  25
  print$Int((char *)"0x10", 16, 16);
//#line  26
  print$Int((char *)"100", 100, 100);
//#line  27
  print$Int((char *)"0100", 64, 64);
//#line  28
  print$Int((char *)"0101", 65, 65);
//#line  29
  print$Int((char *)"0x0101", 257, 257);
//#line  30
  print$Int((char *)"1 | 64 | 512", 577, 577);
//#line  31
  print$Int((char *)"01 | 0100", 65, 65);
//#line  32
  print$Int((char *)"01 | 0100 | 01000", 577, 577);
//#line  34
  print$Int((char *)"0xFFFFFFFF", -1, -1);
//#line  35
  print$Int((char *)"0x80000000 | 0x7FFFFFFFU", -1, -1);
//#line  36
  return (0);
}
}
