/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "litstruct.c"
struct Foo {
   int a ;
   int b ;
};
//#line  1
extern void exit(int  ) ;
//#line  3 "litstruct.c"
struct Foo structure  ;
//#line  8 "litstruct.c"
int main(void) 
{ 
  char **foo ;
  struct Foo __constr_expr_0 ;
  char *__constr_expr_1[3] ;
  int __constr_expr_2[3] ;

  {
//#line  12
  __constr_expr_0.a = 3;
//#line  12
  __constr_expr_0.b = 4;
//#line  12
  structure = __constr_expr_0;
//#line  13
  if (structure.a + structure.b != 7) {
//#line  13
    exit(1);
  }
//#line  16
  __constr_expr_1[0] = (char *)"x";
//#line  16
  __constr_expr_1[1] = (char *)"y";
//#line  16
  __constr_expr_1[2] = (char *)"z";
//#line  16
  foo = __constr_expr_1;
//#line  17
  if ((int )*(*(foo + 1)) != 121) {
//#line  17
    exit(2);
  }
//#line  20
  __constr_expr_2[0] = 1;
//#line  20
  __constr_expr_2[1] = 2;
//#line  20
  __constr_expr_2[2] = 3;
//#line  20
  if (__constr_expr_2[1] != 2) {
//#line  20
    exit(3);
  }
//#line  22
  exit(0);
}
}
