/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  2 "main.c"
#pragma pack(1)
//#line  4
#pragma pack()
//#line  13 "main.c"
int main(void) 
{ 


  {
//#line  14
  return (0);
}
}
