/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 4 "mergestruct1.c"
struct A {
   int x ;
};
#line 9
extern struct A *connection ;
#line 12
int foo(void) ;
#line 15 "mergestruct1.c"
int foo(void) 
{ 


  {
#line 17
  if (connection) {
#line 18
    return (connection->x);
  } else {
#line 21
    return (3);
  }
}
}
#line 26 "mergestruct1.c"
unsigned char sharedChar  ;
