/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 5 "mergeinline2.c"
__inline static long *fill(void) ;
#line 8 "mergeinline2.c"
int bar(void) 
{ 
  long *w ;
  long *tmp ;

  {
#line 10
  tmp = fill();
#line 10
  w = tmp;
#line 11
  return ((int )*w);
}
}
#line 16 "mergeinline2.c"
__inline static long *fill(void) 
{ 


  {
#line 18
  return ((long *)0);
}
}
