/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 4 "mergestruct2.c"
struct B {
   int y ;
};
#line 9 "mergestruct2.c"
struct B *connection  ;
#line 19
extern int ( /* missing proto */  foo)() ;
#line 12 "mergestruct2.c"
int main(void) 
{ 
  int whatever ;
  int tmp ;

  {
#line 16
  if (connection) {
#line 17
    whatever = connection->y;
  }
#line 19
  tmp = foo();
#line 19
  whatever += tmp;
#line 21
  return (whatever - whatever);
}
}
#line 26 "mergestruct2.c"
unsigned char sharedChar  ;
