/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  5 "multiplestatics.c"
int foo(void) ;
//#line  5 "multiplestatics.c"
static int x  =    0;
//#line  3 "multiplestatics.c"
int foo(void) 
{ 


  {
//#line  6
  return (x);
}
}
//#line  11
int bar(void) ;
//#line  11 "multiplestatics.c"
static int x___0  =    5;
//#line  9 "multiplestatics.c"
int bar(void) 
{ 


  {
//#line  12
  return (x___0);
}
}
//#line  15 "multiplestatics.c"
int main(void) 
{ 
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
//#line  17
  tmp = foo();
//#line  17
  tmp___0 = bar();
//#line  17
  if (tmp + tmp___0 == 5) {
//#line  17
    tmp___1 = 0;
  } else {
//#line  17
    tmp___1 = 1;
  }
//#line  17
  return (tmp___1);
//#line  18
  return (0);
}
}
