/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "oldstyle.c"
static int foo(int x ) ;
//#line  5 "oldstyle.c"
static int foo(int x ) 
{ 


  {
//#line  8
  return (x);
}
}
//#line  11 "oldstyle.c"
int main(void) 
{ 
  int tmp ;

  {
//#line  13
  tmp = foo(0);
//#line  13
  return (tmp);
}
}
