/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  172 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __ssize_t;
//#line  109 "/usr/include/x86_64-linux-gnu/sys/types.h"
typedef __ssize_t ssize_t;
//#line  216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
//#line  156 "/usr/include/fcntl.h"
extern int ( __attribute__((__nonnull__(1))) open)(char const   *__file , int __oflag 
                                                   , ...) ;
//#line  356 "/usr/include/unistd.h"
extern int close(int __fd ) ;
//#line  363
extern ssize_t read(int __fd , void *__buf , size_t __nbytes ) ;
//#line  369
extern ssize_t write(int __fd , void const   *__buf , size_t __n ) ;
//#line  829
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1), __leaf__)) unlink)(char const   *__name ) ;
//#line  362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  846
extern void perror(char const   *__s ) ;
//#line  10 "open.c"
int main(void) 
{ 
  int fd ;
  int tmp ;
  char buf ;
  ssize_t tmp___0 ;
  ssize_t tmp___1 ;
  int tmp___2 ;

  {
//#line  14
  tmp = open("./open_test", 65, 256);
//#line  14
  fd = tmp;
//#line  15
  buf = (char )'a';
//#line  16
  if (fd < 0) {
//#line  17
    perror("open(./open_test, O_CREAT | O_WRONLY, S_IRUSR) < 0");
//#line  18
    return (1);
  }
//#line  21
  tmp___0 = write(fd, (void const   *)(& buf), (size_t )1);
//#line  21
  if (tmp___0 != 1L) {
//#line  22
    perror("write(fd, &buf, 1) != 1");
//#line  23
    return (2);
  }
//#line  25
  close(fd);
//#line  26
  buf = (char)0;
//#line  28
  fd = open("./open_test", 0);
//#line  29
  if (fd < 0) {
//#line  30
    perror("open(./open_test, O_RDONLY) < 0");
//#line  31
    return (3);
  }
//#line  34
  tmp___1 = read(fd, (void *)(& buf), (size_t )1);
//#line  34
  if (tmp___1 != 1L) {
//#line  35
    perror("read(fd, &buf, 1) != 1");
//#line  36
    return (4);
  }
//#line  38
  close(fd);
//#line  39
  if ((int )buf != 97) {
//#line  40
    perror("read wrong value");
//#line  41
    return (5);
  }
//#line  44
  tmp___2 = unlink("./open_test");
//#line  44
  if (tmp___2 != 0) {
//#line  46
    perror("unlink(./open_test) != 0");
//#line  47
    return (6);
  }
//#line  50
  printf((char const   */* __restrict  */)"Open Succeeded!\n");
//#line  51
  return (0);
}
}
