/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
//#line  131 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
//#line  132 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off64_t;
//#line  44 "/usr/include/stdio.h"
struct _IO_FILE ;
//#line  48 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
//#line  150 "/usr/include/libio.h"
typedef void _IO_lock_t;
//#line  156 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
//#line  241 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
//#line  310 "/usr/include/libio.h"
typedef struct _IO_FILE _IO_FILE;
//#line  430
extern int _IO_putc(int __c , _IO_FILE *__fp ) ;
//#line  169 "/usr/include/stdio.h"
extern struct _IO_FILE *stdout ;
//#line  237
extern int fclose(FILE *__stream ) ;
//#line  272
extern FILE *fopen(char const   * __restrict  __filename , char const   * __restrict  __modes ) ;
//#line  531
extern int fgetc(FILE *__stream ) ;
//#line  573
extern int fputc(int __c , FILE *__stream ) ;
//#line  695
extern int puts(char const   *__s ) ;
//#line  829 "/usr/include/unistd.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1), __leaf__)) unlink)(char const   *__name ) ;
//#line  7 "putc.c"
int main(void) 
{ 
  FILE *tmp ;
  int ch ;

  {
//#line  12
  _IO_putc('c', stdout);
//#line  13
  _IO_putc('\n', stdout);
//#line  15
  tmp = fopen((char const   */* __restrict  */)"putc.tmp", (char const   */* __restrict  */)"w");
//#line  16
  fputc('a', tmp);
//#line  17
  fclose(tmp);
//#line  19
  tmp = fopen((char const   */* __restrict  */)"putc.tmp", (char const   */* __restrict  */)"r");
//#line  20
  ch = fgetc(tmp);
//#line  21
  fclose(tmp);
//#line  22
  if (ch != 97) {
//#line  23
    return (4);
  }
//#line  26
  unlink("putc.tmp");
//#line  28
  puts("putc seems to work");
//#line  30
  return (0);
}
}
