/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  7 "regparm0.c"
int ( __attribute__((__regparm__(3), __regparm__(2), __regparm__(0))) do_signal)(int *regs ,
                                                                                 int *oldset ) ;
//#line  11 "regparm0.c"
int main(void) 
{ 
  int r ;
  int o ;
  int tmp ;

  {
//#line  13
  r = 6;
//#line  13
  o = 5;
//#line  14
  tmp = do_signal(& o, & r);
//#line  14
  return (tmp - 11);
}
}
//#line  18 "regparm0.c"
int ( __attribute__((__regparm__(3), __regparm__(2), __regparm__(0))) do_signal)(int *regs ,
                                                                                 int *oldset ) 
{ 


  {
//#line  20
  return (*regs + *oldset);
}
}
