/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "s59.c"
typedef unsigned char hashtyp;
//#line  2 "s59.c"
typedef unsigned short strindx;
//#line  5
struct S59 ;
//#line  5 "s59.c"
typedef struct S59 *idptr;
//#line  6 "s59.c"
struct S59 {
   idptr inext ;
   unsigned char inref ;
   hashtyp ihash ;
   strindx istr ;
};
//#line  13 "s59.c"
void printtok(strindx istr ) 
{ 


  {
//#line  13
  return;
}
}
//#line  15 "s59.c"
void printid(idptr ip ) 
{ 


  {
//#line  19
  printtok(ip->istr);
//#line  20
  return;
}
}
//#line  22 "s59.c"
int main(void) 
{ 


  {
//#line  24
  return (0);
}
}
