/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  69 "/usr/include/assert.h"
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) __assert_fail)(char const   *__assertion ,
                                                                                                   char const   *__file ,
                                                                                                   unsigned int __line ,
                                                                                                   char const   *__function ) ;
//#line  9 "sizeofchar.c"
int main(void) 
{ 
  int sz1 ;
  int sz2 ;
  int i ;
  char array[4095U] ;

  {
//#line  14
  sz1 = (int )sizeof('a');
//#line  15
  if (! ((unsigned long )sz1 == sizeof(int ))) {
//#line  15
    __assert_fail("sz1 == sizeof(int)", "sizeofchar.c", 15U, "main");
  }
//#line  17
  sz2 = (int )sizeof((char )'a');
//#line  18
  if (! ((unsigned long )sz2 == sizeof(char ))) {
//#line  18
    __assert_fail("sz2 == sizeof(char)", "sizeofchar.c", 18U, "main");
  }
//#line  21
  i = '\377';
//#line  25
  if (! (i == -1)) {
//#line  25
    __assert_fail("(int)i == (int)-1", "sizeofchar.c", 25U, "main");
  }
//#line  30
  if (! (sizeof(array) == 4095UL)) {
//#line  30
    __assert_fail("sizeof(array) == 0xfff", "sizeofchar.c", 30U, "main");
  }
//#line  34
  return (0);
}
}
