/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  1 "sockaddr.c"
typedef unsigned short sa_family_t;
//#line  5 "sockaddr.c"
typedef unsigned char uint8_t;
//#line  6 "sockaddr.c"
typedef unsigned short uint16_t;
//#line  7 "sockaddr.c"
typedef unsigned int uint32_t;
//#line  9 "sockaddr.c"
typedef unsigned int socklen_t;
//#line  11 "sockaddr.c"
struct sockaddr {
   sa_family_t sa_family ;
   char sa_data[14] ;
};
//#line  18 "sockaddr.c"
struct in_addr {
   uint32_t s_addr ;
};
//#line  23 "sockaddr.c"
struct sockaddr_in {
   sa_family_t sin_family ;
   uint16_t sin_port ;
   struct in_addr sin_addr ;
   unsigned char sin_zero[((sizeof(struct sockaddr ) - sizeof(unsigned short )) - sizeof(uint16_t )) - sizeof(struct in_addr )] ;
};
//#line  36 "sockaddr.c"
union __anonunion_in6_u_979734923 {
   uint8_t u6_addr8[16] ;
   uint16_t u6_addr16[8] ;
   uint32_t u6_addr32[4] ;
};
//#line  36 "sockaddr.c"
struct in6_addr {
   union __anonunion_in6_u_979734923 in6_u ;
};
//#line  46 "sockaddr.c"
struct sockaddr_in6 {
   sa_family_t sin6_family ;
   uint16_t sin6_port ;
   uint32_t sin6_flowinfo ;
   struct in6_addr sin6_addr ;
};
//#line  55 "sockaddr.c"
struct sockinet {
   sa_family_t si_family ;
   uint16_t si_port ;
};
//#line  55 "sockaddr.c"
union sockunion {
   struct sockinet su_si ;
   struct sockaddr_in su_sin ;
   struct sockaddr_in6 su_sin6 ;
};
//#line  64 "sockaddr.c"
union sockunion server_addr  ;
//#line  82
extern int bind(int __fd , struct sockaddr  const  *__addr , socklen_t __len ) ;
//#line  86 "sockaddr.c"
int main(void) 
{ 
  int ctl_sock ;
  struct sockaddr *addrptr ;

  {
//#line  88
  ctl_sock = 0;
//#line  91
  addrptr = (struct sockaddr *)(& server_addr);
//#line  92
  bind(ctl_sock, (struct sockaddr  const  *)addrptr, (socklen_t )3);
//#line  95
  return (ctl_sock);
}
}
