/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  5 "structattr3.c"
struct S {
   char a ;
} __attribute__((__aligned__(8))) ;
//#line  5 "structattr3.c"
struct S  const  x  =    {(char)1};
//#line  7 "structattr3.c"
struct S y[10]  = {      {(char)1}, 
        {(char)2}, 
        {(char)3}};
//#line  8 "structattr3.c"
int z  =    5;
//#line  10 "structattr3.c"
int main(void) 
{ 


  {
//#line  10
  return (0);
}
}
