/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "structattr.c"
struct A {
   int x ;
} __attribute__((__packed__)) ;
//#line  9 "structattr.c"
struct B {
   int x ;
} __attribute__((__packed__)) ;
//#line  19 "structattr.c"
struct C {
   int x ;
} __attribute__((__packed__)) ;
//#line  24 "structattr.c"
struct D {
   int x ;
} __attribute__((__packed__)) ;
//#line  35 "structattr.c"
struct __anonstruct_e_216488822 {
   int i ;
   char c ;
} __attribute__((__packed__)) ;
//#line  41 "structattr.c"
typedef unsigned long ULONG;
//#line  42 "structattr.c"
typedef int WCHAR;
//#line  43 "structattr.c"
struct _INFORMATION {
   ULONG FileAttributes ;
   ULONG FileNameLength ;
   WCHAR FileName[1] ;
} __attribute__((__packed__, __aligned__(4))) ;
//#line  43 "structattr.c"
typedef struct _INFORMATION INFORMATION;
//#line  43 "structattr.c"
typedef struct _INFORMATION *PINFORMATION;
//#line  7 "structattr.c"
struct A a  ;
//#line  9 "structattr.c"
struct B b  ;
//#line  22 "structattr.c"
struct C c  ;
//#line  24 "structattr.c"
struct D d  ;
//#line  35 "structattr.c"
struct __anonstruct_e_216488822 e  ;
//#line  49 "structattr.c"
INFORMATION i  ;
//#line  50 "structattr.c"
PINFORMATION pi  ;
//#line  52 "structattr.c"
int main(void) 
{ 


  {
//#line  54
  return (0);
}
}
