/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 8 "./structattr2-tmp.c"
struct c {
   int a ;
};
#line 15 "./structattr2-tmp.c"
struct c2 {
   int a ;
};
#line 21 "./structattr2-tmp.c"
struct c3 {
   int a ;
} const  ;
#line 25 "./structattr2-tmp.c"
struct c4 {
   int a ;
} const  ;
#line 28 "./structattr2-tmp.c"
struct c5 {
   char c ;
   int a ;
} __attribute__((__packed__)) ;
#line 31 "./structattr2-tmp.c"
struct c6 {
   char c ;
   int a ;
} __attribute__((__packed__)) ;
#line 34 "./structattr2-tmp.c"
struct c7 {
   char c ;
   int a ;
} __attribute__((__packed__)) ;
#line 37 "./structattr2-tmp.c"
struct c8 {
   char c ;
   int a ;
};
#line 8 "./structattr2-tmp.c"
struct c  const  b  ;
#line 8 "./structattr2-tmp.c"
struct c  const  e  ;
#line 11 "./structattr2-tmp.c"
struct c d  ;
#line 15 "./structattr2-tmp.c"
struct c2  const  b2  ;
#line 15 "./structattr2-tmp.c"
struct c2  const  e2  ;
#line 17 "./structattr2-tmp.c"
struct c2 d2  ;
#line 22 "./structattr2-tmp.c"
struct c3 b3  ;
#line 22 "./structattr2-tmp.c"
struct c3 e3  ;
#line 26 "./structattr2-tmp.c"
struct c4 b4  ;
#line 26 "./structattr2-tmp.c"
struct c4 e4  ;
#line 28 "./structattr2-tmp.c"
struct c5 b5  ;
#line 28 "./structattr2-tmp.c"
struct c5 e5  ;
#line 29 "./structattr2-tmp.c"
struct c5 d5  ;
#line 31 "./structattr2-tmp.c"
struct c6 b6  ;
#line 31 "./structattr2-tmp.c"
struct c6 e6  ;
#line 32 "./structattr2-tmp.c"
struct c6 d6  ;
#line 35 "./structattr2-tmp.c"
struct c7 b7  ;
#line 38 "./structattr2-tmp.c"
struct c8 b8  ;
#line 44 "./structattr2-tmp.c"
int main(void) 
{ 


  {
#line 46
  (d.a) ++;
#line 47
  (e2.a) ++;
#line 48
  (d2.a) ++;
#line 49
  (e3.a) ++;
#line 50
  (e4.a) ++;
#line 60
  return (0);
}
}
