/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  4 "thing.c"
struct Thing ;
//#line  4 "thing.c"
struct Thing *thing  ;
//#line  6 "thing.c"
int test(void) 
{ 


  {
//#line  8
  return ((unsigned long )thing == (unsigned long )((struct Thing *)0));
}
}
//#line  11 "thing.c"
int main(void) 
{ 


  {
//#line  13
  test();
//#line  14
  return (0);
}
}
