/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "transpunion.c"
struct BoxedInt {
   int x ;
};
//#line  7 "transpunion.c"
union __anonunion_CompatArgUnion_633621151 {
   int *intPtr ;
   struct BoxedInt *boxedPtr ;
};
//#line  7 "transpunion.c"
typedef union __anonunion_CompatArgUnion_633621151  __attribute__((__transparent_union__)) CompatArgUnion;
//#line  12
int compatFunc(int firstArg , int *__cil_tmp3 ) ;
//#line  14 "transpunion.c"
int compatFunc(int firstArg , int *__cil_tmp3 ) 
{ 
  CompatArgUnion secondArg ;

  {
//#line  16
  secondArg.intPtr = __cil_tmp3;
//#line  16
  return (firstArg + *(secondArg.intPtr));
}
}
//#line  20 "transpunion.c"
int main(void) 
{ 
  int i ;
  struct BoxedInt b ;
  int ret ;
  int tmp ;
  int tmp___0 ;

  {
//#line  22
  i = 6;
//#line  24
  ret = 0;
//#line  26
  b.x = 7;
//#line  29
  tmp = compatFunc(-6, & i);
//#line  29
  ret += tmp;
//#line  32
  tmp___0 = compatFunc(-7, (int *)(& b));
//#line  32
  ret += tmp___0;
//#line  34
  return (ret);
}
}
