/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  543 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
//#line  8 "trivial-tb.c"
void fail(int val ) 
{ 


  {
//#line  10
  printf((char const   */* __restrict  */)"fail(%d)\n", val);
//#line  11
  exit(val);
}
}
//#line  14 "trivial-tb.c"
int main(void) 
{ 


  {
//#line  19
  fail(4);
//#line  21
  printf((char const   */* __restrict  */)"no failure\n");
//#line  22
  return (0);
}
}
