/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  3 "typeof.c"
int globalInt  ;
//#line  6
extern int ( /* missing proto */  exit)() ;
//#line  5 "typeof.c"
void y(void) 
{ 


  {
//#line  6
  exit(-2);
}
}
//#line  9 "typeof.c"
void typeofVoid(void) 
{ 


  {
//#line  11
  return;
}
}
//#line  14 "typeof.c"
int main(void) 
{ 
  int localInt ;

  {
//#line  17
  typeofVoid();
//#line  18
  localInt = 0;
//#line  19
  return (localInt);
}
}
