/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  9 "uninit_tmp.c"
struct struct_one ;
//#line  11
struct struct_two ;
//#line  13
struct struct_of_interest ;
//#line  4 "uninit_tmp.c"
void *function_of_interest(int x , int y ) 
{ 


  {
//#line  6
  return ((void *)5);
}
}
//#line  9 "uninit_tmp.c"
struct struct_one *bad_function(struct struct_one *os , long x ) 
{ 
  struct struct_two  const  *other_variable ;
  struct struct_of_interest  const  *variable_of_interest ;
  void *tmp ;

  {
//#line  15
  other_variable = (struct struct_two  const  *)0;
//#line  15
  tmp = function_of_interest(0, 0);
//#line  15
  variable_of_interest = (struct struct_of_interest  const  *)tmp;
//#line  22
  return ((struct struct_one *)variable_of_interest);
}
}
//#line  32
extern int ( /* missing proto */  printf)() ;
//#line  25 "uninit_tmp.c"
int main(void) 
{ 
  struct struct_one *p ;

  {
//#line  29
  p = bad_function((struct struct_one *)0, 0L);
//#line  31
  if ((unsigned long )p != (unsigned long )((struct struct_one *)5)) {
//#line  32
    printf("cil bug is still present\n");
//#line  33
    return (2);
  } else {
//#line  36
    printf("bug has been fixed!\n");
//#line  37
    return (0);
  }
}
}
