/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  6 "unionassign.c"
struct S1 {
   int x ;
};
//#line  10 "unionassign.c"
struct S2 {
   char p ;
};
//#line  14 "unionassign.c"
struct S3 {
   int x1 ;
   int y1 ;
};
//#line  19 "unionassign.c"
union U {
   struct S1 s1 ;
   struct S2 s2 ;
   struct S3 s3 ;
};
//#line  36 "unionassign.c"
typedef unsigned short sa_family_t;
//#line  37 "unionassign.c"
typedef unsigned char uint8_t;
//#line  38 "unionassign.c"
typedef unsigned short uint16_t;
//#line  39 "unionassign.c"
typedef unsigned int uint32_t;
//#line  41 "unionassign.c"
struct in_addr {
   uint32_t s_addr ;
};
//#line  45 "unionassign.c"
struct sockaddr {
   sa_family_t sa_family ;
   char sa_data[14] ;
};
//#line  50 "unionassign.c"
struct sockaddr_in {
   sa_family_t sin_family ;
   uint16_t sin_port ;
   struct in_addr sin_addr ;
   unsigned char sin_zero[((sizeof(struct sockaddr ) - sizeof(unsigned short )) - sizeof(uint16_t )) - sizeof(struct in_addr )] ;
};
//#line  59 "unionassign.c"
union __anonunion_in6_u_979734923 {
   uint8_t u6_addr8[16] ;
   uint16_t u6_addr16[8] ;
   uint32_t u6_addr32[4] ;
};
//#line  59 "unionassign.c"
struct in6_addr {
   union __anonunion_in6_u_979734923 in6_u ;
};
//#line  67 "unionassign.c"
struct sockaddr_in6 {
   sa_family_t sin6_family ;
   uint16_t sin6_port ;
   uint32_t sin6_flowinfo ;
   struct in6_addr sin6_addr ;
};
//#line  74 "unionassign.c"
struct sockinet {
   sa_family_t si_family ;
   uint16_t si_port ;
};
//#line  74 "unionassign.c"
union sockunion {
   struct sockinet su_si ;
   struct sockaddr_in su_sin ;
   struct sockaddr_in6 su_sin6 ;
};
//#line  25 "unionassign.c"
int main(void) 
{ 
  union U x ;
  union U y ;

  {
//#line  28
  x.s1.x = 5;
//#line  29
  y = x;
//#line  30
  return (y.s1.x - 5);
}
}
//#line  83 "unionassign.c"
int foo(void) 
{ 
  union sockunion x ;
  union sockunion y ;

  {
//#line  86
  x = y;
//#line  87
  return (3);
}
}
