/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
//#line  5 "unscomp.c"
int main(void) 
{ 
  unsigned long size ;
  long offset ;

  {
//#line  10
  size = 1024UL;
//#line  11
  offset = 50L;
//#line  13
  offset = (long )((unsigned long )offset - size);
//#line  13
  if (offset >= 0L) {
//#line  15
    printf((char const   */* __restrict  */)"no -- this is wrong\n");
//#line  16
    return (2);
  }
//#line  21
  offset = 50L;
//#line  22
  if ((unsigned long )offset - size < 0UL) {
//#line  23
    printf((char const   */* __restrict  */)"This is also wrong\n");
//#line  23
    return (3);
  }
//#line  26
  printf((char const   */* __restrict  */)"yes this is right\n");
//#line  27
  return (0);
}
}
