/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  7 "volatilestruct.c"
struct foo {
   int AAAAAAAAAAAAAAAAAAA : 7 ;
};
//#line  14 "volatilestruct.c"
struct foo___0 {
   double BBBBBBBBBBBBBBBBBBB ;
};
//#line  7 "volatilestruct.c"
struct foo xxx  ;
//#line  19 "volatilestruct.c"
static struct foo___0 baz  ;
//#line  12 "volatilestruct.c"
int main(void) 
{ 
  struct foo___0  volatile  bar ;

  {
//#line  20
  bar = (struct foo___0  volatile  )baz;
//#line  22
  return (0);
}
}
