/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

//#line  6 "xcheckers.c"
struct _XDisplay ;
//#line  6 "xcheckers.c"
typedef struct _XDisplay Display;
//#line  11 "xcheckers.c"
Display *dpy  ;
//#line  12 "xcheckers.c"
unsigned long paper  ;
//#line  26 "xcheckers.c"
int main(void) 
{ 


  {
//#line  27
  return (0);
}
}
